// Command genwalker generates walk_generated.go from parsenodes.go and node.go.
//
// It scans all struct types in those files, identifies fields whose types are
// Node (interface), []Node, or pointers to other AST structs, and generates
// the walkChildren function that enumerates child nodes for Walk.
//
// Usage:
//
//	go run ./snowflake/ast/cmd/genwalker
//
// or via go generate:
//
//	go generate ./snowflake/ast/...
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

func main() {
	fset := token.NewFileSet()

	// Parse both source files. The generator runs from the snowflake/ast
	// directory thanks to //go:generate go run ./cmd/genwalker in walk.go,
	// so the relative paths point at sibling files.
	sources := []string{"parsenodes.go", "node.go"}
	var files []*ast.File
	for _, src := range sources {
		f, err := parser.ParseFile(fset, src, nil, 0)
		if err != nil {
			fmt.Fprintf(os.Stderr, "parse %s: %v\n", src, err)
			os.Exit(1)
		}
		files = append(files, f)
	}

	// Collect all struct type names so we can detect pointer-to-known-struct
	// fields below.
	structNames := map[string]bool{}
	type field struct {
		Name string
		Type string // "Node", "[]Node", "*SelectStmt", etc.
	}
	type structInfo struct {
		Name   string
		Fields []field
	}

	var structs []structInfo

	// nodeStructs tracks which structs implement the Node interface (have a Tag() method).
	// Only these structs get their own case in the walkChildren switch, and only
	// pointer-to-Node-struct fields generate Walk calls.
	nodeStructs := map[string]bool{}

	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				if _, ok := ts.Type.(*ast.StructType); ok {
					structNames[ts.Name.Name] = true
				}
			}
		}
		// Scan function declarations for Tag() methods to identify Node types.
		for _, decl := range f.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Recv == nil || fd.Name.Name != "Tag" {
				continue
			}
			// Check it returns NodeTag and has no parameters.
			if fd.Type.Params != nil && len(fd.Type.Params.List) > 0 {
				continue
			}
			if fd.Type.Results == nil || len(fd.Type.Results.List) != 1 {
				continue
			}
			// Extract the receiver type name (handles both *T and T receivers).
			for _, recv := range fd.Recv.List {
				recvName := ""
				switch rt := recv.Type.(type) {
				case *ast.StarExpr:
					if id, ok := rt.X.(*ast.Ident); ok {
						recvName = id.Name
					}
				case *ast.Ident:
					recvName = rt.Name
				}
				if recvName != "" {
					nodeStructs[recvName] = true
				}
			}
		}
	}

	// Collect fields for each struct.
	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				var fields []field
				for _, fld := range st.Fields.List {
					if len(fld.Names) == 0 {
						continue // embedded
					}
					typStr := typeString(fld.Type)
					if isChildType(typStr, nodeStructs) {
						for _, name := range fld.Names {
							fields = append(fields, field{Name: name.Name, Type: typStr})
						}
					}
				}
				structs = append(structs, structInfo{Name: ts.Name.Name, Fields: fields})
			}
		}
	}

	// Sort by name for deterministic output.
	sort.Slice(structs, func(i, j int) bool {
		return structs[i].Name < structs[j].Name
	})

	// Generate code.
	var buf bytes.Buffer
	buf.WriteString("// Code generated by genwalker; DO NOT EDIT.\n\n")
	buf.WriteString("package ast\n\n")
	buf.WriteString("// walkChildren walks the child nodes of node, calling Walk(v, child)\n")
	buf.WriteString("// for each child. This function is generated from parsenodes.go and node.go.\n")
	buf.WriteString("func walkChildren(v Visitor, node Node) {\n")
	buf.WriteString("\tswitch n := node.(type) {\n")

	for _, s := range structs {
		if len(s.Fields) == 0 {
			continue
		}
		// Only emit cases for structs that implement Node (have a Tag() method).
		if !nodeStructs[s.Name] {
			continue
		}
		fmt.Fprintf(&buf, "\tcase *%s:\n", s.Name)
		for _, f := range s.Fields {
			switch f.Type {
			case "Node":
				fmt.Fprintf(&buf, "\t\tWalk(v, n.%s)\n", f.Name)
			case "[]Node":
				fmt.Fprintf(&buf, "\t\twalkNodes(v, n.%s)\n", f.Name)
			default:
				// Pointer to a known struct type (e.g. *SelectStmt).
				fmt.Fprintf(&buf, "\t\tif n.%s != nil {\n", f.Name)
				fmt.Fprintf(&buf, "\t\t\tWalk(v, n.%s)\n", f.Name)
				fmt.Fprintf(&buf, "\t\t}\n")
			}
		}
	}

	buf.WriteString("\t}\n")
	buf.WriteString("}\n")

	// Format with gofmt rules.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		// Write unformatted output for debugging.
		_ = os.WriteFile("walk_generated.go", buf.Bytes(), 0644)
		os.Exit(1)
	}

	if err := os.WriteFile("walk_generated.go", formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	// Stats.
	cases := 0
	fields := 0
	for _, s := range structs {
		if len(s.Fields) > 0 && nodeStructs[s.Name] {
			cases++
			fields += len(s.Fields)
		}
	}
	fmt.Printf("Generated walk_generated.go: %d cases, %d child fields\n", cases, fields)
}

// typeString returns the string representation of a Go type expression.
// Supports identifiers, pointers, selector expressions, and slice types.
func typeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		return "[]" + typeString(t.Elt)
	default:
		return ""
	}
}

// isChildType reports whether typStr represents a field that walkChildren
// should descend into.
//
// Recognized shapes:
//   - "Node"             — the Node interface
//   - "[]Node"           — slice of nodes
//   - "*<NodeStruct>"    — pointer to a struct that implements Node (has Tag() method)
//
// Excluded: pointer to "Loc" (Loc is not a node), pointer to non-Node structs
// (helper types like WhenClause, WindowSpec, etc.), and any other shape.
func isChildType(typStr string, nodeStructs map[string]bool) bool {
	if typStr == "Node" {
		return true
	}
	if typStr == "[]Node" {
		return true
	}
	if strings.HasPrefix(typStr, "*") {
		name := typStr[1:]
		if name == "Loc" {
			return false
		}
		return nodeStructs[name]
	}
	return false
}
