package ast

// NodeLoc returns the source location of n, or NoLoc() if n is nil or its
// concrete type carries no Loc field. Every concrete node type added under
// doris/ast must add a case here.
//
// The pattern matches snowflake/ast.NodeLoc.
func NodeLoc(n Node) Loc {
	if n == nil {
		return NoLoc()
	}
	switch v := n.(type) {
	case *File:
		return v.Loc
	case *ObjectName:
		return v.Loc
	case *TypeName:
		return v.Loc
	case *CreateIndexStmt:
		return v.Loc
	case *DropIndexStmt:
		return v.Loc
	case *BuildIndexStmt:
		return v.Loc
	case *CreateDatabaseStmt:
		return v.Loc
	case *AlterDatabaseStmt:
		return v.Loc
	case *DropDatabaseStmt:
		return v.Loc
	case *Property:
		return v.Loc
	case *BinaryExpr:
		return v.Loc
	case *UnaryExpr:
		return v.Loc
	case *IsExpr:
		return v.Loc
	case *BetweenExpr:
		return v.Loc
	case *InExpr:
		return v.Loc
	case *LikeExpr:
		return v.Loc
	case *RegexpExpr:
		return v.Loc
	case *FuncCallExpr:
		return v.Loc
	case *CastExpr:
		return v.Loc
	case *CaseExpr:
		return v.Loc
	case *WhenClause:
		return v.Loc
	case *SubqueryExpr:
		return v.Loc
	case *ColumnRef:
		return v.Loc
	case *Literal:
		return v.Loc
	case *ParenExpr:
		return v.Loc
	case *ExistsExpr:
		return v.Loc
	case *IntervalExpr:
		return v.Loc
	case *OrderByItem:
		return v.Loc
	case *WithClause:
		return v.Loc
	case *CTE:
		return v.Loc
	case *SelectStmt:
		return v.Loc
	case *SelectItem:
		return v.Loc
	case *TableRef:
		return v.Loc
	case *JoinClause:
		return v.Loc
	case *SetOpStmt:
		return v.Loc
	case *CreateTableStmt:
		return v.Loc
	case *ColumnDef:
		return v.Loc
	case *IndexDef:
		return v.Loc
	case *TableConstraint:
		return v.Loc
	case *KeyDesc:
		return v.Loc
	case *PartitionDesc:
		return v.Loc
	case *PartitionItem:
		return v.Loc
	case *DistributionDesc:
		return v.Loc
	case *RollupDef:
		return v.Loc
	case *RawQuery:
		return v.Loc
	case *AlterTableStmt:
		return v.Loc
	case *AlterTableAction:
		return v.Loc
	case *ViewColumn:
		return v.Loc
	case *CreateViewStmt:
		return v.Loc
	case *AlterViewStmt:
		return v.Loc
	case *DropViewStmt:
		return v.Loc
	case *InsertStmt:
		return v.Loc
	case *Assignment:
		return v.Loc
	case *UpdateStmt:
		return v.Loc
	case *DeleteStmt:
		return v.Loc
	case *MergeStmt:
		return v.Loc
	case *MergeClause:
		return v.Loc
	case *TruncateTableStmt:
		return v.Loc
	case *CopyIntoStmt:
		return v.Loc
	case *LoadDataDesc:
		return v.Loc
	case *LoadDataStmt:
		return v.Loc
	case *ExportStmt:
		return v.Loc
	case *CreateRoutineLoadStmt:
		return v.Loc
	case *AlterRoutineLoadStmt:
		return v.Loc
	case *PauseRoutineLoadStmt:
		return v.Loc
	case *ResumeRoutineLoadStmt:
		return v.Loc
	case *StopRoutineLoadStmt:
		return v.Loc
	case *ShowRoutineLoadStmt:
		return v.Loc
	case *ShowRoutineLoadTaskStmt:
		return v.Loc
	case *SyncStmt:
		return v.Loc
	case *MTMVRefreshTrigger:
		return v.Loc
	case *CreateMTMVStmt:
		return v.Loc
	case *AlterMTMVStmt:
		return v.Loc
	case *DropMTMVStmt:
		return v.Loc
	case *RefreshMTMVStmt:
		return v.Loc
	case *PauseMTMVJobStmt:
		return v.Loc
	case *ResumeMTMVJobStmt:
		return v.Loc
	case *CancelMTMVTaskStmt:
		return v.Loc
	case *CreateCatalogStmt:
		return v.Loc
	case *AlterCatalogStmt:
		return v.Loc
	case *DropCatalogStmt:
		return v.Loc
	case *RefreshCatalogStmt:
		return v.Loc
	case *CreateStorageVaultStmt:
		return v.Loc
	case *AlterStorageVaultStmt:
		return v.Loc
	case *DropStorageVaultStmt:
		return v.Loc
	case *SetDefaultStorageVaultStmt:
		return v.Loc
	case *UnsetDefaultStorageVaultStmt:
		return v.Loc
	case *CreateStoragePolicyStmt:
		return v.Loc
	case *AlterStoragePolicyStmt:
		return v.Loc
	case *DropStoragePolicyStmt:
		return v.Loc
	case *CreateRepositoryStmt:
		return v.Loc
	case *AlterRepositoryStmt:
		return v.Loc
	case *DropRepositoryStmt:
		return v.Loc
	case *CreateStageStmt:
		return v.Loc
	case *DropStageStmt:
		return v.Loc
	case *CreateFileStmt:
		return v.Loc
	case *DropFileStmt:
		return v.Loc
	case *CreateWorkloadGroupStmt:
		return v.Loc
	case *AlterWorkloadGroupStmt:
		return v.Loc
	case *DropWorkloadGroupStmt:
		return v.Loc
	case *WorkloadPolicyItem:
		return v.Loc
	case *CreateWorkloadPolicyStmt:
		return v.Loc
	case *AlterWorkloadPolicyStmt:
		return v.Loc
	case *DropWorkloadPolicyStmt:
		return v.Loc
	case *CreateResourceStmt:
		return v.Loc
	case *AlterResourceStmt:
		return v.Loc
	case *DropResourceStmt:
		return v.Loc
	case *CreateSQLBlockRuleStmt:
		return v.Loc
	case *AlterSQLBlockRuleStmt:
		return v.Loc
	case *DropSQLBlockRuleStmt:
		return v.Loc
	case *CreateRowPolicyStmt:
		return v.Loc
	case *DropRowPolicyStmt:
		return v.Loc
	case *CreateEncryptKeyStmt:
		return v.Loc
	case *DropEncryptKeyStmt:
		return v.Loc
	case *DictionaryColumn:
		return v.Loc
	case *CreateDictionaryStmt:
		return v.Loc
	case *AlterDictionaryStmt:
		return v.Loc
	case *DropDictionaryStmt:
		return v.Loc
	case *RefreshDictionaryStmt:
		return v.Loc
	case *CreateRoleStmt:
		return v.Loc
	case *AlterRoleStmt:
		return v.Loc
	case *DropRoleStmt:
		return v.Loc
	case *UserIdentity:
		return v.Loc
	case *CreateUserStmt:
		return v.Loc
	case *AlterUserStmt:
		return v.Loc
	case *DropUserStmt:
		return v.Loc
	case *SetPasswordStmt:
		return v.Loc
	case *GrantStmt:
		return v.Loc
	case *RevokeStmt:
		return v.Loc
	case *BeginStmt:
		return v.Loc
	case *CommitStmt:
		return v.Loc
	case *RollbackStmt:
		return v.Loc
	case *ShowStmt:
		return v.Loc
	case *DescribeStmt:
		return v.Loc
	case *ExplainStmt:
		return v.Loc
	case *UseStmt:
		return v.Loc
	case *SetStmt:
		return v.Loc
	case *SetItem:
		return v.Loc
	case *UnsetStmt:
		return v.Loc
	case *HelpStmt:
		return v.Loc
	case *AdminStmt:
		return v.Loc
	case *SystemAlterStmt:
		return v.Loc
	case *CancelDecommissionStmt:
		return v.Loc
	case *BackupStmt:
		return v.Loc
	case *RestoreStmt:
		return v.Loc
	case *KillStmt:
		return v.Loc
	case *LockTablesStmt:
		return v.Loc
	case *LockItem:
		return v.Loc
	case *UnlockTablesStmt:
		return v.Loc
	case *InstallPluginStmt:
		return v.Loc
	case *UninstallPluginStmt:
		return v.Loc
	case *WarmUpStmt:
		return v.Loc
	case *CleanStmt:
		return v.Loc
	case *CancelStmt:
		return v.Loc
	case *RecoverStmt:
	// Job DDL nodes (T8.1).
	case *JobSchedule:
		return v.Loc
	case *CreateJobStmt:
		return v.Loc
	case *AlterJobStmt:
		return v.Loc
	case *DropJobStmt:
		return v.Loc
	case *PauseJobStmt:
		return v.Loc
	case *ResumeJobStmt:
		return v.Loc
	case *CancelTaskStmt:
		return v.Loc
	case *ShowJobStmt:
		return v.Loc
	case *ShowJobTaskStmt:
		return v.Loc
	default:
		return NoLoc()
	}
}

// SpanNodes returns the smallest Loc that covers every node in nodes.
// Nil entries and nodes whose Loc is invalid are skipped. Returns NoLoc()
// when no node has a valid Loc (including the empty-args case).
func SpanNodes(nodes ...Node) Loc {
	out := NoLoc()
	for _, n := range nodes {
		if n == nil {
			continue
		}
		out = out.Merge(NodeLoc(n))
	}
	return out
}
