package parser

import "strings"

// KeywordToken returns the kw* constant for name (case-insensitive) and true
// if name is a recognized GoogleSQL word-keyword; (0, false) otherwise.
func KeywordToken(name string) (int, bool) {
	t, ok := keywordMap[strings.ToLower(name)]
	return t, ok
}

// IsReservedKeyword reports whether name (case-insensitive) is a reserved
// keyword that cannot be used as a bare (unquoted, non-backtick) identifier.
//
// The reserved/non-reserved split is driven by the legacy
// GoogleSQLParser.g4 common_keyword_as_identifier rule: a word-keyword is
// non-reserved iff it appears there (plus SIMPLE, added by
// keyword_as_identifier). keywordReserved below is the complement set —
// every word-keyword NOT in common_keyword_as_identifier. The lexer itself
// does not enforce this; it always emits the kw* token. The parser consults
// IsReservedKeyword when deciding whether a keyword may stand in as an
// identifier.
func IsReservedKeyword(name string) bool {
	t, ok := KeywordToken(name)
	return ok && keywordReserved[t]
}

// keywordName returns the upper-case name of a keyword token, for TokenName
// debug output. Builds a reverse-lookup map on first use. Not thread-safe —
// only called from tests and debug paths.
var keywordNameCache map[int]string

func keywordName(t int) (string, bool) {
	if keywordNameCache == nil {
		keywordNameCache = make(map[int]string, len(keywordMap))
		for name, tok := range keywordMap {
			keywordNameCache[tok] = strings.ToUpper(name)
		}
	}
	name, ok := keywordNameCache[t]
	return name, ok
}

// keywordMap maps each lower-cased GoogleSQL word-keyword to its kw* token.
// Generated from GoogleSQLLexer.g4 (308 entries). Keywords are matched
// case-insensitively (GoogleSQLLexer.g4 sets caseInsensitive = true).
var keywordMap = map[string]int{
	"array":                          kwARRAY,
	"all":                            kwALL,
	"as":                             kwAS,
	"asc":                            kwASC,
	"by":                             kwBY,
	"cross":                          kwCROSS,
	"join":                           kwJOIN,
	"delta":                          kwDELTA,
	"desc":                           kwDESC,
	"differential_privacy":           kwDIFFERENTIAL_PRIVACY,
	"distinct":                       kwDISTINCT,
	"epsilon":                        kwEPSILON,
	"except":                         kwEXCEPT,
	"exclude":                        kwEXCLUDE,
	"for":                            kwFOR,
	"from":                           kwFROM,
	"full":                           kwFULL,
	"in":                             kwIN,
	"include":                        kwINCLUDE,
	"inner":                          kwINNER,
	"intersect":                      kwINTERSECT,
	"left":                           kwLEFT,
	"limit":                          kwLIMIT,
	"max_groups_contributed":         kwMAX_GROUPS_CONTRIBUTED,
	"null":                           kwNULL,
	"nulls":                          kwNULLS,
	"of":                             kwOF,
	"offset":                         kwOFFSET,
	"on":                             kwON,
	"options":                        kwOPTIONS,
	"order":                          kwORDER,
	"outer":                          kwOUTER,
	"percent":                        kwPERCENT,
	"pivot":                          kwPIVOT,
	"privacy_unit_column":            kwPRIVACY_UNIT_COLUMN,
	"right":                          kwRIGHT,
	"recursive":                      kwRECURSIVE,
	"replace":                        kwREPLACE,
	"unpivot":                        kwUNPIVOT,
	"select":                         kwSELECT,
	"struct":                         kwSTRUCT,
	"system":                         kwSYSTEM,
	"system_time":                    kwSYSTEM_TIME,
	"tablesample":                    kwTABLESAMPLE,
	"union":                          kwUNION,
	"unnest":                         kwUNNEST,
	"using":                          kwUSING,
	"value":                          kwVALUE,
	"with":                           kwWITH,
	"true":                           kwTRUE,
	"false":                          kwFALSE,
	"numeric":                        kwNUMERIC,
	"decimal":                        kwDECIMAL,
	"bignumeric":                     kwBIGNUMERIC,
	"bigdecimal":                     kwBIGDECIMAL,
	"not":                            kwNOT,
	"and":                            kwAND,
	"or":                             kwOR,
	"json":                           kwJSON,
	"date":                           kwDATE,
	"time":                           kwTIME,
	"datetime":                       kwDATETIME,
	"timestamp":                      kwTIMESTAMP,
	"range":                          kwRANGE,
	"interval":                       kwINTERVAL,
	"simple":                         kwSIMPLE,
	"abort":                          kwABORT,
	"access":                         kwACCESS,
	"action":                         kwACTION,
	"aggregate":                      kwAGGREGATE,
	"add":                            kwADD,
	"alter":                          kwALTER,
	"always":                         kwALWAYS,
	"analyze":                        kwANALYZE,
	"approx":                         kwAPPROX,
	"are":                            kwARE,
	"assert":                         kwASSERT,
	"batch":                          kwBATCH,
	"begin":                          kwBEGIN,
	"break":                          kwBREAK,
	"call":                           kwCALL,
	"cascade":                        kwCASCADE,
	"check":                          kwCHECK,
	"clamped":                        kwCLAMPED,
	"clone":                          kwCLONE,
	"copy":                           kwCOPY,
	"cluster":                        kwCLUSTER,
	"column":                         kwCOLUMN,
	"columns":                        kwCOLUMNS,
	"commit":                         kwCOMMIT,
	"connection":                     kwCONNECTION,
	"constant":                       kwCONSTANT,
	"constraint":                     kwCONSTRAINT,
	"continue":                       kwCONTINUE,
	"corresponding":                  kwCORRESPONDING,
	"cycle":                          kwCYCLE,
	"data":                           kwDATA,
	"database":                       kwDATABASE,
	"declare":                        kwDECLARE,
	"definer":                        kwDEFINER,
	"delete":                         kwDELETE,
	"deletion":                       kwDELETION,
	"depth":                          kwDEPTH,
	"describe":                       kwDESCRIBE,
	"deterministic":                  kwDETERMINISTIC,
	"do":                             kwDO,
	"drop":                           kwDROP,
	"elseif":                         kwELSEIF,
	"enforced":                       kwENFORCED,
	"error":                          kwERROR,
	"exception":                      kwEXCEPTION,
	"execute":                        kwEXECUTE,
	"explain":                        kwEXPLAIN,
	"export":                         kwEXPORT,
	"extend":                         kwEXTEND,
	"external":                       kwEXTERNAL,
	"files":                          kwFILES,
	"filter":                         kwFILTER,
	"fill":                           kwFILL,
	"first":                          kwFIRST,
	"foreign":                        kwFOREIGN,
	"format":                         kwFORMAT,
	"function":                       kwFUNCTION,
	"generated":                      kwGENERATED,
	"grant":                          kwGRANT,
	"group_rows":                     kwGROUP_ROWS,
	"hidden":                         kwHIDDEN,
	"identity":                       kwIDENTITY,
	"immediate":                      kwIMMEDIATE,
	"immutable":                      kwIMMUTABLE,
	"import":                         kwIMPORT,
	"increment":                      kwINCREMENT,
	"index":                          kwINDEX,
	"inout":                          kwINOUT,
	"input":                          kwINPUT,
	"insert":                         kwINSERT,
	"invoker":                        kwINVOKER,
	"isolation":                      kwISOLATION,
	"iterate":                        kwITERATE,
	"key":                            kwKEY,
	"language":                       kwLANGUAGE,
	"last":                           kwLAST,
	"leave":                          kwLEAVE,
	"level":                          kwLEVEL,
	"load":                           kwLOAD,
	"loop":                           kwLOOP,
	"macro":                          kwMACRO,
	"map":                            kwMAP,
	"match":                          kwMATCH,
	"kw_match_recognize_nonreserved": kwKW_MATCH_RECOGNIZE_NONRESERVED,
	"matched":                        kwMATCHED,
	"materialized":                   kwMATERIALIZED,
	"max":                            kwMAX,
	"maxvalue":                       kwMAXVALUE,
	"measures":                       kwMEASURES,
	"message":                        kwMESSAGE,
	"metadata":                       kwMETADATA,
	"min":                            kwMIN,
	"minvalue":                       kwMINVALUE,
	"model":                          kwMODEL,
	"module":                         kwMODULE,
	"only":                           kwONLY,
	"out":                            kwOUT,
	"output":                         kwOUTPUT,
	"overwrite":                      kwOVERWRITE,
	"partitions":                     kwPARTITIONS,
	"pattern":                        kwPATTERN,
	"policies":                       kwPOLICIES,
	"policy":                         kwPOLICY,
	"primary":                        kwPRIMARY,
	"private":                        kwPRIVATE,
	"privilege":                      kwPRIVILEGE,
	"privileges":                     kwPRIVILEGES,
	"procedure":                      kwPROCEDURE,
	"project":                        kwPROJECT,
	"public":                         kwPUBLIC,
	"raise":                          kwRAISE,
	"read":                           kwREAD,
	"references":                     kwREFERENCES,
	"remote":                         kwREMOTE,
	"remove":                         kwREMOVE,
	"rename":                         kwRENAME,
	"repeat":                         kwREPEAT,
	"repeatable":                     kwREPEATABLE,
	"replace_fields":                 kwREPLACE_FIELDS,
	"replica":                        kwREPLICA,
	"report":                         kwREPORT,
	"restrict":                       kwRESTRICT,
	"restriction":                    kwRESTRICTION,
	"returns":                        kwRETURNS,
	"return":                         kwRETURN,
	"revoke":                         kwREVOKE,
	"rollback":                       kwROLLBACK,
	"row":                            kwROW,
	"run":                            kwRUN,
	"safe_cast":                      kwSAFE_CAST,
	"schema":                         kwSCHEMA,
	"search":                         kwSEARCH,
	"security":                       kwSECURITY,
	"sequence":                       kwSEQUENCE,
	"sets":                           kwSETS,
	"set":                            kwSET,
	"show":                           kwSHOW,
	"snapshot":                       kwSNAPSHOT,
	"source":                         kwSOURCE,
	"sql":                            kwSQL,
	"stable":                         kwSTABLE,
	"start":                          kwSTART,
	"static_describe":                kwSTATIC_DESCRIBE,
	"stored":                         kwSTORED,
	"storing":                        kwSTORING,
	"strict":                         kwSTRICT,
	"table":                          kwTABLE,
	"tables":                         kwTABLES,
	"target":                         kwTARGET,
	"temp":                           kwTEMP,
	"temporary":                      kwTEMPORARY,
	"transaction":                    kwTRANSACTION,
	"transform":                      kwTRANSFORM,
	"truncate":                       kwTRUNCATE,
	"type":                           kwTYPE,
	"undrop":                         kwUNDROP,
	"unique":                         kwUNIQUE,
	"unknown":                        kwUNKNOWN,
	"until":                          kwUNTIL,
	"update":                         kwUPDATE,
	"values":                         kwVALUES,
	"vector":                         kwVECTOR,
	"view":                           kwVIEW,
	"views":                          kwVIEWS,
	"volatile":                       kwVOLATILE,
	"weight":                         kwWEIGHT,
	"while":                          kwWHILE,
	"write":                          kwWRITE,
	"zone":                           kwZONE,
	"descriptor":                     kwDESCRIPTOR,
	"interleave":                     kwINTERLEAVE,
	"null_filtered":                  kwNULL_FILTERED,
	"parent":                         kwPARENT,
	"new":                            kwNEW,
	"end":                            kwEND,
	"case":                           kwCASE,
	"when":                           kwWHEN,
	"then":                           kwTHEN,
	"else":                           kwELSE,
	"cast":                           kwCAST,
	"extract":                        kwEXTRACT,
	"collate":                        kwCOLLATE,
	"if":                             kwIF,
	"grouping":                       kwGROUPING,
	"having":                         kwHAVING,
	"group":                          kwGROUP,
	"rollup":                         kwROLLUP,
	"cube":                           kwCUBE,
	"hash":                           kwHASH,
	"proto":                          kwPROTO,
	"partition":                      kwPARTITION,
	"ignore":                         kwIGNORE,
	"respect":                        kwRESPECT,
	"rows":                           kwROWS,
	"over":                           kwOVER,
	"between":                        kwBETWEEN,
	"unbounded":                      kwUNBOUNDED,
	"current":                        kwCURRENT,
	"preceding":                      kwPRECEDING,
	"following":                      kwFOLLOWING,
	"natural":                        kwNATURAL,
	"qualify":                        kwQUALIFY,
	"default":                        kwDEFAULT,
	"slash":                          kwSLASH,
	"match_recognize":                kwMATCH_RECOGNIZE,
	"define":                         kwDEFINE,
	"lookup":                         kwLOOKUP,
	"where":                          kwWHERE,
	"window":                         kwWINDOW,
	"to":                             kwTO,
	"exists":                         kwEXISTS,
	"any":                            kwANY,
	"some":                           kwSOME,
	"like":                           kwLIKE,
	"is":                             kwIS,
	"no":                             kwNO,
	"into":                           kwINTO,
	"assert_rows_modified":           kwASSERT_ROWS_MODIFIED,
	"conflict":                       kwCONFLICT,
	"nothing":                        kwNOTHING,
	"merge":                          kwMERGE,
	"create":                         kwCREATE,
	"enum":                           kwENUM,
	"destination":                    kwDESTINATION,
	"property":                       kwPROPERTY,
	"graph":                          kwGRAPH,
	"node":                           kwNODE,
	"properties":                     kwPROPERTIES,
	"label":                          kwLABEL,
	"edge":                           kwEDGE,
	"next":                           kwNEXT,
	"ascending":                      kwASCENDING,
	"descending":                     kwDESCENDING,
	"skip":                           kwSKIP,
	"shortest":                       kwSHORTEST,
	"path":                           kwPATH,
	"paths":                          kwPATHS,
	"walk":                           kwWALK,
	"trail":                          kwTRAIL,
	"acyclic":                        kwACYCLIC,
	"optional":                       kwOPTIONAL,
	"let":                            kwLET,
}

// keywordReserved marks the 97 reserved word-keywords — those NOT present in
// the legacy GoogleSQLParser.g4 common_keyword_as_identifier rule. A reserved
// keyword cannot be used as a bare identifier without backtick-quoting.
// Generated by set-difference (all 308 word-keywords minus the 211
// non-reserved members of common_keyword_as_identifier, which itself excludes
// SIMPLE — SIMPLE is non-reserved via keyword_as_identifier). The
// keyword_completeness_test.go drift detector recomputes this split from the
// grammar and fails on any mismatch.
var keywordReserved = map[int]bool{
	kwALL:                    true,
	kwAND:                    true,
	kwANY:                    true,
	kwARRAY:                  true,
	kwAS:                     true,
	kwASC:                    true,
	kwASSERT_ROWS_MODIFIED:   true,
	kwBETWEEN:                true,
	kwBY:                     true,
	kwCASE:                   true,
	kwCAST:                   true,
	kwCOLLATE:                true,
	kwCREATE:                 true,
	kwCROSS:                  true,
	kwCUBE:                   true,
	kwCURRENT:                true,
	kwDEFAULT:                true,
	kwDEFINE:                 true,
	kwDELTA:                  true,
	kwDESC:                   true,
	kwDIFFERENTIAL_PRIVACY:   true,
	kwDISTINCT:               true,
	kwELSE:                   true,
	kwEND:                    true,
	kwENUM:                   true,
	kwEPSILON:                true,
	kwEXCEPT:                 true,
	kwEXCLUDE:                true,
	kwEXISTS:                 true,
	kwEXTRACT:                true,
	kwFALSE:                  true,
	kwFOLLOWING:              true,
	kwFOR:                    true,
	kwFROM:                   true,
	kwFULL:                   true,
	kwGROUP:                  true,
	kwGROUPING:               true,
	kwHASH:                   true,
	kwHAVING:                 true,
	kwIF:                     true,
	kwIGNORE:                 true,
	kwIN:                     true,
	kwINNER:                  true,
	kwINTERSECT:              true,
	kwINTERVAL:               true,
	kwINTO:                   true,
	kwIS:                     true,
	kwJOIN:                   true,
	kwLEFT:                   true,
	kwLIKE:                   true,
	kwLIMIT:                  true,
	kwLOOKUP:                 true,
	kwMATCH_RECOGNIZE:        true,
	kwMAX_GROUPS_CONTRIBUTED: true,
	kwMERGE:                  true,
	kwNATURAL:                true,
	kwNEW:                    true,
	kwNO:                     true,
	kwNOT:                    true,
	kwNOTHING:                true,
	kwNULL:                   true,
	kwNULLS:                  true,
	kwOF:                     true,
	kwON:                     true,
	kwOR:                     true,
	kwORDER:                  true,
	kwOUTER:                  true,
	kwOVER:                   true,
	kwPARTITION:              true,
	kwPRECEDING:              true,
	kwPRIVACY_UNIT_COLUMN:    true,
	kwPROTO:                  true,
	kwQUALIFY:                true,
	kwRANGE:                  true,
	kwRECURSIVE:              true,
	kwRESPECT:                true,
	kwRIGHT:                  true,
	kwROLLUP:                 true,
	kwROWS:                   true,
	kwSELECT:                 true,
	kwSET:                    true,
	kwSHORTEST:               true,
	kwSLASH:                  true,
	kwSOME:                   true,
	kwSTRUCT:                 true,
	kwTABLESAMPLE:            true,
	kwTHEN:                   true,
	kwTO:                     true,
	kwTRUE:                   true,
	kwUNBOUNDED:              true,
	kwUNION:                  true,
	kwUNNEST:                 true,
	kwUSING:                  true,
	kwWHEN:                   true,
	kwWHERE:                  true,
	kwWINDOW:                 true,
	kwWITH:                   true,
}
