package parser

import (
	"testing"
)

// TestParseDatabaseStmts tests parsing of CREATE/ALTER DATABASE,
// CREATE/ALTER PLUGGABLE DATABASE, CREATE/ALTER/DROP DISKGROUP,
// and CREATE CONTROLFILE statements.
func TestParseDatabaseStmts(t *testing.T) {
	tests := []string{
		// ---- CREATE DATABASE ----
		// Minimal
		`CREATE DATABASE`,
		// Named database
		`CREATE DATABASE mydb`,
		// With SYS/SYSTEM passwords
		`CREATE DATABASE mydb
			USER SYS IDENTIFIED BY syspass
			USER SYSTEM IDENTIFIED BY systempass`,
		// Character sets
		`CREATE DATABASE mydb
			CHARACTER SET AL32UTF8
			NATIONAL CHARACTER SET AL16UTF16`,
		// With CONTROLFILE REUSE
		`CREATE DATABASE mydb CONTROLFILE REUSE`,
		// With LOGFILE groups
		`CREATE DATABASE mydb
			LOGFILE GROUP 1 '/u01/logs/redo01.log' SIZE 100M,
			        GROUP 2 '/u01/logs/redo02.log' SIZE 100M`,
		// With MAX* parameters
		`CREATE DATABASE mydb
			MAXLOGFILES 16
			MAXLOGMEMBERS 3
			MAXLOGHISTORY 100
			MAXDATAFILES 1024
			MAXINSTANCES 8`,
		// With ARCHIVELOG/NOARCHIVELOG
		`CREATE DATABASE mydb ARCHIVELOG`,
		`CREATE DATABASE mydb NOARCHIVELOG`,
		// FORCE LOGGING
		`CREATE DATABASE mydb FORCE LOGGING`,
		// SET STANDBY NOLOGGING
		`CREATE DATABASE mydb SET STANDBY NOLOGGING FOR DATA AVAILABILITY`,
		`CREATE DATABASE mydb SET STANDBY NOLOGGING FOR LOAD PERFORMANCE`,
		// SET DEFAULT BIGFILE/SMALLFILE TABLESPACE
		`CREATE DATABASE mydb SET DEFAULT BIGFILE TABLESPACE`,
		`CREATE DATABASE mydb SET DEFAULT SMALLFILE TABLESPACE`,
		// Default tablespace
		`CREATE DATABASE mydb
			DEFAULT TABLESPACE users
			DATAFILE '/u01/data/users01.dbf' SIZE 500M AUTOEXTEND ON`,
		// Default temporary tablespace
		`CREATE DATABASE mydb
			DEFAULT TEMPORARY TABLESPACE temp
			TEMPFILE '/u01/data/temp01.dbf' SIZE 200M`,
		// Undo tablespace
		`CREATE DATABASE mydb
			UNDO TABLESPACE undots
			DATAFILE '/u01/data/undo01.dbf' SIZE 200M`,
		// Extent management
		`CREATE DATABASE mydb
			EXTENT MANAGEMENT LOCAL AUTOALLOCATE
			DATAFILE '/u01/data/system01.dbf' SIZE 500M`,
		// SYSAUX DATAFILE
		`CREATE DATABASE mydb
			SYSAUX DATAFILE '/u01/data/sysaux01.dbf' SIZE 500M`,
		// ENABLE PLUGGABLE DATABASE
		`CREATE DATABASE mydb ENABLE PLUGGABLE DATABASE`,
		// ENABLE PLUGGABLE DATABASE with SEED
		`CREATE DATABASE mydb
			ENABLE PLUGGABLE DATABASE
			SEED FILE_NAME_CONVERT = ('/u01/data/', '/u01/seed/')`,
		// SET TIME_ZONE
		`CREATE DATABASE mydb SET TIME_ZONE = '+00:00'`,
		// USING MIRROR COPY
		`CREATE DATABASE mydb USING MIRROR COPY mirror1`,
		// Comprehensive CREATE DATABASE
		`CREATE DATABASE proddb
			USER SYS IDENTIFIED BY sys123
			USER SYSTEM IDENTIFIED BY system123
			CONTROLFILE REUSE
			LOGFILE GROUP 1 '/u01/logs/redo01.log' SIZE 200M
			MAXLOGFILES 16
			MAXDATAFILES 1024
			MAXINSTANCES 8
			CHARACTER SET AL32UTF8
			NATIONAL CHARACTER SET AL16UTF16
			ARCHIVELOG
			FORCE LOGGING
			SET DEFAULT BIGFILE TABLESPACE
			DEFAULT TABLESPACE users DATAFILE '/u01/data/users01.dbf' SIZE 1G
			DEFAULT TEMPORARY TABLESPACE temp TEMPFILE '/u01/data/temp01.dbf' SIZE 500M
			UNDO TABLESPACE undots DATAFILE '/u01/data/undo01.dbf' SIZE 500M
			SET TIME_ZONE = 'US/Eastern'
			ENABLE PLUGGABLE DATABASE`,

		// ---- ALTER DATABASE ----
		// MOUNT
		`ALTER DATABASE MOUNT`,
		`ALTER DATABASE MOUNT STANDBY DATABASE`,
		`ALTER DATABASE MOUNT CLONE DATABASE`,
		// OPEN
		`ALTER DATABASE OPEN`,
		`ALTER DATABASE OPEN READ WRITE`,
		`ALTER DATABASE OPEN READ ONLY`,
		`ALTER DATABASE OPEN READ WRITE RESETLOGS`,
		`ALTER DATABASE OPEN NORESETLOGS`,
		`ALTER DATABASE OPEN UPGRADE`,
		`ALTER DATABASE OPEN READ WRITE RESETLOGS UPGRADE`,
		// Named database
		`ALTER DATABASE mydb OPEN READ WRITE`,
		// Recovery clauses
		`ALTER DATABASE BEGIN BACKUP`,
		`ALTER DATABASE END BACKUP`,
		`ALTER DATABASE RECOVER DATABASE`,
		`ALTER DATABASE RECOVER AUTOMATIC DATABASE`,
		`ALTER DATABASE RECOVER STANDBY DATABASE UNTIL CANCEL`,
		`ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION`,
		`ALTER DATABASE RECOVER MANAGED STANDBY DATABASE CANCEL IMMEDIATE`,
		`ALTER DATABASE RECOVER MANAGED STANDBY DATABASE FINISH`,
		`ALTER DATABASE RECOVER TABLESPACE users`,
		`ALTER DATABASE RECOVER DATAFILE '/u01/data/users01.dbf'`,
		// Database file clauses
		`ALTER DATABASE RENAME FILE '/old/path.dbf' TO '/new/path.dbf'`,
		`ALTER DATABASE CREATE DATAFILE '/u01/data/file1.dbf' AS NEW`,
		`ALTER DATABASE DATAFILE '/u01/data/file1.dbf' ONLINE`,
		`ALTER DATABASE DATAFILE '/u01/data/file1.dbf' OFFLINE`,
		`ALTER DATABASE DATAFILE '/u01/data/file1.dbf' OFFLINE FOR DROP`,
		`ALTER DATABASE DATAFILE '/u01/data/file1.dbf' RESIZE 500M`,
		`ALTER DATABASE DATAFILE '/u01/data/file1.dbf' AUTOEXTEND ON NEXT 100M MAXSIZE 2G`,
		`ALTER DATABASE DATAFILE '/u01/data/file1.dbf' AUTOEXTEND OFF`,
		`ALTER DATABASE DATAFILE '/u01/data/file1.dbf' END BACKUP`,
		`ALTER DATABASE TEMPFILE '/u01/data/temp1.dbf' RESIZE 1G`,
		`ALTER DATABASE TEMPFILE '/u01/data/temp1.dbf' DROP INCLUDING DATAFILES`,
		`ALTER DATABASE MOVE DATAFILE '/old/path.dbf' TO '/new/path.dbf'`,
		// Logfile clauses
		`ALTER DATABASE ARCHIVELOG`,
		`ALTER DATABASE NOARCHIVELOG`,
		`ALTER DATABASE FORCE LOGGING`,
		`ALTER DATABASE NO FORCE LOGGING`,
		`ALTER DATABASE ADD LOGFILE GROUP 3 '/u01/logs/redo03.log' SIZE 200M`,
		`ALTER DATABASE ADD LOGFILE MEMBER '/u01/logs/redo01b.log' TO GROUP 1`,
		`ALTER DATABASE DROP LOGFILE GROUP 3`,
		`ALTER DATABASE DROP LOGFILE MEMBER '/u01/logs/redo01b.log'`,
		`ALTER DATABASE CLEAR LOGFILE GROUP 2`,
		// Controlfile clauses
		`ALTER DATABASE BACKUP CONTROLFILE TO '/u01/backup/control.bak'`,
		`ALTER DATABASE BACKUP CONTROLFILE TO TRACE`,
		`ALTER DATABASE BACKUP CONTROLFILE TO TRACE AS '/u01/trace/control.sql'`,
		`ALTER DATABASE CREATE STANDBY CONTROLFILE AS '/u01/standby/control01.ctl'`,
		`ALTER DATABASE CREATE PHYSICAL STANDBY CONTROLFILE AS '/u01/standby/control01.ctl'`,
		`ALTER DATABASE CREATE LOGICAL STANDBY CONTROLFILE AS '/u01/standby/control01.ctl' REUSE`,
		// Standby clauses
		`ALTER DATABASE ACTIVATE STANDBY DATABASE`,
		`ALTER DATABASE ACTIVATE PHYSICAL STANDBY DATABASE`,
		`ALTER DATABASE ACTIVATE PHYSICAL STANDBY DATABASE FINISH APPLY`,
		`ALTER DATABASE SET STANDBY DATABASE TO MAXIMIZE PROTECTION`,
		`ALTER DATABASE SET STANDBY DATABASE TO MAXIMIZE AVAILABILITY`,
		`ALTER DATABASE SET STANDBY DATABASE TO MAXIMIZE PERFORMANCE`,
		`ALTER DATABASE COMMIT TO SWITCHOVER TO PHYSICAL STANDBY`,
		`ALTER DATABASE COMMIT TO SWITCHOVER TO PRIMARY DATABASE`,
		`ALTER DATABASE START LOGICAL STANDBY APPLY IMMEDIATE`,
		`ALTER DATABASE STOP LOGICAL STANDBY APPLY`,
		`ALTER DATABASE CONVERT TO PHYSICAL STANDBY`,
		`ALTER DATABASE CONVERT TO SNAPSHOT STANDBY`,
		// Default settings
		`ALTER DATABASE DEFAULT TABLESPACE users`,
		`ALTER DATABASE DEFAULT TEMPORARY TABLESPACE temp`,
		`ALTER DATABASE SET DEFAULT BIGFILE TABLESPACE`,
		`ALTER DATABASE SET DEFAULT SMALLFILE TABLESPACE`,
		`ALTER DATABASE FLASHBACK ON`,
		`ALTER DATABASE FLASHBACK OFF`,
		`ALTER DATABASE SET TIME_ZONE = '+05:30'`,
		// Instance clauses
		`ALTER DATABASE ENABLE RESTRICTED SESSION`,
		`ALTER DATABASE DISABLE RESTRICTED SESSION`,
		// Block change tracking
		`ALTER DATABASE ENABLE BLOCK CHANGE TRACKING`,
		`ALTER DATABASE ENABLE BLOCK CHANGE TRACKING USING FILE '/u01/bct/bct.chg'`,
		`ALTER DATABASE DISABLE BLOCK CHANGE TRACKING`,
		// RENAME GLOBAL_NAME
		`ALTER DATABASE RENAME GLOBAL_NAME TO newdb`,
		// Security clauses
		`ALTER DATABASE ENABLE LOST WRITE PROTECTION`,
		`ALTER DATABASE DISABLE LOST WRITE PROTECTION`,
		// Supplemental logging
		`ALTER DATABASE ADD SUPPLEMENTAL LOG DATA`,
		`ALTER DATABASE DROP SUPPLEMENTAL LOG DATA`,
		// CDB fleet
		`ALTER DATABASE SET LEAD_CDB = NONE`,
		// Replay upgrade
		`ALTER DATABASE SET STANDBY NOLOGGING FOR DATA AVAILABILITY`,
		`ALTER DATABASE SET STANDBY NOLOGGING FOR LOAD PERFORMANCE`,

		// ---- CREATE CONTROLFILE ----
		`CREATE CONTROLFILE REUSE DATABASE mydb RESETLOGS`,
		`CREATE CONTROLFILE SET DATABASE mydb NORESETLOGS
			LOGFILE GROUP 1 '/u01/logs/redo01.log' SIZE 100M
			DATAFILE '/u01/data/system01.dbf'`,

		// ---- CREATE PLUGGABLE DATABASE ----
		// Minimal from seed
		`CREATE PLUGGABLE DATABASE pdb1
			ADMIN USER pdbadmin IDENTIFIED BY password1`,
		// From seed with options
		`CREATE PLUGGABLE DATABASE pdb1
			ADMIN USER pdbadmin IDENTIFIED BY password1
			ROLES = (dba, resource)
			DEFAULT TABLESPACE users
			FILE_NAME_CONVERT = ('/u01/cdb/', '/u01/pdb1/')
			STORAGE (MAXSIZE 10G)
			PATH_PREFIX = '/u01/pdb1/'`,
		// Clone from another PDB
		`CREATE PLUGGABLE DATABASE pdb2
			FROM pdb1
			FILE_NAME_CONVERT = ('/u01/pdb1/', '/u01/pdb2/')`,
		// Clone from remote PDB
		`CREATE PLUGGABLE DATABASE pdb2
			FROM pdb1@remote_db
			FILE_NAME_CONVERT = NONE`,
		// AS PROXY
		`CREATE PLUGGABLE DATABASE pdb3
			AS PROXY FROM pdb1@remote_db`,
		// From XML metadata
		`CREATE PLUGGABLE DATABASE pdb4
			USING '/u01/export/pdb1.xml'
			COPY
			FILE_NAME_CONVERT = ('/u01/export/', '/u01/pdb4/')`,
		// AS APPLICATION CONTAINER
		`CREATE PLUGGABLE DATABASE approot
			AS APPLICATION CONTAINER
			ADMIN USER appadmin IDENTIFIED BY appass`,
		// AS SEED
		`CREATE PLUGGABLE DATABASE pdbseed
			AS SEED
			ADMIN USER seedadmin IDENTIFIED BY seedpass`,
		// With LOGGING/NOLOGGING
		`CREATE PLUGGABLE DATABASE pdb5
			ADMIN USER admin1 IDENTIFIED BY pass1
			LOGGING`,
		`CREATE PLUGGABLE DATABASE pdb6
			ADMIN USER admin2 IDENTIFIED BY pass2
			NOLOGGING`,
		// SNAPSHOT COPY
		`CREATE PLUGGABLE DATABASE pdb7
			FROM pdb1 SNAPSHOT COPY`,
		// NO DATA
		`CREATE PLUGGABLE DATABASE pdb8
			FROM pdb1 NO DATA`,
		// TEMPFILE REUSE
		`CREATE PLUGGABLE DATABASE pdb9
			ADMIN USER admin3 IDENTIFIED BY pass3
			TEMPFILE REUSE`,
		// USER_TABLESPACES
		`CREATE PLUGGABLE DATABASE pdb10
			FROM pdb1
			USER_TABLESPACES = ALL`,
		`CREATE PLUGGABLE DATABASE pdb11
			FROM pdb1
			USER_TABLESPACES = NONE`,
		`CREATE PLUGGABLE DATABASE pdb12
			FROM pdb1
			USER_TABLESPACES = ALL EXCEPT (system, sysaux)`,
		// STANDBYS
		`CREATE PLUGGABLE DATABASE pdb13
			ADMIN USER admin4 IDENTIFIED BY pass4
			STANDBYS = ALL`,
		`CREATE PLUGGABLE DATABASE pdb14
			ADMIN USER admin5 IDENTIFIED BY pass5
			STANDBYS = NONE`,
		// CREATE_FILE_DEST
		`CREATE PLUGGABLE DATABASE pdb15
			ADMIN USER admin6 IDENTIFIED BY pass6
			CREATE_FILE_DEST = '/u01/pdb15/'`,
		// STORAGE UNLIMITED
		`CREATE PLUGGABLE DATABASE pdb16
			ADMIN USER admin7 IDENTIFIED BY pass7
			STORAGE UNLIMITED`,
		// PARALLEL
		`CREATE PLUGGABLE DATABASE pdb17
			FROM pdb1
			PARALLEL 4`,
		// SERVICE_NAME_CONVERT
		`CREATE PLUGGABLE DATABASE pdb18
			FROM pdb1
			SERVICE_NAME_CONVERT = ('svc1', 'svc2')`,
		// RELOCATE
		`CREATE PLUGGABLE DATABASE pdb19
			FROM pdb1
			RELOCATE`,
		// REFRESH MODE
		`CREATE PLUGGABLE DATABASE pdb20
			FROM pdb1
			REFRESH MODE MANUAL`,
		`CREATE PLUGGABLE DATABASE pdb21
			FROM pdb1
			REFRESH MODE EVERY 60 MINUTES`,
		// Comprehensive CREATE PDB
		`CREATE PLUGGABLE DATABASE prodpdb
			FROM pdb_template@remote_cdb
			PARALLEL 4
			DEFAULT TABLESPACE users
			FILE_NAME_CONVERT = ('/u01/template/', '/u01/prodpdb/')
			SERVICE_NAME_CONVERT = ('tmpl_svc', 'prod_svc')
			STORAGE (MAXSIZE 50G MAX_AUDIT_SIZE 1G MAX_DIAG_SIZE 2G)
			PATH_PREFIX = '/u01/prodpdb/'
			TEMPFILE REUSE
			USER_TABLESPACES = ALL
			STANDBYS = ALL
			LOGGING
			CREATE_FILE_DEST = '/u01/prodpdb/'`,

		// ---- ALTER PLUGGABLE DATABASE ----
		// OPEN/CLOSE
		`ALTER PLUGGABLE DATABASE pdb1 OPEN`,
		`ALTER PLUGGABLE DATABASE pdb1 OPEN READ WRITE`,
		`ALTER PLUGGABLE DATABASE pdb1 OPEN READ ONLY`,
		`ALTER PLUGGABLE DATABASE pdb1 OPEN RESTRICTED`,
		`ALTER PLUGGABLE DATABASE pdb1 OPEN FORCE`,
		`ALTER PLUGGABLE DATABASE pdb1 CLOSE`,
		`ALTER PLUGGABLE DATABASE pdb1 CLOSE IMMEDIATE`,
		`ALTER PLUGGABLE DATABASE pdb1 CLOSE ABORT`,
		// All PDBs
		`ALTER PLUGGABLE DATABASE ALL OPEN`,
		`ALTER PLUGGABLE DATABASE ALL CLOSE IMMEDIATE`,
		`ALTER PLUGGABLE DATABASE ALL EXCEPT (pdb1, pdb2) OPEN`,
		// SAVE/DISCARD STATE
		`ALTER PLUGGABLE DATABASE pdb1 SAVE STATE`,
		`ALTER PLUGGABLE DATABASE pdb1 DISCARD STATE`,
		// UNPLUG
		`ALTER PLUGGABLE DATABASE pdb1 UNPLUG INTO '/u01/export/pdb1.xml'`,
		// Settings
		`ALTER PLUGGABLE DATABASE pdb1 DEFAULT TABLESPACE users`,
		`ALTER PLUGGABLE DATABASE pdb1 DEFAULT TEMPORARY TABLESPACE temp`,
		`ALTER PLUGGABLE DATABASE DEFAULT EDITION ed1`,
		`ALTER PLUGGABLE DATABASE SET DEFAULT TABLESPACE BIGFILE`,
		// STORAGE
		`ALTER PLUGGABLE DATABASE pdb1 STORAGE (MAXSIZE 20G)`,
		`ALTER PLUGGABLE DATABASE pdb1 STORAGE (MAXSIZE UNLIMITED)`,
		// Logging
		`ALTER PLUGGABLE DATABASE pdb1 LOGGING`,
		`ALTER PLUGGABLE DATABASE pdb1 NOLOGGING`,
		`ALTER PLUGGABLE DATABASE ENABLE FORCE LOGGING`,
		`ALTER PLUGGABLE DATABASE DISABLE FORCE LOGGING`,
		// RECOVER
		`ALTER PLUGGABLE DATABASE pdb1 RECOVER`,
		// RENAME
		`ALTER PLUGGABLE DATABASE pdb1 RENAME GLOBAL_NAME TO newpdb`,
		// APPLICATION clauses
		`ALTER PLUGGABLE DATABASE APPLICATION myapp BEGIN INSTALL VERSION '1.0'`,
		`ALTER PLUGGABLE DATABASE APPLICATION myapp END INSTALL`,
		`ALTER PLUGGABLE DATABASE APPLICATION myapp BEGIN PATCH 1`,
		`ALTER PLUGGABLE DATABASE APPLICATION myapp END PATCH`,
		`ALTER PLUGGABLE DATABASE APPLICATION myapp BEGIN UPGRADE FROM '1.0' TO '2.0'`,
		`ALTER PLUGGABLE DATABASE APPLICATION myapp END UPGRADE`,
		`ALTER PLUGGABLE DATABASE APPLICATION myapp SET COMPATIBILITY VERSION '2.0'`,
		`ALTER PLUGGABLE DATABASE APPLICATION myapp SYNC`,
		// SNAPSHOT clauses
		`ALTER PLUGGABLE DATABASE SNAPSHOT MANUAL`,
		`ALTER PLUGGABLE DATABASE SNAPSHOT NONE`,
		`ALTER PLUGGABLE DATABASE CREATE SNAPSHOT snap1`,
		`ALTER PLUGGABLE DATABASE DROP SNAPSHOT snap1`,
		`ALTER PLUGGABLE DATABASE SET MAX_PDB_SNAPSHOTS = 10`,
		// REFRESH
		`ALTER PLUGGABLE DATABASE pdb1 REFRESH MODE NONE`,
		`ALTER PLUGGABLE DATABASE pdb1 REFRESH MODE MANUAL`,
		`ALTER PLUGGABLE DATABASE pdb1 REFRESH MODE EVERY 30 MINUTES`,
		// CONTAINERS
		`ALTER PLUGGABLE DATABASE CONTAINERS DEFAULT TARGET pdb1`,
		`ALTER PLUGGABLE DATABASE CONTAINERS DEFAULT TARGET NONE`,
		// PRIORITY
		`ALTER PLUGGABLE DATABASE pdb1 PRIORITY 5`,
		// BACKUP
		`ALTER PLUGGABLE DATABASE BACKUP BEGIN`,
		`ALTER PLUGGABLE DATABASE BACKUP END`,
		`ALTER PLUGGABLE DATABASE ENABLE RECOVERY`,
		`ALTER PLUGGABLE DATABASE DISABLE RECOVERY`,
		// SET TIME_ZONE
		`ALTER PLUGGABLE DATABASE SET TIME_ZONE = '+08:00'`,
		// ENABLE/DISABLE LOST WRITE PROTECTION
		`ALTER PLUGGABLE DATABASE ENABLE LOST WRITE PROTECTION`,
		`ALTER PLUGGABLE DATABASE DISABLE LOST WRITE PROTECTION`,
		// MATERIALIZE
		`ALTER PLUGGABLE DATABASE MATERIALIZE`,
		// ENABLE/DISABLE BACKUP
		`ALTER PLUGGABLE DATABASE ENABLE BACKUP`,
		`ALTER PLUGGABLE DATABASE DISABLE BACKUP`,

		// ---- DROP PLUGGABLE DATABASE ----
		`DROP PLUGGABLE DATABASE pdb1`,
		`DROP PLUGGABLE DATABASE pdb1 INCLUDING DATAFILES`,
		`DROP PLUGGABLE DATABASE pdb1 KEEP DATAFILES`,

		// ---- CREATE DISKGROUP ----
		// Minimal
		`CREATE DISKGROUP dg1
			DISK '/dev/sda1'`,
		// With redundancy
		`CREATE DISKGROUP dg1
			NORMAL REDUNDANCY
			DISK '/dev/sda1'`,
		`CREATE DISKGROUP dg1
			HIGH REDUNDANCY
			DISK '/dev/sda1'`,
		`CREATE DISKGROUP dg1
			EXTERNAL REDUNDANCY
			DISK '/dev/sda1'`,
		`CREATE DISKGROUP dg1
			FLEX REDUNDANCY
			DISK '/dev/sda1'`,
		`CREATE DISKGROUP dg1
			EXTENDED REDUNDANCY
			DISK '/dev/sda1'`,
		// With failgroups
		`CREATE DISKGROUP dg1
			NORMAL REDUNDANCY
			FAILGROUP fg1 DISK '/dev/sda1' NAME disk1 SIZE 100G,
			                                '/dev/sda2' NAME disk2
			FAILGROUP fg2 DISK '/dev/sdb1' NAME disk3,
			                                '/dev/sdb2' NAME disk4`,
		// QUORUM/REGULAR failgroups
		`CREATE DISKGROUP dg1
			NORMAL REDUNDANCY
			QUORUM FAILGROUP fg_q DISK '/dev/sdc1'
			REGULAR FAILGROUP fg_r DISK '/dev/sdd1'`,
		// With ATTRIBUTE
		`CREATE DISKGROUP dg1
			EXTERNAL REDUNDANCY
			DISK '/dev/sda1'
			ATTRIBUTE 'compatible.asm' = '19.0'`,
		// With FORCE/NOFORCE
		`CREATE DISKGROUP dg1
			EXTERNAL REDUNDANCY
			DISK '/dev/sda1' FORCE`,
		// Comprehensive
		`CREATE DISKGROUP datadg
			NORMAL REDUNDANCY
			FAILGROUP fg1 DISK '/dev/sda1' NAME d1 SIZE 500G, '/dev/sda2' NAME d2 SIZE 500G
			FAILGROUP fg2 DISK '/dev/sdb1' NAME d3 SIZE 500G, '/dev/sdb2' NAME d4 SIZE 500G
			ATTRIBUTE 'compatible.asm' = '19.0', 'au_size' = '4M'`,

		// ---- ALTER DISKGROUP ----
		// ADD DISK
		`ALTER DISKGROUP dg1 ADD DISK '/dev/sdc1'`,
		`ALTER DISKGROUP dg1 ADD DISK '/dev/sdc1' NAME disk5 SIZE 200G FAILGROUP fg1`,
		// DROP DISK
		`ALTER DISKGROUP dg1 DROP DISK disk1`,
		`ALTER DISKGROUP dg1 DROP DISK disk1, disk2 FORCE`,
		`ALTER DISKGROUP dg1 DROP DISKS IN FAILGROUP fg1`,
		// RESIZE
		`ALTER DISKGROUP dg1 RESIZE ALL 500G`,
		// REPLACE DISK
		`ALTER DISKGROUP dg1 REPLACE DISK disk1 WITH '/dev/sde1'`,
		`ALTER DISKGROUP dg1 REPLACE DISK disk1 WITH '/dev/sde1' FORCE POWER 5 WAIT`,
		// RENAME DISK
		`ALTER DISKGROUP dg1 RENAME DISK old_disk TO new_disk`,
		`ALTER DISKGROUP dg1 RENAME DISKS ALL`,
		// ONLINE/OFFLINE DISK
		`ALTER DISKGROUP dg1 ONLINE DISK disk1, disk2`,
		`ALTER DISKGROUP dg1 ONLINE ALL`,
		`ALTER DISKGROUP dg1 ONLINE DISKS IN FAILGROUP fg1`,
		`ALTER DISKGROUP dg1 OFFLINE DISK disk1`,
		`ALTER DISKGROUP dg1 OFFLINE DISKS IN FAILGROUP fg1`,
		// REBALANCE
		`ALTER DISKGROUP dg1 REBALANCE POWER 5`,
		`ALTER DISKGROUP dg1 REBALANCE POWER 5 WAIT`,
		// CHECK
		`ALTER DISKGROUP dg1 CHECK`,
		`ALTER DISKGROUP dg1 CHECK REPAIR`,
		`ALTER DISKGROUP dg1 CHECK NOREPAIR`,
		// TEMPLATE
		`ALTER DISKGROUP dg1 ADD TEMPLATE tmpl1 ATTRIBUTES (MIRROR FINE)`,
		`ALTER DISKGROUP dg1 DROP TEMPLATE tmpl1`,
		// DIRECTORY
		`ALTER DISKGROUP dg1 ADD DIRECTORY '+dg1/mydir'`,
		`ALTER DISKGROUP dg1 DROP DIRECTORY '+dg1/mydir'`,
		// ALIAS
		`ALTER DISKGROUP dg1 ADD ALIAS '+dg1/myalias' FOR '+dg1.001.001'`,
		`ALTER DISKGROUP dg1 DROP ALIAS '+dg1/myalias'`,
		// VOLUME
		`ALTER DISKGROUP dg1 ADD VOLUME vol1 SIZE 100G`,
		`ALTER DISKGROUP dg1 RESIZE VOLUME vol1 200G`,
		`ALTER DISKGROUP dg1 DROP VOLUME vol1`,
		// SET ATTRIBUTE
		`ALTER DISKGROUP dg1 SET ATTRIBUTE 'compatible.asm' = '19.0'`,
		// MOUNT/DISMOUNT
		`ALTER DISKGROUP dg1 MOUNT`,
		`ALTER DISKGROUP dg1 MOUNT RESTRICTED`,
		`ALTER DISKGROUP dg1 DISMOUNT`,
		`ALTER DISKGROUP dg1 DISMOUNT FORCE`,
		// UNDROP DISKS
		`ALTER DISKGROUP dg1 UNDROP DISKS`,
		// CONVERT REDUNDANCY
		`ALTER DISKGROUP dg1 CONVERT REDUNDANCY`,
		// USERGROUP
		`ALTER DISKGROUP dg1 ADD USERGROUP ug1`,
		`ALTER DISKGROUP dg1 DROP USERGROUP ug1`,
		// USER
		`ALTER DISKGROUP dg1 ADD USER user1`,
		`ALTER DISKGROUP dg1 DROP USER user1`,
		// SCRUB
		`ALTER DISKGROUP dg1 SCRUB`,
		`ALTER DISKGROUP dg1 SCRUB REPAIR`,
		`ALTER DISKGROUP dg1 SCRUB POWER AUTO`,
		// QUOTAGROUP
		`ALTER DISKGROUP dg1 ADD QUOTAGROUP qg1 SET QUOTA = 100G`,
		`ALTER DISKGROUP dg1 MODIFY QUOTAGROUP qg1 SET QUOTA = UNLIMITED`,
		`ALTER DISKGROUP dg1 DROP QUOTAGROUP qg1`,
		// FILEGROUP
		`ALTER DISKGROUP dg1 ADD FILEGROUP fg1`,
		`ALTER DISKGROUP dg1 DROP FILEGROUP fg1`,
		// ENABLE/DISABLE VOLUME
		`ALTER DISKGROUP dg1 ENABLE VOLUME ALL`,
		`ALTER DISKGROUP dg1 DISABLE VOLUME vol1`,
		// MODIFY POWER
		`ALTER DISKGROUP dg1 MODIFY POWER 3`,

		// ---- DROP DISKGROUP ----
		`DROP DISKGROUP dg1`,
		`DROP DISKGROUP dg1 INCLUDING CONTENTS`,
		`DROP DISKGROUP dg1 EXCLUDING CONTENTS`,
		`DROP DISKGROUP dg1 FORCE INCLUDING CONTENTS`,
	}
	for _, sql := range tests {
		name := sql
		if len(name) > 60 {
			name = name[:60]
		}
		t.Run(name, func(t *testing.T) {
			result := ParseAndCheck(t, sql)
			if result.Len() < 1 {
				t.Fatalf("expected at least 1 statement, got %d", result.Len())
			}
		})
	}
}
