package parser

import (
	"testing"
)

// TestParseSecurityStmts tests parsing of CREATE/ALTER USER, CREATE/ALTER ROLE,
// CREATE/ALTER PROFILE, and related security statements.
func TestParseSecurityStmts(t *testing.T) {
	tests := []string{
		// ---- CREATE USER ----
		// Basic
		`CREATE USER scott IDENTIFIED BY tiger`,
		// IF NOT EXISTS
		`CREATE USER IF NOT EXISTS scott IDENTIFIED BY tiger`,
		// IDENTIFIED EXTERNALLY
		`CREATE USER extuser IDENTIFIED EXTERNALLY`,
		`CREATE USER extuser IDENTIFIED EXTERNALLY AS 'CN=scott,OU=Users,DC=example,DC=com'`,
		// IDENTIFIED GLOBALLY
		`CREATE USER globaluser IDENTIFIED GLOBALLY`,
		`CREATE USER globaluser IDENTIFIED GLOBALLY AS 'CN=scott,OU=Users,DC=example,DC=com'`,
		// NO AUTHENTICATION
		`CREATE USER schema_only NO AUTHENTICATION`,
		// DEFAULT TABLESPACE
		`CREATE USER scott IDENTIFIED BY tiger DEFAULT TABLESPACE users`,
		// TEMPORARY TABLESPACE
		`CREATE USER scott IDENTIFIED BY tiger TEMPORARY TABLESPACE temp`,
		// LOCAL TEMPORARY TABLESPACE
		`CREATE USER scott IDENTIFIED BY tiger LOCAL TEMPORARY TABLESPACE ltemp`,
		// QUOTA
		`CREATE USER scott IDENTIFIED BY tiger QUOTA 100M ON users`,
		`CREATE USER scott IDENTIFIED BY tiger QUOTA UNLIMITED ON users`,
		// PROFILE
		`CREATE USER scott IDENTIFIED BY tiger PROFILE app_user`,
		// PASSWORD EXPIRE
		`CREATE USER scott IDENTIFIED BY tiger PASSWORD EXPIRE`,
		// ACCOUNT LOCK/UNLOCK
		`CREATE USER scott IDENTIFIED BY tiger ACCOUNT LOCK`,
		`CREATE USER scott IDENTIFIED BY tiger ACCOUNT UNLOCK`,
		// ENABLE EDITIONS
		`CREATE USER scott IDENTIFIED BY tiger ENABLE EDITIONS`,
		// CONTAINER
		`CREATE USER c##common IDENTIFIED BY tiger CONTAINER = ALL`,
		`CREATE USER localuser IDENTIFIED BY tiger CONTAINER = CURRENT`,
		// DEFAULT COLLATION
		`CREATE USER scott IDENTIFIED BY tiger DEFAULT COLLATION USING_NLS_COMP`,
		// Comprehensive CREATE USER
		`CREATE USER scott
			IDENTIFIED BY tiger
			DEFAULT TABLESPACE users
			TEMPORARY TABLESPACE temp
			QUOTA 500M ON users
			QUOTA UNLIMITED ON temp
			PROFILE app_profile
			PASSWORD EXPIRE
			ACCOUNT UNLOCK
			ENABLE EDITIONS
			DEFAULT COLLATION USING_NLS_COMP
			CONTAINER = ALL`,

		// ---- ALTER USER ----
		// Change password
		`ALTER USER scott IDENTIFIED BY lion`,
		// Change password with REPLACE
		`ALTER USER scott IDENTIFIED BY lion REPLACE tiger`,
		// IF EXISTS
		`ALTER USER IF EXISTS scott IDENTIFIED BY lion`,
		// IDENTIFIED EXTERNALLY
		`ALTER USER scott IDENTIFIED EXTERNALLY`,
		`ALTER USER scott IDENTIFIED EXTERNALLY AS 'kerberos_principal'`,
		// IDENTIFIED GLOBALLY
		`ALTER USER scott IDENTIFIED GLOBALLY AS 'cn=scott'`,
		// NO AUTHENTICATION
		`ALTER USER scott NO AUTHENTICATION`,
		// DEFAULT TABLESPACE
		`ALTER USER scott DEFAULT TABLESPACE users2`,
		// TEMPORARY TABLESPACE
		`ALTER USER scott TEMPORARY TABLESPACE temp2`,
		// LOCAL TEMPORARY TABLESPACE
		`ALTER USER scott LOCAL TEMPORARY TABLESPACE ltemp2`,
		// QUOTA
		`ALTER USER scott QUOTA 200M ON users`,
		`ALTER USER scott QUOTA UNLIMITED ON users`,
		// PROFILE
		`ALTER USER scott PROFILE new_profile`,
		// DEFAULT ROLE
		`ALTER USER scott DEFAULT ROLE dba, resource`,
		`ALTER USER scott DEFAULT ROLE ALL`,
		`ALTER USER scott DEFAULT ROLE ALL EXCEPT dba`,
		`ALTER USER scott DEFAULT ROLE NONE`,
		// PASSWORD EXPIRE
		`ALTER USER scott PASSWORD EXPIRE`,
		// ACCOUNT LOCK/UNLOCK
		`ALTER USER scott ACCOUNT LOCK`,
		`ALTER USER scott ACCOUNT UNLOCK`,
		// ENABLE EDITIONS
		`ALTER USER scott ENABLE EDITIONS`,
		// CONTAINER
		`ALTER USER c##common CONTAINER = ALL`,
		`ALTER USER localuser CONTAINER = CURRENT`,
		// GRANT CONNECT THROUGH proxy
		`ALTER USER scott GRANT CONNECT THROUGH proxy_user`,
		`ALTER USER scott GRANT CONNECT THROUGH ENTERPRISE USERS`,
		// REVOKE CONNECT THROUGH proxy
		`ALTER USER scott REVOKE CONNECT THROUGH proxy_user`,
		`ALTER USER scott REVOKE CONNECT THROUGH ENTERPRISE USERS`,
		// Comprehensive ALTER USER
		`ALTER USER scott
			IDENTIFIED BY newpass REPLACE oldpass
			DEFAULT TABLESPACE users2
			TEMPORARY TABLESPACE temp2
			QUOTA 1G ON users2
			PROFILE secure_profile
			PASSWORD EXPIRE
			ACCOUNT UNLOCK
			CONTAINER = ALL`,

		// ---- CREATE ROLE ----
		// Basic (no auth)
		`CREATE ROLE app_role`,
		// NOT IDENTIFIED
		`CREATE ROLE app_role NOT IDENTIFIED`,
		// IDENTIFIED BY password
		`CREATE ROLE secure_role IDENTIFIED BY secret`,
		// IDENTIFIED USING package
		`CREATE ROLE dynamic_role IDENTIFIED USING sec_pkg`,
		`CREATE ROLE dynamic_role IDENTIFIED USING myschema.sec_pkg`,
		// IDENTIFIED EXTERNALLY
		`CREATE ROLE ext_role IDENTIFIED EXTERNALLY`,
		// IDENTIFIED GLOBALLY
		`CREATE ROLE global_role IDENTIFIED GLOBALLY`,
		`CREATE ROLE global_role IDENTIFIED GLOBALLY AS 'cn=app_role,ou=roles'`,
		// CONTAINER
		`CREATE ROLE c##common_role CONTAINER = ALL`,
		`CREATE ROLE local_role CONTAINER = CURRENT`,
		// Comprehensive
		`CREATE ROLE c##secure_role
			IDENTIFIED BY secret
			CONTAINER = ALL`,

		// ---- ALTER ROLE ----
		// NOT IDENTIFIED
		`ALTER ROLE app_role NOT IDENTIFIED`,
		// IDENTIFIED BY password
		`ALTER ROLE app_role IDENTIFIED BY newsecret`,
		// IDENTIFIED EXTERNALLY
		`ALTER ROLE app_role IDENTIFIED EXTERNALLY`,
		// IDENTIFIED GLOBALLY
		`ALTER ROLE app_role IDENTIFIED GLOBALLY AS 'cn=new_role'`,
		// IDENTIFIED USING
		`ALTER ROLE app_role IDENTIFIED USING myschema.auth_pkg`,
		// CONTAINER
		`ALTER ROLE c##role IDENTIFIED BY pass CONTAINER = ALL`,

		// ---- CREATE PROFILE ----
		// Resource parameters
		`CREATE PROFILE app_profile LIMIT
			SESSIONS_PER_USER 10
			CPU_PER_SESSION 10000
			CPU_PER_CALL 5000
			CONNECT_TIME 480
			IDLE_TIME 60`,
		// Password parameters
		`CREATE PROFILE secure_profile LIMIT
			FAILED_LOGIN_ATTEMPTS 5
			PASSWORD_LIFE_TIME 90
			PASSWORD_REUSE_TIME 365
			PASSWORD_REUSE_MAX 10
			PASSWORD_LOCK_TIME 1
			PASSWORD_GRACE_TIME 7`,
		// UNLIMITED and DEFAULT values
		`CREATE PROFILE default_profile LIMIT
			SESSIONS_PER_USER UNLIMITED
			CPU_PER_SESSION DEFAULT
			CONNECT_TIME UNLIMITED
			IDLE_TIME DEFAULT`,
		// PASSWORD_VERIFY_FUNCTION
		`CREATE PROFILE verify_profile LIMIT
			PASSWORD_VERIFY_FUNCTION verify_function_name`,
		`CREATE PROFILE no_verify_profile LIMIT
			PASSWORD_VERIFY_FUNCTION NULL`,
		`CREATE PROFILE default_verify_profile LIMIT
			PASSWORD_VERIFY_FUNCTION DEFAULT`,
		// Mixed resource and password parameters
		`CREATE PROFILE mixed_profile LIMIT
			SESSIONS_PER_USER 5
			FAILED_LOGIN_ATTEMPTS 3
			CPU_PER_SESSION UNLIMITED
			PASSWORD_LIFE_TIME 60
			CONNECT_TIME 120
			PASSWORD_LOCK_TIME 1`,
		// LOGICAL_READS and PRIVATE_SGA
		`CREATE PROFILE io_profile LIMIT
			LOGICAL_READS_PER_SESSION 100000
			LOGICAL_READS_PER_CALL 10000
			PRIVATE_SGA 15M
			COMPOSITE_LIMIT 50000`,
		// INACTIVE_ACCOUNT_TIME
		`CREATE PROFILE inactive_profile LIMIT
			INACTIVE_ACCOUNT_TIME 90`,
		// PASSWORD_ROLLOVER_TIME
		`CREATE PROFILE rollover_profile LIMIT
			PASSWORD_ROLLOVER_TIME 1`,
		// MANDATORY profile
		`CREATE MANDATORY PROFILE mandatory_prof LIMIT
			SESSIONS_PER_USER 5
			FAILED_LOGIN_ATTEMPTS 3`,
		// CONTAINER
		`CREATE PROFILE c##common_profile LIMIT
			SESSIONS_PER_USER 10
			CONTAINER = ALL`,
		// Comprehensive
		`CREATE PROFILE full_profile LIMIT
			SESSIONS_PER_USER 10
			CPU_PER_SESSION 10000
			CPU_PER_CALL 5000
			CONNECT_TIME 480
			IDLE_TIME 60
			LOGICAL_READS_PER_SESSION 100000
			LOGICAL_READS_PER_CALL 10000
			PRIVATE_SGA 20M
			COMPOSITE_LIMIT UNLIMITED
			FAILED_LOGIN_ATTEMPTS 5
			PASSWORD_LIFE_TIME 90
			PASSWORD_REUSE_TIME 365
			PASSWORD_REUSE_MAX 10
			PASSWORD_LOCK_TIME 1
			PASSWORD_GRACE_TIME 7
			INACTIVE_ACCOUNT_TIME 90
			PASSWORD_ROLLOVER_TIME 1
			PASSWORD_VERIFY_FUNCTION verify_func`,

		// ---- ALTER PROFILE ----
		// Resource parameters
		`ALTER PROFILE app_profile LIMIT
			SESSIONS_PER_USER 20
			CPU_PER_SESSION UNLIMITED`,
		// Password parameters
		`ALTER PROFILE secure_profile LIMIT
			FAILED_LOGIN_ATTEMPTS 3
			PASSWORD_LIFE_TIME 60`,
		// Mixed
		`ALTER PROFILE mixed_profile LIMIT
			SESSIONS_PER_USER 15
			FAILED_LOGIN_ATTEMPTS 10
			PASSWORD_VERIFY_FUNCTION new_verify_func`,
		// CONTAINER
		`ALTER PROFILE c##common_profile LIMIT
			SESSIONS_PER_USER 5
			CONTAINER = ALL`,
	}
	for _, sql := range tests {
		name := sql
		if len(name) > 60 {
			name = name[:60]
		}
		t.Run(name, func(t *testing.T) {
			result := ParseAndCheck(t, sql)
			if result.Len() < 1 {
				t.Fatalf("expected at least 1 statement, got %d", result.Len())
			}
		})
	}
}
