package parser

import (
	"testing"

	"github.com/bytebase/omni/oracle/ast"
)

// TestSubprogramHeadingClauses checks the clauses of procedure, function,
// and package headings against Oracle 23ai: every accepted form compiles
// there (or fails only on names it cannot resolve), and every rejected one
// fails with the error noted beside it. Rows ref_147 to ref_165 run the
// PLS-00103 cases against the engine; the others are errors Oracle reports
// from the text alone after parsing, which the reference harness counts as
// accepted.
func TestSubprogramHeadingClauses(t *testing.T) {
	for _, sql := range []string{
		// ACCESSIBLE BY with every unit kind, in any order with AUTHID.
		"CREATE PROCEDURE p ACCESSIBLE BY (PACKAGE x, PROCEDURE y, FUNCTION z, TRIGGER t, TYPE ty, plain, s.q) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p (a NUMBER) AUTHID DEFINER ACCESSIBLE BY (x) IS BEGIN NULL; END;",
		"CREATE FUNCTION f RETURN NUMBER ACCESSIBLE BY (x) DETERMINISTIC IS BEGIN RETURN 1; END;",
		"CREATE PACKAGE k AUTHID DEFINER ACCESSIBLE BY (PACKAGE x) AS PROCEDURE p; END;",
		"CREATE PACKAGE k ACCESSIBLE BY (x) AUTHID CURRENT_USER AS PROCEDURE p ACCESSIBLE BY (PACKAGE x); FUNCTION f RETURN NUMBER ACCESSIBLE BY (y); END;",
		"CREATE PACKAGE BODY k AS PROCEDURE p ACCESSIBLE BY (PACKAGE x) IS BEGIN NULL; END; END;",
		"CREATE PROCEDURE p ACCESSIBLE BY (PACKAGE \"X\", s.x) IS BEGIN NULL; END;",
		// A type implements the function, which then has no body.
		"CREATE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE USING impl;",
		"CREATE FUNCTION f (x NUMBER) RETURN NUMBER DETERMINISTIC AGGREGATE USING s.impl;",
		"CREATE FUNCTION f RETURN t PIPELINED USING impl;",
		"CREATE FUNCTION f RETURN t PIPELINED PARALLEL_ENABLE USING impl@lnk;",
		"CREATE FUNCTION f (c SYS_REFCURSOR) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) USING impl;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED TABLE POLYMORPHIC USING pkg;",
		"CREATE PACKAGE k AS FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE USING impl; FUNCTION g RETURN t PIPELINED USING impl; END;",
		// PARALLEL_ENABLE partitioning and streaming clauses.
		"CREATE FUNCTION f (c SYS_REFCURSOR) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY HASH (a, b)) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY RANGE (a)) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY VALUE (a)) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY HASH (a, b)) ORDER c BY (a, b) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY HASH (a)) ORDER c BY (a) CLUSTER c BY (b) IS BEGIN RETURN; END;",
		// RESULT_CACHE RELIES_ON and SQL_MACRO.
		"CREATE FUNCTION f RETURN NUMBER RESULT_CACHE RELIES_ON (t1, s.t2) IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f RETURN NUMBER RESULT_CACHE RELIES_ON () IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO (TYPE => TABLE) IS BEGIN RETURN 'x'; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO (SCALAR) IS BEGIN RETURN 'x'; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO IS BEGIN RETURN 'x'; END;",
		// CHARACTER SET on parameters, results, and declarations.
		"CREATE PROCEDURE p (a VARCHAR2 CHARACTER SET ANY_CS, b IN OUT NOCOPY CLOB CHARACTER SET ANY_CS, c CHAR CHARACTER SET ANY_CS DEFAULT 'x') IS BEGIN NULL; END;",
		"CREATE FUNCTION f (a VARCHAR2 CHARACTER SET ANY_CS) RETURN VARCHAR2 CHARACTER SET a%CHARSET IS v VARCHAR2(10) CHARACTER SET a%CHARSET; BEGIN RETURN a; END;",
		"CREATE PROCEDURE p (a VARCHAR2 CHARACTER SET CHAR_CS, b VARCHAR2 CHARACTER SET NCHAR_CS) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p (a STRING CHARACTER SET ANY_CS, b CHARACTER CHARACTER SET ANY_CS, c my_subtype CHARACTER SET ANY_CS) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p (a VARCHAR2 CHARACTER SET ANY_CS) IS c CONSTANT VARCHAR2(10) CHARACTER SET a%CHARSET NOT NULL := 'x'; SUBTYPE s IS VARCHAR2(10) CHARACTER SET a%CHARSET; TYPE r IS RECORD (f VARCHAR2(10) CHARACTER SET CHAR_CS); CURSOR cu (q VARCHAR2 CHARACTER SET a%CHARSET) IS SELECT 1 FROM dual; BEGIN NULL; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 CHARACTER SET CHAR_CS IS BEGIN RETURN NULL; END;",
		// A polymorphic table function may have a body (it compiles on
		// Oracle 23ai), and an implementation type a dotted database link.
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN t PIPELINED USING impl@lnk.dom;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC ACCESSIBLE BY (y) USING pkg;",
		"CREATE PROCEDURE p ACCESSIBLE BY (loop, \"SELECT\") IS BEGIN NULL; END;",
		// A SQL macro returns a character type, national ones included.
		"CREATE FUNCTION f RETURN NVARCHAR2 SQL_MACRO IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN CLOB SQL_MACRO IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN CHAR SQL_MACRO (SCALAR) IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN STRING SQL_MACRO ACCESSIBLE BY (x) IS BEGIN RETURN NULL; END;",
		// The partitioned argument matches a parameter however it is quoted,
		// and may be IN; the streaming clauses may come first.
		"CREATE FUNCTION f (c IN SYS_REFCURSOR) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION \"C\" BY ANY) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t ORDER c BY (a) PARALLEL_ENABLE (PARTITION c BY ANY) PIPELINED IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (t TABLE, c COLUMNS) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (t TABLE, x NUMBER) RETURN TABLE PIPELINED TABLE POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (a IN NUMBER) RETURN NUMBER RESULT_CACHE RELIES_ON () IS BEGIN RETURN 1; END;",
		"CREATE TYPE ty AS OBJECT (a NUMBER, MEMBER PROCEDURE p (x VARCHAR2, b VARCHAR2 CHARACTER SET x%CHARSET))",
		"CREATE FUNCTION f (t TABLE, c COLUMNS DEFAULT NULL) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (a DATE, b VARCHAR2, c BOOLEAN) RETURN NUMBER RESULT_CACHE IS BEGIN RETURN 1; END;",
		"CREATE PROCEDURE p AUTHID \"CURRENT_USER\" IS BEGIN NULL; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY HASH (\"A\", b)) IS BEGIN RETURN; END;",
		// A quoted formal spelled like a dotted %CHARSET source, a quoted "*"
		// column, and a result-cached %ROWTYPE result compile.
		"CREATE FUNCTION f (\"K.C\" NUMBER) RETURN VARCHAR2 CHARACTER SET k.c%CHARSET IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY HASH (\"*\")) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f RETURN dual%ROWTYPE RESULT_CACHE IS r dual%ROWTYPE; BEGIN RETURN r; END;",
		"CREATE PROCEDURE p IS BEGIN DECLARE FUNCTION f RETURN NUMBER RESULT_CACHE RELIES_ON () IS BEGIN RETURN 1; END; BEGIN NULL; END; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY HASH (a)) ORDER c BY (a) CLUSTER c BY (b) IS BEGIN RETURN; END;",
		"CREATE PACKAGE BODY k AS FUNCTION g RETURN NUMBER PARALLEL_ENABLE IS BEGIN RETURN 1; END; END;",
		"CREATE PROCEDURE p IS n VARCHAR2(10); v VARCHAR2(10) CHARACTER SET n%CHARSET; BEGIN NULL; END;",
		"CREATE FUNCTION f (c SYS_REFCURSOR) RETURN NUMBER PARALLEL_ENABLE (PARTITION c BY ANY) IS BEGIN RETURN 1; END;",
		"DECLARE CURSOR c (a VARCHAR2, b VARCHAR2 CHARACTER SET a%CHARSET) IS SELECT 1 FROM dual; BEGIN NULL; END;",
		"CREATE PROCEDURE p IS FUNCTION f RETURN t PIPELINED DETERMINISTIC IS BEGIN RETURN; END; BEGIN NULL; END;",
		"DECLARE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE USING impl; BEGIN NULL; END;",
		// Nested SQL macros and result-cached functions compile, and a
		// definer's rights package may hold a SQL macro.
		"CREATE PROCEDURE p IS FUNCTION f RETURN VARCHAR2 SQL_MACRO IS BEGIN RETURN NULL; END; BEGIN NULL; END;",
		"CREATE PROCEDURE p IS FUNCTION f RETURN NUMBER RESULT_CACHE IS BEGIN RETURN 1; END; BEGIN NULL; END;",
		"CREATE PACKAGE k AUTHID DEFINER AS FUNCTION f RETURN VARCHAR2 SQL_MACRO; END;",
		// A quoted name is a user type, not the predefined one: Oracle 23ai
		// compiles this package.
		"CREATE PACKAGE k AS SUBTYPE \"NUMBER\" IS VARCHAR2(100); FUNCTION m RETURN \"NUMBER\" SQL_MACRO; " +
			"TYPE \"SYS_REFCURSOR\" IS REF CURSOR RETURN dual%ROWTYPE; " +
			"FUNCTION p (c \"SYS_REFCURSOR\") RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY HASH (dummy)); " +
			"SUBTYPE \"CLOB\" IS NUMBER; FUNCTION r RETURN \"CLOB\" RESULT_CACHE; END;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg@lnk;",
		// A quoted "TABLE" or "COLUMNS" names a user type, not the pseudo-type.
		"CREATE PROCEDURE p (a \"COLUMNS\") IS BEGIN NULL; END;",
		"CREATE PROCEDURE p (a \"TABLE\") IS BEGIN NULL; END;",
		"CREATE FUNCTION f (a \"TABLE\") RETURN NUMBER IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY RANGE (a, b)) IS BEGIN RETURN; END;",
		// item%CHARSET may name a character parameter without ANY_CS, a
		// national one, or an item outside the heading.
		"CREATE FUNCTION f (a VARCHAR2) RETURN VARCHAR2 CHARACTER SET a%CHARSET IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f (a NVARCHAR2) RETURN VARCHAR2 CHARACTER SET a%CHARSET IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 CHARACTER SET k.c%CHARSET IS BEGIN RETURN NULL; END;",
		// Oracle 23ai compiles these combinations and nested polymorphic
		// table functions.
		"CREATE FUNCTION f (a VARCHAR2) RETURN VARCHAR2 SQL_MACRO AGGREGATE USING impl;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC AGGREGATE USING pkg;",
		"CREATE PROCEDURE p IS FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC IS BEGIN RETURN NULL; END; BEGIN NULL; END;",
		"DECLARE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg; BEGIN NULL; END;",
		// An aggregate compiles with several or OUT parameters.
		"CREATE FUNCTION f (a NUMBER, b NUMBER) RETURN NUMBER AGGREGATE USING impl;",
		"CREATE FUNCTION f (a IN OUT NUMBER) RETURN NUMBER AGGREGATE USING impl;",
		"CREATE FUNCTION f RETURN pipelined.using IS BEGIN RETURN NULL; END;",
		// USING as a name, not an implementation clause.
		"CREATE FUNCTION using RETURN NUMBER IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION g (using NUMBER) RETURN NUMBER IS BEGIN RETURN using; END;",
		// Unconstrained parameter and result types.
		"CREATE PROCEDURE p (a TIMESTAMP WITH TIME ZONE, b INTERVAL DAY TO SECOND, c INTERVAL YEAR TO MONTH, d LONG RAW, e RAW) IS BEGIN NULL; END;",
	} {
		ParseAndCheck(t, sql)
		if violations := CheckLocations(t, sql); len(violations) > 0 {
			t.Errorf("Parse(%q) Loc violations: %v", sql, violations)
		}
	}

	for _, sql := range []string{
		// ACCESSIBLE BY (PLS-00103 unless noted).
		"CREATE PROCEDURE p ACCESSIBLE BY () IS BEGIN NULL; END;",
		"CREATE PROCEDURE p ACCESSIBLE BY x IS BEGIN NULL; END;",
		"CREATE PROCEDURE p ACCESSIBLE BY (PACKAGE) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p ACCESSIBLE BY (VIEW x) IS BEGIN NULL; END;",
		"CREATE FUNCTION f RETURN NUMBER ACCESSIBLE BY (x@lnk) IS BEGIN RETURN 1; END;",
		"CREATE PROCEDURE p ACCESSIBLE BY (x) AUTHID DEFINER ACCESSIBLE BY (y) IS BEGIN NULL; END;", // PLS-00371
		"CREATE PACKAGE k ACCESSIBLE BY (x) ACCESSIBLE BY (y) AS PROCEDURE p; END;",                 // PLS-00371
		"CREATE PACKAGE k AUTHID DEFINER AUTHID DEFINER AS PROCEDURE p; END;",                       // PLS-00371
		"CREATE PROCEDURE p AUTHID DEFINER AUTHID CURRENT_USER IS BEGIN NULL; END;",                 // PLS-00371
		// A type implements the function: nothing may follow but ';'.
		"CREATE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE USING impl IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f RETURN t PIPELINED USING impl IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE USING impl DETERMINISTIC;",
		"CREATE FUNCTION f RETURN t USING impl PIPELINED;",
		"CREATE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE PARALLEL_ENABLE USING impl;",
		"CREATE FUNCTION f RETURN t PIPELINED USING;",
		"CREATE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE USING impl.;",
		"CREATE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE USING impl@;",
		"CREATE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE USING impl",
		"CREATE FUNCTION f RETURN NUMBER USING impl;",           // PLS-00624
		"CREATE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE;", // PLS-00220
		// PARALLEL_ENABLE and streaming clauses.
		"CREATE FUNCTION f (c SYS_REFCURSOR) RETURN t PARALLEL_ENABLE () IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c SYS_REFCURSOR) RETURN t PARALLEL_ENABLE (PARTITION c) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c SYS_REFCURSOR) RETURN t PARALLEL_ENABLE (PARTITION c BY LIST (a)) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PARALLEL_ENABLE (PARTITION c BY HASH ()) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PARALLEL_ENABLE (PARTITION c BY ANY) ORDER c BY () IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PARALLEL_ENABLE (PARTITION c BY ANY) ORDER c.x BY (a) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t ORDER c BY (a) ORDER c BY (b) IS BEGIN RETURN; END;",     // PLS-00371
		"CREATE FUNCTION f (c pkg.rc) RETURN t CLUSTER c BY (a) CLUSTER c BY (b) IS BEGIN RETURN; END;", // PLS-00371
		// SQL_MACRO and repeated clauses.
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO () IS BEGIN RETURN 'x'; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO (foo) IS BEGIN RETURN 'x'; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO (TYPE => foo) IS BEGIN RETURN 'x'; END;",
		"CREATE FUNCTION f RETURN NUMBER DETERMINISTIC DETERMINISTIC IS BEGIN RETURN 1; END;",     // PLS-00371
		"CREATE FUNCTION f RETURN t PIPELINED PIPELINED IS BEGIN RETURN; END;",                    // PLS-00371
		"CREATE FUNCTION f RETURN NUMBER RESULT_CACHE RESULT_CACHE IS BEGIN RETURN 1; END;",       // PLS-00371
		"CREATE FUNCTION f RETURN NUMBER PARALLEL_ENABLE PARALLEL_ENABLE IS BEGIN RETURN 1; END;", // PLS-00371
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO SQL_MACRO IS BEGIN RETURN 'x'; END;",         // PLS-00371
		"CREATE FUNCTION f RETURN NUMBER AUTHID DEFINER AUTHID DEFINER IS BEGIN RETURN 1; END;",   // PLS-00371
		"CREATE FUNCTION f RETURN NUMBER RESULT_CACHE RELIES_ON (t1,) IS BEGIN RETURN 1; END;",
		// A polymorphic table function takes none of these (PLS-00760, and
		// PLS-00999 for RESULT_CACHE), before or after POLYMORPHIC.
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC DETERMINISTIC USING pkg;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE DETERMINISTIC PIPELINED TABLE POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC PARALLEL_ENABLE USING pkg;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE AUTHID DEFINER PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC RESULT_CACHE USING pkg;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC ORDER t BY (a) USING pkg;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC DETERMINISTIC IS BEGIN RETURN NULL; END;",
		// A SQL macro takes no DETERMINISTIC, PARALLEL_ENABLE, RESULT_CACHE,
		// AUTHID, or streaming clause (PLS-00778), no PIPELINED (PLS-00630),
		// and returns a character type (PLS-00776).
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO DETERMINISTIC IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 DETERMINISTIC SQL_MACRO IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO PARALLEL_ENABLE IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO RESULT_CACHE IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO AUTHID DEFINER IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN VARCHAR2 SQL_MACRO ORDER c BY (a) IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO PIPELINED IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN NUMBER SQL_MACRO IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f RETURN LONG SQL_MACRO IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN dual%ROWTYPE SQL_MACRO IS BEGIN RETURN NULL; END;",
		// The row kind is required (PLS-00103); a type method is not
		// polymorphic (PLS-00765); PIPELINED excludes AGGREGATE (PLS-00371).
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED POLYMORPHIC USING pkg;",
		"CREATE TYPE ty AS OBJECT (a NUMBER, MEMBER FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC)",
		"CREATE FUNCTION f (a NUMBER) RETURN NUMBER PIPELINED AGGREGATE USING impl;",
		// PARALLEL_ENABLE partitions an IN parameter (PLS-00626, PLS-00625);
		// a streaming clause needs PARALLEL_ENABLE with PARTITION BY on the
		// same argument (PLS-00654, PLS-00665, PLS-00631).
		"CREATE FUNCTION f RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c OUT SYS_REFCURSOR) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c IN OUT SYS_REFCURSOR) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t ORDER c BY (a) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE ORDER c BY (a) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc, d pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) CLUSTER d BY (a) IS BEGIN RETURN; END;",
		// The partitioned argument is a strong REF CURSOR unless it is a
		// SYS_REFCURSOR partitioned BY ANY without streaming (PLS-00627).
		"CREATE FUNCTION f (c NUMBER) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c VARCHAR2) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c SYS_REFCURSOR) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY HASH (a)) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c SYS_REFCURSOR) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY VALUE (a)) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c SYS_REFCURSOR) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) ORDER c BY (a) IS BEGIN RETURN; END;",
		// A polymorphic table function returns TABLE (PLS-00767) and takes one
		// TABLE parameter (PLS-00773, PLS-00766).
		"CREATE FUNCTION f (t TABLE) RETURN NUMBER PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (x NUMBER) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (t TABLE, u TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;",
		// COLUMNS stands only in a polymorphic table function (PLS-00765).
		"CREATE PROCEDURE p (c COLUMNS) IS BEGIN NULL; END;",
		"CREATE FUNCTION f (c COLUMNS) RETURN NUMBER IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f RETURN COLUMNS IS BEGIN RETURN NULL; END;",
		// Multiword predefined types are not character types (PLS-00776,
		// PLS-00550) or REF CURSORs (PLS-00627).
		"CREATE FUNCTION f RETURN TIMESTAMP WITH TIME ZONE SQL_MACRO IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN TIMESTAMP WITH LOCAL TIME ZONE SQL_MACRO IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN LONG RAW SQL_MACRO IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN INTERVAL DAY TO SECOND SQL_MACRO IS BEGIN RETURN NULL; END;",
		"CREATE PROCEDURE p (a TIMESTAMP WITH TIME ZONE CHARACTER SET ANY_CS) IS BEGIN NULL; END;",
		"CREATE FUNCTION f (c TIMESTAMP WITH TIME ZONE) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) IS BEGIN RETURN; END;",
		// Type method procedures and ALTER TYPE signatures take the heading
		// checks (PLS-00550, PLS-00765); RESULT_CACHE takes no OUT or IN OUT
		// parameter (PLS-00999).
		"CREATE TYPE ty AS OBJECT (a NUMBER, MEMBER PROCEDURE p (x NUMBER, b VARCHAR2 CHARACTER SET x%CHARSET))",
		"CREATE TYPE ty AS OBJECT (a NUMBER, MEMBER PROCEDURE p (t TABLE))",
		"ALTER TYPE ty ADD MEMBER PROCEDURE p (x NUMBER, b VARCHAR2 CHARACTER SET x%CHARSET) CASCADE",
		"ALTER TYPE ty ADD MEMBER FUNCTION f (t TABLE) RETURN NUMBER CASCADE",
		"ALTER TYPE ty ADD MEMBER FUNCTION f RETURN VARCHAR2(10) CASCADE",
		"CREATE FUNCTION f (a OUT NUMBER) RETURN NUMBER RESULT_CACHE IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f (a IN OUT NUMBER) RETURN NUMBER RESULT_CACHE RELIES_ON () IS BEGIN RETURN 1; END;",
		"CREATE PACKAGE k AS FUNCTION f (a IN OUT NOCOPY NUMBER) RETURN NUMBER RESULT_CACHE; END;",
		// TABLE takes no default (PLS-00768), COLUMNS only NULL (PLS-00769);
		// RESULT_CACHE takes no LOB, BFILE, or REF CURSOR (PLS-00999);
		// AUTHID CURRENT_USER is one word (PLS-00103); partition and
		// streaming items are simple column names (PLS-00670).
		"CREATE FUNCTION f (t TABLE DEFAULT dual) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (t TABLE DEFAULT NULL) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (t TABLE, c COLUMNS DEFAULT 1) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;",
		// Only a bare NULL: Oracle 23ai rejects DEFAULT (NULL) too (PLS-00769).
		"CREATE FUNCTION f (t TABLE, c COLUMNS DEFAULT (NULL)) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (a BLOB) RETURN NUMBER RESULT_CACHE IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f (a NCLOB) RETURN NUMBER RESULT_CACHE RELIES_ON () IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f RETURN CLOB RESULT_CACHE IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN SYS_REFCURSOR RESULT_CACHE IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f (a BFILE) RETURN NUMBER RESULT_CACHE IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f (a dual%ROWTYPE) RETURN NUMBER RESULT_CACHE IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f (\"K.C\" NUMBER) RETURN VARCHAR2 CHARACTER SET \"K.C\"%CHARSET IS BEGIN RETURN NULL; END;",
		"DECLARE FUNCTION f RETURN NUMBER RESULT_CACHE IS BEGIN RETURN 1; END; BEGIN NULL; END;",
		"DECLARE CURSOR c (a NUMBER, b VARCHAR2 CHARACTER SET a%CHARSET) IS SELECT 1 FROM dual; BEGIN NULL; END;",
		"CREATE PROCEDURE p IS CURSOR c (a DATE, b VARCHAR2 CHARACTER SET a%CHARSET) IS SELECT 1 FROM dual; BEGIN NULL; END;",
		// A body declaration's %CHARSET source is a formal or preceding local
		// of a non-character type (PLS-00550); an aggregate's type is local
		// (PLS-00331).
		"CREATE PROCEDURE p (a NUMBER) IS v VARCHAR2(10) CHARACTER SET a%CHARSET; BEGIN NULL; END;",
		"CREATE PROCEDURE p IS n NUMBER; v VARCHAR2(10) CHARACTER SET n%CHARSET; BEGIN NULL; END;",
		"CREATE PACKAGE BODY k AS FUNCTION f (a DATE) RETURN NUMBER IS v VARCHAR2(10) CHARACTER SET a%CHARSET; BEGIN RETURN 1; END; END;",
		"CREATE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE USING impl@lnk;",
		// CHARACTER SET on a pseudo-type (PLS-00550); PARALLEL_ENABLE on a
		// nested function (PLS-00712).
		"CREATE FUNCTION f (t TABLE CHARACTER SET ANY_CS) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE CHARACTER SET CHAR_CS PIPELINED ROW POLYMORPHIC USING pkg;",
		"CREATE PROCEDURE p IS FUNCTION f RETURN NUMBER PARALLEL_ENABLE IS BEGIN RETURN 1; END; BEGIN NULL; END;",
		"DECLARE FUNCTION f RETURN NUMBER PARALLEL_ENABLE IS BEGIN RETURN 1; END; BEGIN NULL; END;",
		"DECLARE FUNCTION f RETURN NUMBER RESULT_CACHE RELIES_ON () IS BEGIN RETURN 1; END; BEGIN NULL; END;",
		"BEGIN DECLARE FUNCTION f RETURN NUMBER RESULT_CACHE IS BEGIN RETURN 1; END; BEGIN NULL; END; END;",
		"DECLARE PROCEDURE q IS FUNCTION f RETURN NUMBER RESULT_CACHE IS BEGIN RETURN 1; END; BEGIN NULL; END; BEGIN NULL; END;",
		"CREATE PROCEDURE p AUTHID CURRENT IS BEGIN NULL; END;",
		"CREATE PROCEDURE p AUTHID CURRENT USER IS BEGIN NULL; END;",
		"CREATE PACKAGE k AUTHID CURRENT AS PROCEDURE p; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY HASH (a || 'x')) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY ANY) ORDER c BY (lower(a)) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY HASH (c.a)) IS BEGIN RETURN; END;",
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY RANGE (1)) IS BEGIN RETURN; END;",
		// An ordinary pipelined function returns a collection (PLS-00630) and
		// is not result-cached (PLS-00999); a package holding a SQL macro is
		// not AUTHID CURRENT_USER (PLS-00782).
		"CREATE FUNCTION f RETURN NUMBER PIPELINED IS BEGIN RETURN; END;",
		"CREATE FUNCTION f RETURN VARCHAR2 PIPELINED IS BEGIN RETURN; END;",
		"CREATE FUNCTION f RETURN dual%ROWTYPE PIPELINED IS BEGIN RETURN; END;",
		"CREATE FUNCTION f RETURN NUMBER PIPELINED USING impl;",
		"CREATE FUNCTION f RETURN t PIPELINED RESULT_CACHE IS BEGIN RETURN; END;",
		"CREATE PACKAGE k AUTHID CURRENT_USER AS FUNCTION f RETURN VARCHAR2 SQL_MACRO; END;",
		// VALUE partitioning takes one column (PLS-00757); BOOL is BOOLEAN
		// (PLS-00550); clause keywords are unquoted (PLS-00103).
		"CREATE FUNCTION f (c pkg.rc) RETURN t PIPELINED PARALLEL_ENABLE (PARTITION c BY VALUE (a, b)) IS BEGIN RETURN; END;",
		"CREATE PROCEDURE p (a BOOL CHARACTER SET ANY_CS) IS BEGIN NULL; END;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW \"POLYMORPHIC\" USING pkg;",
		"CREATE PACKAGE k DEFAULT \"COLLATION\" USING_NLS_COMP AS PROCEDURE p; END;",
		// item%CHARSET of a non-character parameter (PLS-00550).
		"CREATE FUNCTION f (a NUMBER) RETURN VARCHAR2 CHARACTER SET a%CHARSET IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f (a DATE) RETURN VARCHAR2 CHARACTER SET a%CHARSET IS BEGIN RETURN NULL; END;",
		"CREATE PROCEDURE p (a NUMBER, b VARCHAR2 CHARACTER SET a%CHARSET) IS BEGIN NULL; END;",
		"CREATE PACKAGE k AS FUNCTION f (c pkg.rc) RETURN t PIPELINED ORDER c BY (a); END;",
		// TABLE stands only in a polymorphic table function (PLS-00765), and a
		// type method is not a SQL macro (PLS-00781).
		"CREATE PROCEDURE p (t TABLE) IS BEGIN NULL; END;",
		"CREATE FUNCTION f (t TABLE) RETURN NUMBER IS BEGIN RETURN 1; END;",
		"CREATE FUNCTION f RETURN TABLE IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f (t TABLE) RETURN VARCHAR2 SQL_MACRO (SCALAR) IS BEGIN RETURN 'x'; END;",
		"CREATE FUNCTION f (t TABLE) RETURN VARCHAR2 SQL_MACRO IS BEGIN RETURN 'x'; END;",
		"CREATE PACKAGE k AS PROCEDURE p (t TABLE); END;",
		"CREATE TYPE ty AS OBJECT (a NUMBER, MEMBER FUNCTION f RETURN VARCHAR2 SQL_MACRO)",
		"CREATE TYPE ty AS OBJECT (a NUMBER, STATIC FUNCTION f RETURN VARCHAR2 SQL_MACRO)",
		// An aggregate takes an argument (PLS-00652).
		"CREATE FUNCTION f RETURN NUMBER AGGREGATE USING impl;",
		// ACCESSIBLE BY is not for a nested subprogram (PLS-00262, PLS-00263).
		"DECLARE PROCEDURE p ACCESSIBLE BY (x) IS BEGIN NULL; END; BEGIN NULL; END;",
		"CREATE PROCEDURE p IS FUNCTION f RETURN NUMBER ACCESSIBLE BY (x) IS BEGIN RETURN 1; END; BEGIN NULL; END;",
		// DEFAULT COLLATION takes USING_NLS_COMP unquoted (documented).
		"CREATE PROCEDURE p DEFAULT COLLATION BINARY IS BEGIN NULL; END;",
		"CREATE PROCEDURE p DEFAULT COLLATION \"USING_NLS_COMP\" IS BEGIN NULL; END;",
		// A %ROWTYPE record takes no character set (PLS-00550).
		"CREATE PROCEDURE p (a dual%ROWTYPE CHARACTER SET ANY_CS) IS BEGIN NULL; END;",
		// Names are not PL/SQL reserved words (PLS-00103).
		"CREATE PROCEDURE p ACCESSIBLE BY (SELECT) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p ACCESSIBLE BY (BEGIN) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p ACCESSIBLE BY (PACKAGE SELECT) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p ACCESSIBLE BY (sys.select) IS BEGIN NULL; END;",
		"CREATE FUNCTION f RETURN NUMBER RESULT_CACHE RELIES_ON (BEGIN) IS BEGIN RETURN 1; END;",
		// Clause keywords are unquoted words.
		"CREATE PROCEDURE p \"ACCESSIBLE\" BY (x) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p \"AUTHID\" DEFINER IS BEGIN NULL; END;",
		"CREATE PACKAGE k \"AUTHID\" DEFINER AS PROCEDURE p; END;",
		"CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED \"ROW\" POLYMORPHIC USING pkg;",
		// AUTHID stands only on a schema-level unit (PLS-00157), ACCESSIBLE
		// BY not on a type method (PLS-00262), DEFAULT COLLATION only on a
		// schema-level unit (documented).
		"CREATE PACKAGE k AS PROCEDURE p AUTHID DEFINER; END;",
		"CREATE PACKAGE k AS FUNCTION f RETURN NUMBER AUTHID DEFINER; END;",
		"CREATE PACKAGE k AS PROCEDURE p ACCESSIBLE BY (x) AUTHID DEFINER; END;",
		"CREATE PROCEDURE p IS PROCEDURE q AUTHID DEFINER IS BEGIN NULL; END; BEGIN NULL; END;",
		"DECLARE FUNCTION f RETURN NUMBER AUTHID CURRENT_USER IS BEGIN RETURN 1; END; BEGIN NULL; END;",
		"CREATE PACKAGE k AS PROCEDURE p DEFAULT COLLATION USING_NLS_COMP; END;",
		"CREATE PACKAGE k AS FUNCTION f RETURN NUMBER DEFAULT COLLATION USING_NLS_COMP; END;",
		"CREATE TYPE ty AS OBJECT (a NUMBER, MEMBER FUNCTION f RETURN NUMBER AUTHID DEFINER)",
		"CREATE TYPE ty AS OBJECT (a NUMBER, MEMBER FUNCTION f RETURN NUMBER ACCESSIBLE BY (x))",
		// CHARACTER SET.
		"CREATE PROCEDURE p (a VARCHAR2 CHARACTER SET) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p (a VARCHAR2 CHARACTER SET a%TYPE) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p (a NUMBER CHARACTER SET ANY_CS) IS BEGIN NULL; END;",                                                              // PLS-00550
		"CREATE PROCEDURE p (a BOOLEAN CHARACTER SET ANY_CS) IS BEGIN NULL; END;",                                                             // PLS-00550
		"CREATE PROCEDURE p (a PLS_INTEGER CHARACTER SET ANY_CS) IS BEGIN NULL; END;",                                                         // PLS-00550
		"CREATE PROCEDURE p (a SYS_REFCURSOR CHARACTER SET ANY_CS) IS BEGIN NULL; END;",                                                       // PLS-00550
		"CREATE FUNCTION f (a VARCHAR2 CHARACTER SET ANY_CS) RETURN VARCHAR2 CHARACTER SET a%\"CHARSET\" IS BEGIN RETURN a; END;",             // PLS-00550
		"CREATE PROCEDURE p (a NVARCHAR2 CHARACTER SET ANY_CS) IS BEGIN NULL; END;",                                                           // PLS-00554
		"CREATE PROCEDURE p (a LONG CHARACTER SET ANY_CS) IS BEGIN NULL; END;",                                                                // PLS-00554
		"CREATE PROCEDURE p IS v VARCHAR2(10) CHARACTER SET ANY_CS; BEGIN NULL; END;",                                                         // PLS-00551
		"CREATE FUNCTION f RETURN VARCHAR2 CHARACTER SET ANY_CS IS BEGIN RETURN NULL; END;",                                                   // PLS-00551
		"CREATE PROCEDURE p IS CURSOR c (q VARCHAR2 CHARACTER SET ANY_CS) IS SELECT 1 FROM dual; BEGIN NULL; END;",                            // PLS-00551
		"CREATE PROCEDURE p (a VARCHAR2 CHARACTER SET ANY_CS) IS TYPE r IS RECORD (f VARCHAR2(10) CHARACTER SET a%CHARSET); BEGIN NULL; END;", // PLS-00552
		"CREATE PROCEDURE p (a VARCHAR2 CHARACTER SET ANY_CS) IS TYPE t IS TABLE OF VARCHAR2(10) CHARACTER SET a%CHARSET; BEGIN NULL; END;",   // PLS-00552
		"CREATE TABLE t (c VARCHAR2(10) CHARACTER SET ANY_CS)",
		// Constrained parameter and result types.
		"CREATE PROCEDURE p (a VARCHAR2(10)) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p (a NUMBER(5)) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p (a TIMESTAMP(3)) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p (a INTERVAL DAY(2) TO SECOND(6)) IS BEGIN NULL; END;",
		"CREATE PROCEDURE p (a FLOAT(5)) IS BEGIN NULL; END;",
		"CREATE FUNCTION f RETURN VARCHAR2(10) IS BEGIN RETURN NULL; END;",
		"CREATE FUNCTION f RETURN NUMBER(5) IS BEGIN RETURN 1; END;",
		"CREATE PACKAGE k AS PROCEDURE p (a VARCHAR2(10)); END;",
		"CREATE TYPE ty AS OBJECT (a NUMBER, MEMBER FUNCTION f (x VARCHAR2(10)) RETURN NUMBER)",
		"CREATE TYPE ty AS OBJECT (a NUMBER, MEMBER FUNCTION f RETURN VARCHAR2(10))",
		"CREATE PROCEDURE p IS CURSOR c (q VARCHAR2(10)) IS SELECT 1 FROM dual; BEGIN NULL; END;",
		"CREATE PROCEDURE p IS FUNCTION f (x NUMBER(5)) RETURN NUMBER IS BEGIN RETURN 1; END; BEGIN NULL; END;",
		"CREATE PROCEDURE p IS TYPE rc IS REF CURSOR RETURN VARCHAR2(10); BEGIN NULL; END;",
	} {
		ParseShouldFail(t, sql)
	}
}

// TestSubprogramHeadingClausesAST checks what the heading clauses record.
func TestSubprogramHeadingClausesAST(t *testing.T) {
	proc := parseOne[*ast.CreateProcedureStmt](t, "CREATE PROCEDURE p AUTHID DEFINER ACCESSIBLE BY (PACKAGE s.k, f) IS BEGIN NULL; END;")
	if proc.AuthID != "DEFINER" || proc.AccessibleBy == nil || proc.AccessibleBy.Len() != 2 {
		t.Fatalf("procedure AuthID %q, AccessibleBy %v", proc.AuthID, proc.AccessibleBy)
	}
	first := proc.AccessibleBy.Items[0].(*ast.Accessor)
	second := proc.AccessibleBy.Items[1].(*ast.Accessor)
	if first.UnitKind != "PACKAGE" || first.Name.Schema != "S" || first.Name.Name != "K" || second.UnitKind != "" || second.Name.Name != "F" {
		t.Errorf("accessors = %+v %+v, want PACKAGE S.K and F", first, second)
	}

	pkg := parseOne[*ast.CreatePackageStmt](t, "CREATE PACKAGE k AUTHID CURRENT_USER ACCESSIBLE BY (x) DEFAULT COLLATION USING_NLS_COMP AS PROCEDURE p; END;")
	if pkg.AuthID != "CURRENT_USER" || pkg.AccessibleBy == nil || pkg.AccessibleBy.Len() != 1 || pkg.DefaultCollation != "USING_NLS_COMP" {
		t.Errorf("package AuthID %q, AccessibleBy %v, DefaultCollation %q", pkg.AuthID, pkg.AccessibleBy, pkg.DefaultCollation)
	}
	coll := parseOne[*ast.CreateProcedureStmt](t, "CREATE PROCEDURE p DEFAULT COLLATION USING_NLS_COMP IS BEGIN NULL; END;")
	if coll.DefaultCollation != "USING_NLS_COMP" {
		t.Errorf("procedure DefaultCollation = %q, want USING_NLS_COMP", coll.DefaultCollation)
	}
	fcoll := parseOne[*ast.CreateFunctionStmt](t, "CREATE FUNCTION f RETURN NUMBER DEFAULT COLLATION USING_NLS_COMP IS BEGIN RETURN 1; END;")
	if fcoll.DefaultCollation != "USING_NLS_COMP" {
		t.Errorf("function DefaultCollation = %q, want USING_NLS_COMP", fcoll.DefaultCollation)
	}

	agg := parseOne[*ast.CreateFunctionStmt](t, "CREATE FUNCTION f (x NUMBER) RETURN NUMBER AGGREGATE USING s.impl;")
	if !agg.Aggregate || agg.Implementation == nil || agg.Implementation.Schema != "S" || agg.Implementation.Name != "IMPL" || agg.Body != nil {
		t.Errorf("aggregate function = %+v", agg)
	}

	ptf := parseOne[*ast.CreateFunctionStmt](t, "CREATE FUNCTION f (t TABLE) RETURN TABLE PIPELINED ROW POLYMORPHIC USING pkg;")
	if !ptf.Pipelined || ptf.Polymorphic != "ROW" || ptf.Implementation == nil || ptf.Implementation.Name != "PKG" {
		t.Errorf("polymorphic function = %+v", ptf)
	}

	par := parseOne[*ast.CreateFunctionStmt](t, "CREATE FUNCTION f (c pkg.rc) RETURN t PARALLEL_ENABLE (PARTITION c BY HASH (a, b)) CLUSTER c BY (a) RESULT_CACHE RELIES_ON (t1) IS BEGIN RETURN NULL; END;")
	if spec := par.ParallelSpec; spec == nil || spec.Argument != "C" || spec.PartitionBy != "HASH" || spec.Columns.Len() != 2 {
		t.Errorf("parallel spec = %+v", par.ParallelSpec)
	}
	if par.Streaming == nil || par.Streaming.Len() != 1 {
		t.Fatalf("streaming = %v", par.Streaming)
	}
	if s := par.Streaming.Items[0].(*ast.StreamingClause); s.Kind != "CLUSTER" || s.Argument != "C" || s.Columns.Len() != 1 {
		t.Errorf("streaming clause = %+v", s)
	}
	if par.ReliesOn == nil || par.ReliesOn.Len() != 1 {
		t.Errorf("RELIES_ON %v", par.ReliesOn)
	}
	macro := parseOne[*ast.CreateFunctionStmt](t, "CREATE FUNCTION f RETURN VARCHAR2 SQL_MACRO (TYPE => TABLE) IS BEGIN RETURN 'x'; END;")
	if !macro.SqlMacro || macro.SqlMacroType != "TABLE" {
		t.Errorf("SQL_MACRO %v type %q", macro.SqlMacro, macro.SqlMacroType)
	}

	cs := parseOne[*ast.CreateFunctionStmt](t, "CREATE FUNCTION f (a VARCHAR2 CHARACTER SET ANY_CS) RETURN VARCHAR2 CHARACTER SET a%CHARSET IS BEGIN RETURN a; END;")
	param := cs.Parameters.Items[0].(*ast.Parameter)
	if param.TypeName.CharacterSet != "ANY_CS" || param.TypeName.IsPercCharset {
		t.Errorf("parameter character set = %q (%%CHARSET %v), want ANY_CS", param.TypeName.CharacterSet, param.TypeName.IsPercCharset)
	}
	if cs.ReturnType.CharacterSet != "A" || !cs.ReturnType.IsPercCharset {
		t.Errorf("result character set = %q (%%CHARSET %v), want A%%CHARSET", cs.ReturnType.CharacterSet, cs.ReturnType.IsPercCharset)
	}
}

// parseOne parses sql, which must hold one statement of type T.
func parseOne[T ast.Node](t *testing.T, sql string) T {
	t.Helper()
	result := ParseAndCheck(t, sql)
	stmt, ok := result.Items[0].(*ast.RawStmt).Stmt.(T)
	if !ok {
		t.Fatalf("Parse(%q) = %T", sql, result.Items[0].(*ast.RawStmt).Stmt)
	}
	return stmt
}
