package catalog

import (
	"strings"
	"testing"
)

func execIdentitySQL(t *testing.T, c *Catalog, sql string) {
	t.Helper()
	stmts := parseStmts(t, sql)
	for _, stmt := range stmts {
		if err := c.ProcessUtility(stmt); err != nil {
			t.Fatalf("ProcessUtility(%q): %v", sql, err)
		}
	}
}

func TestAlterAddIdentityCreatesSequenceAndDefault(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `CREATE TABLE t (id integer NOT NULL)`)

	execIdentitySQL(t, c, `ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY`)

	rel := c.GetRelation("", "t")
	if rel == nil {
		t.Fatal("relation t not found")
	}
	col := rel.Columns[rel.colByName["id"]]
	if col.Identity != 'a' {
		t.Fatalf("identity: got %q, want %q", col.Identity, 'a')
	}
	if !col.HasDefault || !strings.Contains(col.Default, "t_id_seq") {
		t.Fatalf("identity default: got HasDefault=%v Default=%q, want nextval on t_id_seq", col.HasDefault, col.Default)
	}

	schema := c.schemaByName["public"]
	seq := schema.Sequences["t_id_seq"]
	if seq == nil {
		t.Fatal("identity sequence public.t_id_seq not found")
	}
	if seq.OwnerRelOID != rel.OID || seq.OwnerAttNum != col.AttNum {
		t.Fatalf("sequence owner: got rel=%d att=%d, want rel=%d att=%d",
			seq.OwnerRelOID, seq.OwnerAttNum, rel.OID, col.AttNum)
	}
	if seq.TypeOID != INT4OID {
		t.Fatalf("sequence type: got %d, want %d", seq.TypeOID, INT4OID)
	}
}

func TestAlterAddIdentityUsesSequenceNameAndOptions(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE SCHEMA s;
		CREATE TABLE s.t (id bigint NOT NULL);
	`)

	execIdentitySQL(t, c, `
		ALTER TABLE s.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
			SEQUENCE NAME s.custom_identity_seq
			START WITH 42
			INCREMENT BY 2
			CACHE 5
		)
	`)

	rel := c.GetRelation("s", "t")
	if rel == nil {
		t.Fatal("relation s.t not found")
	}
	col := rel.Columns[rel.colByName["id"]]
	if col.Identity != 'd' {
		t.Fatalf("identity: got %q, want %q", col.Identity, 'd')
	}
	if !strings.Contains(col.Default, "s.custom_identity_seq") {
		t.Fatalf("identity default: got %q, want nextval on s.custom_identity_seq", col.Default)
	}

	seq := c.schemaByName["s"].Sequences["custom_identity_seq"]
	if seq == nil {
		t.Fatal("identity sequence s.custom_identity_seq not found")
	}
	if seq.TypeOID != INT8OID {
		t.Fatalf("sequence type: got %d, want %d", seq.TypeOID, INT8OID)
	}
	if seq.Start != 42 || seq.Increment != 2 || seq.CacheValue != 5 {
		t.Fatalf("sequence options: got start=%d increment=%d cache=%d, want 42/2/5",
			seq.Start, seq.Increment, seq.CacheValue)
	}
	if seq.OwnerRelOID != rel.OID || seq.OwnerAttNum != col.AttNum {
		t.Fatalf("sequence owner: got rel=%d att=%d, want rel=%d att=%d",
			seq.OwnerRelOID, seq.OwnerAttNum, rel.OID, col.AttNum)
	}
}

func TestCreateTableIdentityUsesSequenceOptions(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE t (
			id smallint GENERATED BY DEFAULT AS IDENTITY (
				START WITH 7
				INCREMENT BY 5
			)
		)
	`)

	rel := c.GetRelation("", "t")
	if rel == nil {
		t.Fatal("relation t not found")
	}
	col := rel.Columns[rel.colByName["id"]]
	if col.Identity != 'd' {
		t.Fatalf("identity: got %q, want %q", col.Identity, 'd')
	}
	if !col.NotNull {
		t.Fatal("identity column should be NOT NULL")
	}

	seq := c.schemaByName["public"].Sequences["t_id_seq"]
	if seq == nil {
		t.Fatal("identity sequence public.t_id_seq not found")
	}
	if seq.TypeOID != INT2OID {
		t.Fatalf("sequence type: got %d, want %d", seq.TypeOID, INT2OID)
	}
	if seq.Start != 7 || seq.Increment != 5 {
		t.Fatalf("sequence options: got start=%d increment=%d, want 7/5", seq.Start, seq.Increment)
	}
}

func TestAlterAddIdentityRequiresNotNull(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `CREATE TABLE t (id integer)`)

	stmts := parseStmts(t, `ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeObjectNotInPrerequisiteState)
}

func TestAlterAddIdentityRejectsExistingDefault(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `CREATE TABLE t (id integer NOT NULL DEFAULT 1)`)

	stmts := parseStmts(t, `ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeObjectNotInPrerequisiteState)
}

func TestAlterAddIdentityAfterSetNotNullInSameStatement(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `CREATE TABLE t (id integer)`)

	execIdentitySQL(t, c, `
		ALTER TABLE t
			ALTER COLUMN id SET NOT NULL,
			ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY
	`)

	rel := c.GetRelation("", "t")
	col := rel.Columns[rel.colByName["id"]]
	if !col.NotNull {
		t.Fatal("expected ALTER SET NOT NULL to run before ADD IDENTITY")
	}
	if col.Identity != 'a' {
		t.Fatalf("identity: got %q, want %q", col.Identity, 'a')
	}
}

func TestAlterAddIdentityRejectsOnlyPartitionedTable(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE pt (bucket integer NOT NULL, id integer NOT NULL)
			PARTITION BY RANGE (bucket);
		CREATE TABLE pt_p1 PARTITION OF pt FOR VALUES FROM (0) TO (10);
	`)

	stmts := parseStmts(t, `
		ALTER TABLE ONLY pt
			ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY
	`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeInvalidTableDefinition)
}

func TestAlterAddIdentityRejectsDirectPartition(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE pt (bucket integer NOT NULL, id integer)
			PARTITION BY RANGE (bucket);
		CREATE TABLE pt_p1 PARTITION OF pt FOR VALUES FROM (0) TO (10);
	`)

	stmts := parseStmts(t, `
		ALTER TABLE pt_p1
			ALTER COLUMN id SET NOT NULL,
			ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY
	`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeInvalidTableDefinition)
}

func TestAlterAddIdentityRecursesToPartitionsInPassOrder(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE pt (bucket integer NOT NULL, id integer)
			PARTITION BY RANGE (bucket);
		CREATE TABLE pt_p1 PARTITION OF pt FOR VALUES FROM (0) TO (10);
	`)

	execIdentitySQL(t, c, `
		ALTER TABLE pt
			ALTER COLUMN id SET NOT NULL,
			ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 3)
	`)

	parent := c.GetRelation("", "pt")
	if parent == nil {
		t.Fatal("relation pt not found")
	}
	parentID := parent.Columns[parent.colByName["id"]]
	if !parentID.NotNull || parentID.Identity != 'a' {
		t.Fatalf("parent id: got NotNull=%v Identity=%q, want true/'a'", parentID.NotNull, parentID.Identity)
	}

	child := c.GetRelation("", "pt_p1")
	if child == nil {
		t.Fatal("relation pt_p1 not found")
	}
	childID := child.Columns[child.colByName["id"]]
	if !childID.NotNull || childID.Identity != 'a' {
		t.Fatalf("child id: got NotNull=%v Identity=%q, want true/'a'", childID.NotNull, childID.Identity)
	}
}

func TestAlterSetIdentityChangesGeneratedAndSequenceOptions(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE t (
			id integer GENERATED ALWAYS AS IDENTITY
		)
	`)

	execIdentitySQL(t, c, `
		ALTER TABLE t ALTER COLUMN id
			SET GENERATED BY DEFAULT
			SET INCREMENT BY 2
			SET CACHE 7
	`)

	rel := c.GetRelation("", "t")
	if rel == nil {
		t.Fatal("relation t not found")
	}
	col := rel.Columns[rel.colByName["id"]]
	if col.Identity != 'd' {
		t.Fatalf("identity: got %q, want %q", col.Identity, 'd')
	}

	seq := c.schemaByName["public"].Sequences["t_id_seq"]
	if seq == nil {
		t.Fatal("identity sequence public.t_id_seq not found")
	}
	if seq.Increment != 2 || seq.CacheValue != 7 {
		t.Fatalf("sequence options: got increment=%d cache=%d, want 2/7", seq.Increment, seq.CacheValue)
	}
}

func TestAlterSetIdentityRequiresIdentityColumn(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `CREATE TABLE t (id integer NOT NULL)`)

	stmts := parseStmts(t, `ALTER TABLE t ALTER COLUMN id SET GENERATED BY DEFAULT`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeObjectNotInPrerequisiteState)
}

func TestAlterSetIdentityRejectsOnlyPartitionedTable(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE pt (bucket integer NOT NULL, id integer NOT NULL)
			PARTITION BY RANGE (bucket);
		CREATE TABLE pt_p1 PARTITION OF pt FOR VALUES FROM (0) TO (10);
		ALTER TABLE pt ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
	`)

	stmts := parseStmts(t, `
		ALTER TABLE ONLY pt
			ALTER COLUMN id SET GENERATED BY DEFAULT
	`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeInvalidTableDefinition)
}

func TestAlterSetIdentityRejectsDirectPartition(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE pt (bucket integer NOT NULL, id integer NOT NULL)
			PARTITION BY RANGE (bucket);
		CREATE TABLE pt_p1 PARTITION OF pt FOR VALUES FROM (0) TO (10);
		ALTER TABLE pt ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
	`)

	stmts := parseStmts(t, `
		ALTER TABLE pt_p1
			ALTER COLUMN id SET GENERATED BY DEFAULT
	`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeInvalidTableDefinition)
}

func TestAlterSetIdentityRecursesToPartitions(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE pt (bucket integer NOT NULL, id integer NOT NULL)
			PARTITION BY RANGE (bucket);
		CREATE TABLE pt_p1 PARTITION OF pt FOR VALUES FROM (0) TO (10);
		ALTER TABLE pt ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
	`)

	execIdentitySQL(t, c, `
		ALTER TABLE pt
			ALTER COLUMN id SET GENERATED BY DEFAULT
			SET INCREMENT BY 3
	`)

	parent := c.GetRelation("", "pt")
	child := c.GetRelation("", "pt_p1")
	if parent == nil || child == nil {
		t.Fatal("partitioned table or child not found")
	}
	parentID := parent.Columns[parent.colByName["id"]]
	childID := child.Columns[child.colByName["id"]]
	if parentID.Identity != 'd' || childID.Identity != 'd' {
		t.Fatalf("identity: got parent=%q child=%q, want both %q", parentID.Identity, childID.Identity, 'd')
	}
	seq := c.schemaByName["public"].Sequences["pt_id_seq"]
	if seq == nil {
		t.Fatal("identity sequence public.pt_id_seq not found")
	}
	if seq.Increment != 3 {
		t.Fatalf("sequence increment: got %d, want 3", seq.Increment)
	}
}

func TestAlterDropIdentityDropsSequenceAndDefault(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `CREATE TABLE t (id integer GENERATED ALWAYS AS IDENTITY)`)

	execIdentitySQL(t, c, `ALTER TABLE t ALTER COLUMN id DROP IDENTITY`)

	rel := c.GetRelation("", "t")
	if rel == nil {
		t.Fatal("relation t not found")
	}
	col := rel.Columns[rel.colByName["id"]]
	if col.Identity != 0 || col.HasDefault || col.Default != "" {
		t.Fatalf("id column: got Identity=%q HasDefault=%v Default=%q, want cleared identity/default",
			col.Identity, col.HasDefault, col.Default)
	}
	if _, err := c.findSequence("", "t_id_seq"); err == nil {
		t.Fatal("expected identity sequence public.t_id_seq to be dropped")
	}
}

func TestAlterDropIdentityRequiresIdentityColumn(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `CREATE TABLE t (id integer NOT NULL)`)

	stmts := parseStmts(t, `ALTER TABLE t ALTER COLUMN id DROP IDENTITY`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeObjectNotInPrerequisiteState)
}

func TestAlterDropIdentityIfExistsSkipsNonIdentityColumn(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `CREATE TABLE t (id integer NOT NULL)`)

	execIdentitySQL(t, c, `ALTER TABLE t ALTER COLUMN id DROP IDENTITY IF EXISTS`)
}

func TestAlterDropIdentityRejectsOnlyPartitionedTable(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE pt (bucket integer NOT NULL, id integer NOT NULL)
			PARTITION BY RANGE (bucket);
		CREATE TABLE pt_p1 PARTITION OF pt FOR VALUES FROM (0) TO (10);
		ALTER TABLE pt ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
	`)

	stmts := parseStmts(t, `
		ALTER TABLE ONLY pt
			ALTER COLUMN id DROP IDENTITY
	`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeInvalidTableDefinition)
}

func TestAlterDropIdentityRejectsDirectPartition(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE pt (bucket integer NOT NULL, id integer NOT NULL)
			PARTITION BY RANGE (bucket);
		CREATE TABLE pt_p1 PARTITION OF pt FOR VALUES FROM (0) TO (10);
		ALTER TABLE pt ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
	`)

	stmts := parseStmts(t, `
		ALTER TABLE pt_p1
			ALTER COLUMN id DROP IDENTITY
	`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeInvalidTableDefinition)
}

func TestAlterDropIdentityRecursesToPartitions(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE pt (bucket integer NOT NULL, id integer NOT NULL)
			PARTITION BY RANGE (bucket);
		CREATE TABLE pt_p1 PARTITION OF pt FOR VALUES FROM (0) TO (10);
		ALTER TABLE pt ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
	`)

	execIdentitySQL(t, c, `ALTER TABLE pt ALTER COLUMN id DROP IDENTITY`)

	parent := c.GetRelation("", "pt")
	child := c.GetRelation("", "pt_p1")
	if parent == nil || child == nil {
		t.Fatal("partitioned table or child not found")
	}
	parentID := parent.Columns[parent.colByName["id"]]
	childID := child.Columns[child.colByName["id"]]
	if parentID.Identity != 0 || childID.Identity != 0 {
		t.Fatalf("identity: got parent=%q child=%q, want both cleared", parentID.Identity, childID.Identity)
	}
	if _, err := c.findSequence("", "pt_id_seq"); err == nil {
		t.Fatal("expected identity sequence public.pt_id_seq to be dropped")
	}
}

func TestAlterAddColumnIdentityCreatesSequenceAndDefault(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `CREATE TABLE t (name text)`)

	execIdentitySQL(t, c, `
		ALTER TABLE t
			ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY (
				START WITH 11
				INCREMENT BY 4
			)
	`)

	rel := c.GetRelation("", "t")
	if rel == nil {
		t.Fatal("relation t not found")
	}
	col := rel.Columns[rel.colByName["id"]]
	if col.Identity != 'd' || !col.NotNull || !col.HasDefault || !strings.Contains(col.Default, "t_id_seq") {
		t.Fatalf("id column: got Identity=%q NotNull=%v HasDefault=%v Default=%q, want identity/default",
			col.Identity, col.NotNull, col.HasDefault, col.Default)
	}

	seq := c.schemaByName["public"].Sequences["t_id_seq"]
	if seq == nil {
		t.Fatal("identity sequence public.t_id_seq not found")
	}
	if seq.Start != 11 || seq.Increment != 4 {
		t.Fatalf("sequence options: got start=%d increment=%d, want 11/4", seq.Start, seq.Increment)
	}
	if seq.OwnerRelOID != rel.OID || seq.OwnerAttNum != col.AttNum {
		t.Fatalf("sequence owner: got rel=%d att=%d, want rel=%d att=%d",
			seq.OwnerRelOID, seq.OwnerAttNum, rel.OID, col.AttNum)
	}
}

func TestAlterAddColumnIdentityRejectsRegularInheritanceChildren(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE parent (name text);
		CREATE TABLE child () INHERITS (parent);
	`)

	stmts := parseStmts(t, `
		ALTER TABLE parent
			ADD COLUMN id integer GENERATED ALWAYS AS IDENTITY
	`)
	err := c.ProcessUtility(stmts[0])
	assertErrorCode(t, err, CodeInvalidTableDefinition)
}

func TestAlterAddColumnIdentityRecursesToPartitions(t *testing.T) {
	c := New()
	execIdentitySQL(t, c, `
		CREATE TABLE pt (bucket integer NOT NULL)
			PARTITION BY RANGE (bucket);
		CREATE TABLE pt_p1 PARTITION OF pt FOR VALUES FROM (0) TO (10);
	`)

	execIdentitySQL(t, c, `
		ALTER TABLE pt
			ADD COLUMN id integer GENERATED ALWAYS AS IDENTITY (START WITH 13)
	`)

	parent := c.GetRelation("", "pt")
	child := c.GetRelation("", "pt_p1")
	if parent == nil || child == nil {
		t.Fatal("partitioned table or child not found")
	}
	parentID := parent.Columns[parent.colByName["id"]]
	childID := child.Columns[child.colByName["id"]]
	if parentID.Identity != 'a' || !parentID.NotNull || !parentID.HasDefault {
		t.Fatalf("parent id: got Identity=%q NotNull=%v HasDefault=%v, want identity/default",
			parentID.Identity, parentID.NotNull, parentID.HasDefault)
	}
	if childID.Identity != 'a' || !childID.NotNull {
		t.Fatalf("child id: got Identity=%q NotNull=%v, want inherited identity", childID.Identity, childID.NotNull)
	}
	if _, exists := c.schemaByName["public"].Sequences["pt_p1_id_seq"]; exists {
		t.Fatal("partition child should not get its own identity sequence")
	}
	seq := c.schemaByName["public"].Sequences["pt_id_seq"]
	if seq == nil {
		t.Fatal("identity sequence public.pt_id_seq not found")
	}
	if seq.Start != 13 {
		t.Fatalf("sequence start: got %d, want 13", seq.Start)
	}
}
