// Code generated by genwalker; DO NOT EDIT.

package ast

// walkChildren walks the child nodes of node, calling Walk(v, child)
// for each child. This function is generated from parsenodes.go.
func walkChildren(v Visitor, node Node) {
	switch n := node.(type) {
	case *AliasedTableRef:
		Walk(v, n.Table)
		walkList(v, n.Columns)
		if n.TableSample != nil {
			Walk(v, n.TableSample)
		}
		walkList(v, n.Hints)
	case *AlterAssemblyStmt:
		walkList(v, n.Actions)
	case *AlterDatabaseStmt:
		walkList(v, n.Options)
		walkList(v, n.FileSpecs)
	case *AlterFederationStmt:
		Walk(v, n.Boundary)
	case *AlterFulltextCatalogStmt:
		walkList(v, n.Options)
	case *AlterFulltextIndexStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Columns)
		walkList(v, n.Options)
	case *AlterIndexStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Options)
	case *AlterMaterializedViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterPartitionFunctionStmt:
		Walk(v, n.BoundaryValue)
	case *AlterSequenceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.RestartWith)
		Walk(v, n.Increment)
		Walk(v, n.MinValue)
		Walk(v, n.MaxValue)
		Walk(v, n.Cache)
	case *AlterServerConfigurationStmt:
		walkList(v, n.Options)
	case *AlterTableAction:
		if n.Column != nil {
			Walk(v, n.Column)
		}
		if n.Constraint != nil {
			Walk(v, n.Constraint)
		}
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		walkList(v, n.Options)
		if n.TargetName != nil {
			Walk(v, n.TargetName)
		}
		walkList(v, n.Names)
		Walk(v, n.Partition)
		Walk(v, n.TargetPart)
	case *AlterTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Actions)
	case *AlterXmlSchemaCollectionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.XmlSchemaNamespaces)
	case *AtTimeZoneExpr:
		Walk(v, n.Expr)
		Walk(v, n.TimeZone)
	case *BackupStmt:
		walkList(v, n.FileSpecs)
		walkList(v, n.Devices)
		walkList(v, n.Options)
	case *BeginEndStmt:
		walkList(v, n.Stmts)
	case *BetweenExpr:
		Walk(v, n.Expr)
		Walk(v, n.Low)
		Walk(v, n.High)
	case *BinaryExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *BulkInsertStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Options)
	case *CaseExpr:
		Walk(v, n.Arg)
		walkList(v, n.WhenList)
		Walk(v, n.ElseExpr)
	case *CaseWhen:
		Walk(v, n.Condition)
		Walk(v, n.Result)
	case *CastExpr:
		Walk(v, n.Expr)
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
	case *CheckpointStmt:
		Walk(v, n.Duration)
	case *CoalesceExpr:
		walkList(v, n.Args)
	case *CollateExpr:
		Walk(v, n.Expr)
	case *ColumnDef:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		if n.Identity != nil {
			Walk(v, n.Identity)
		}
		if n.Computed != nil {
			Walk(v, n.Computed)
		}
		Walk(v, n.DefaultExpr)
		walkList(v, n.Constraints)
		if n.Nullable != nil {
			Walk(v, n.Nullable)
		}
		if n.EncryptedWith != nil {
			Walk(v, n.EncryptedWith)
		}
		if n.GeneratedAlways != nil {
			Walk(v, n.GeneratedAlways)
		}
	case *CommonTableExpr:
		walkList(v, n.Columns)
		Walk(v, n.Query)
	case *ComputedColumnDef:
		Walk(v, n.Expr)
	case *ConstraintDef:
		walkList(v, n.Columns)
		Walk(v, n.Expr)
		if n.RefTable != nil {
			Walk(v, n.RefTable)
		}
		walkList(v, n.RefColumns)
		walkList(v, n.IndexOptions)
		walkList(v, n.EdgeConnections)
	case *ConvertExpr:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		Walk(v, n.Expr)
		Walk(v, n.Style)
	case *CopyIntoColumn:
		Walk(v, n.DefaultValue)
	case *CopyIntoStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.ColumnList)
		walkList(v, n.Sources)
		walkList(v, n.Options)
	case *CreateAggregateStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Params)
		if n.ReturnType != nil {
			Walk(v, n.ReturnType)
		}
	case *CreateAssemblyStmt:
		walkList(v, n.FromFiles)
	case *CreateDatabaseStmt:
		walkList(v, n.OnPrimary)
		walkList(v, n.Filegroups)
		walkList(v, n.LogOn)
		walkList(v, n.WithOptions)
		walkList(v, n.AttachOptions)
		walkList(v, n.Options)
	case *CreateExternalTableAsSelectStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Columns)
		walkList(v, n.Options)
		Walk(v, n.Query)
	case *CreateFederationStmt:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
	case *CreateFulltextCatalogStmt:
		walkList(v, n.Options)
	case *CreateFulltextIndexStmt:
		walkList(v, n.Columns)
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Options)
	case *CreateFunctionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Params)
		if n.ReturnType != nil {
			Walk(v, n.ReturnType)
		}
		if n.ReturnsTable != nil {
			Walk(v, n.ReturnsTable)
		}
		Walk(v, n.Body)
		walkList(v, n.Options)
		walkList(v, n.OrderClause)
	case *CreateIndexStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Columns)
		walkList(v, n.IncludeCols)
		walkList(v, n.OrderCols)
		Walk(v, n.WhereClause)
		walkList(v, n.Options)
	case *CreateJsonIndexStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.ForPaths)
		walkList(v, n.Options)
	case *CreateMaterializedViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.HashColumns)
		Walk(v, n.Query)
	case *CreatePartitionFunctionStmt:
		if n.InputType != nil {
			Walk(v, n.InputType)
		}
		walkList(v, n.Values)
	case *CreatePartitionSchemeStmt:
		walkList(v, n.FileGroups)
	case *CreateProcedureStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Params)
		Walk(v, n.Body)
		walkList(v, n.Options)
	case *CreateRemoteTableAsSelectStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Options)
		Walk(v, n.Query)
	case *CreateSchemaStmt:
		walkList(v, n.Elements)
	case *CreateSelectiveXmlIndexStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Namespaces)
		walkList(v, n.Paths)
		walkList(v, n.Options)
	case *CreateSequenceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		Walk(v, n.Start)
		Walk(v, n.RestartWith)
		Walk(v, n.Increment)
		Walk(v, n.MinValue)
		Walk(v, n.MaxValue)
		Walk(v, n.Cache)
	case *CreateSpatialIndexStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		if n.SpatialColumnRef != nil {
			Walk(v, n.SpatialColumnRef)
		}
		walkList(v, n.Options)
	case *CreateStatisticsStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Columns)
		Walk(v, n.Where)
		walkList(v, n.Options)
	case *CreateSynonymStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Target != nil {
			Walk(v, n.Target)
		}
	case *CreateTableAsSelectStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Columns)
		walkList(v, n.Options)
		Walk(v, n.Query)
	case *CreateTableCloneStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.SourceName != nil {
			Walk(v, n.SourceName)
		}
	case *CreateTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Columns)
		walkList(v, n.Constraints)
		walkList(v, n.Indexes)
		walkList(v, n.TableOptions)
	case *CreateTriggerStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.TriggerOptions)
		walkList(v, n.Events)
		Walk(v, n.Body)
	case *CreateTypeStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.BaseType != nil {
			Walk(v, n.BaseType)
		}
		walkList(v, n.TableDef)
	case *CreateVectorIndexStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Options)
	case *CreateViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Columns)
		Walk(v, n.Query)
		walkList(v, n.Options)
	case *CreateXmlIndexStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Options)
	case *CreateXmlSchemaCollectionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.XmlSchemaNamespaces)
	case *CubeExpr:
		walkList(v, n.Args)
	case *DataType:
		Walk(v, n.Precision)
		Walk(v, n.Scale)
		Walk(v, n.Length)
	case *DatabaseFileSpec:
		if n.Size != nil {
			Walk(v, n.Size)
		}
		if n.MaxSize != nil {
			Walk(v, n.MaxSize)
		}
		if n.FileGrowth != nil {
			Walk(v, n.FileGrowth)
		}
	case *DatabaseFilegroup:
		walkList(v, n.Files)
	case *DbccStmt:
		walkList(v, n.Args)
		walkList(v, n.Options)
	case *DeclareCursorStmt:
		Walk(v, n.Query)
		walkList(v, n.UpdateCols)
	case *DeclareStmt:
		walkList(v, n.Variables)
	case *DeleteStmt:
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
		if n.Top != nil {
			Walk(v, n.Top)
		}
		Walk(v, n.Relation)
		if n.OutputClause != nil {
			Walk(v, n.OutputClause)
		}
		walkList(v, n.FromClause)
		Walk(v, n.WhereClause)
		walkList(v, n.OptionClause)
	case *DropAggregateStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropStatisticsStmt:
		walkList(v, n.Names)
	case *DropStmt:
		walkList(v, n.Names)
		walkList(v, n.OnTables)
		walkList(v, n.Options)
	case *EdgeConnectionDef:
		if n.FromTable != nil {
			Walk(v, n.FromTable)
		}
		if n.ToTable != nil {
			Walk(v, n.ToTable)
		}
	case *EnableDisableTriggerStmt:
		walkList(v, n.Triggers)
		if n.OnObject != nil {
			Walk(v, n.OnObject)
		}
	case *ExecArg:
		Walk(v, n.Value)
	case *ExecStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Args)
		Walk(v, n.ExecString)
		walkList(v, n.WithOptions)
	case *ExistsExpr:
		Walk(v, n.Subquery)
	case *FetchClause:
		Walk(v, n.Count)
	case *FetchCursorStmt:
		Walk(v, n.FetchOffset)
		walkList(v, n.IntoVars)
	case *FullTextPredicate:
		walkList(v, n.Columns)
		if n.PropertyName != nil {
			Walk(v, n.PropertyName)
		}
		Walk(v, n.Value)
		Walk(v, n.LanguageTerm)
	case *FullTextTableRef:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Columns)
		if n.PropertyName != nil {
			Walk(v, n.PropertyName)
		}
		Walk(v, n.SearchCondition)
		Walk(v, n.Language)
		Walk(v, n.TopN)
	case *FuncCallExpr:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Args)
		if n.ReturnType != nil {
			Walk(v, n.ReturnType)
		}
		if n.Over != nil {
			Walk(v, n.Over)
		}
		walkList(v, n.Within)
	case *GrantStmt:
		walkList(v, n.Privileges)
		if n.OnName != nil {
			Walk(v, n.OnName)
		}
		walkList(v, n.Principals)
	case *GroupingSetsExpr:
		walkList(v, n.Sets)
	case *IfStmt:
		Walk(v, n.Condition)
		Walk(v, n.Then)
		Walk(v, n.Else)
	case *IifExpr:
		Walk(v, n.Condition)
		Walk(v, n.TrueVal)
		Walk(v, n.FalseVal)
	case *InExpr:
		Walk(v, n.Expr)
		walkList(v, n.List)
		Walk(v, n.Subquery)
	case *IndexColumn:
		Walk(v, n.Expr)
	case *InlineIndexDef:
		walkList(v, n.Columns)
		walkList(v, n.IncludeCols)
		Walk(v, n.WhereClause)
		walkList(v, n.Options)
	case *InsertBulkColumnDef:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
	case *InsertBulkStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Columns)
		walkList(v, n.Options)
	case *InsertStmt:
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
		if n.Top != nil {
			Walk(v, n.Top)
		}
		Walk(v, n.Relation)
		walkList(v, n.Cols)
		Walk(v, n.Source)
		if n.OutputClause != nil {
			Walk(v, n.OutputClause)
		}
		walkList(v, n.OptionClause)
	case *IsExpr:
		Walk(v, n.Expr)
	case *JoinClause:
		Walk(v, n.Left)
		Walk(v, n.Right)
		Walk(v, n.Condition)
		walkList(v, n.Using)
	case *JsonKeyValueExpr:
		Walk(v, n.Key)
		Walk(v, n.Value)
	case *KillQueryNotificationStmt:
		Walk(v, n.SubscriptionID)
	case *KillStatsJobStmt:
		Walk(v, n.JobID)
	case *KillStmt:
		Walk(v, n.SessionID)
	case *LikeExpr:
		Walk(v, n.Expr)
		Walk(v, n.Pattern)
		Walk(v, n.Escape)
	case *List:
		for _, item := range n.Items {
			Walk(v, item)
		}
	case *MergeInsertAction:
		walkList(v, n.Cols)
		walkList(v, n.Values)
	case *MergeStmt:
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
		if n.Top != nil {
			Walk(v, n.Top)
		}
		Walk(v, n.Target)
		Walk(v, n.Source)
		Walk(v, n.OnCondition)
		walkList(v, n.WhenClauses)
		if n.OutputClause != nil {
			Walk(v, n.OutputClause)
		}
		walkList(v, n.OptionClause)
	case *MergeUpdateAction:
		walkList(v, n.SetClause)
	case *MergeWhenClause:
		Walk(v, n.Condition)
		Walk(v, n.Action)
	case *MethodCallExpr:
		if n.Type != nil {
			Walk(v, n.Type)
		}
		walkList(v, n.Args)
	case *NextValueForExpr:
		if n.Sequence != nil {
			Walk(v, n.Sequence)
		}
		if n.Over != nil {
			Walk(v, n.Over)
		}
	case *NullifExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *OptimizeForParam:
		Walk(v, n.Value)
	case *OrderByItem:
		Walk(v, n.Expr)
	case *OutputClause:
		walkList(v, n.Targets)
		if n.IntoTable != nil {
			Walk(v, n.IntoTable)
		}
		walkList(v, n.IntoCols)
	case *OverClause:
		walkList(v, n.PartitionBy)
		walkList(v, n.OrderBy)
		if n.WindowFrame != nil {
			Walk(v, n.WindowFrame)
		}
	case *ParamDef:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		Walk(v, n.Default)
	case *ParenExpr:
		Walk(v, n.Expr)
	case *ParseExpr:
		Walk(v, n.Expr)
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		Walk(v, n.Culture)
	case *PivotExpr:
		Walk(v, n.Source)
		Walk(v, n.AggFunc)
		walkList(v, n.InValues)
	case *PredictStmt:
		Walk(v, n.Model)
		Walk(v, n.Data)
		walkList(v, n.WithColumns)
	case *PrintStmt:
		Walk(v, n.Expr)
	case *QueryHint:
		Walk(v, n.Value)
		walkList(v, n.Params)
		if n.TableName != nil {
			Walk(v, n.TableName)
		}
		walkList(v, n.TableHints)
	case *RaiseErrorStmt:
		Walk(v, n.Message)
		Walk(v, n.Severity)
		Walk(v, n.State)
		walkList(v, n.Args)
		walkList(v, n.Options)
	case *ReadtextStmt:
		if n.Column != nil {
			Walk(v, n.Column)
		}
		Walk(v, n.TextPtr)
		Walk(v, n.Offset)
		Walk(v, n.Size)
	case *ReceiveColumn:
		Walk(v, n.Expr)
	case *ReceiveStmt:
		Walk(v, n.Top)
		walkList(v, n.Columns)
		if n.Queue != nil {
			Walk(v, n.Queue)
		}
		Walk(v, n.WhereClause)
	case *RenameStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *ResTarget:
		Walk(v, n.Val)
	case *RestoreStmt:
		walkList(v, n.FileSpecs)
		walkList(v, n.Devices)
		walkList(v, n.Options)
	case *ReturnStmt:
		Walk(v, n.Value)
	case *ReturnsTableDef:
		walkList(v, n.Columns)
	case *RollupExpr:
		walkList(v, n.Args)
	case *SecurityKeyStmt:
		walkList(v, n.Options)
	case *SecurityPolicyStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Predicates)
	case *SecurityPredicate:
		if n.Function != nil {
			Walk(v, n.Function)
		}
		walkList(v, n.Args)
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *SecurityStmt:
		walkList(v, n.Options)
		Walk(v, n.WhereClause)
	case *SelectAssign:
		Walk(v, n.Value)
	case *SelectStmt:
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
		if n.Top != nil {
			Walk(v, n.Top)
		}
		walkList(v, n.TargetList)
		if n.IntoTable != nil {
			Walk(v, n.IntoTable)
		}
		walkList(v, n.FromClause)
		Walk(v, n.WhereClause)
		walkList(v, n.GroupByClause)
		Walk(v, n.HavingClause)
		walkList(v, n.WindowClause)
		walkList(v, n.OrderByClause)
		Walk(v, n.OffsetClause)
		if n.FetchClause != nil {
			Walk(v, n.FetchClause)
		}
		if n.ForClause != nil {
			Walk(v, n.ForClause)
		}
		walkList(v, n.OptionClause)
		if n.Larg != nil {
			Walk(v, n.Larg)
		}
		if n.Rarg != nil {
			Walk(v, n.Rarg)
		}
	case *SemanticTableRef:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Columns)
		Walk(v, n.SourceKey)
		if n.MatchedColumn != nil {
			Walk(v, n.MatchedColumn)
		}
		Walk(v, n.MatchedKey)
	case *SensitivityClassificationStmt:
		walkList(v, n.Columns)
		walkList(v, n.Options)
	case *ServiceBrokerStmt:
		walkList(v, n.Options)
	case *SetExpr:
		if n.Column != nil {
			Walk(v, n.Column)
		}
		if n.VarColumn != nil {
			Walk(v, n.VarColumn)
		}
		Walk(v, n.Value)
	case *SetOptionStmt:
		Walk(v, n.Value)
	case *SetStmt:
		Walk(v, n.Value)
	case *SignatureStmt:
		if n.ModuleName != nil {
			Walk(v, n.ModuleName)
		}
		walkList(v, n.CryptoList)
	case *SubqueryComparisonExpr:
		Walk(v, n.Left)
		Walk(v, n.Subquery)
	case *SubqueryExpr:
		Walk(v, n.Query)
	case *TableHint:
		walkList(v, n.IndexValues)
		walkList(v, n.ForceSeekColumns)
		Walk(v, n.IntValue)
	case *TableRef:
		walkList(v, n.Hints)
	case *TableSampleClause:
		Walk(v, n.Size)
		Walk(v, n.Repeatable)
	case *TableTypeIndex:
		Walk(v, n.BucketCount)
		walkList(v, n.Columns)
		walkList(v, n.IncludeCols)
	case *TableVarMethodCallRef:
		for _, item := range n.Args {
			Walk(v, item)
		}
	case *ThrowStmt:
		Walk(v, n.ErrorNumber)
		Walk(v, n.Message)
		Walk(v, n.State)
	case *TopClause:
		Walk(v, n.Count)
	case *TruncateStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Partitions)
	case *TryCastExpr:
		Walk(v, n.Expr)
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
	case *TryCatchStmt:
		walkList(v, n.TryBlock)
		walkList(v, n.CatchBlock)
	case *TryConvertExpr:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		Walk(v, n.Expr)
		Walk(v, n.Style)
	case *UnaryExpr:
		Walk(v, n.Operand)
	case *UnpivotExpr:
		Walk(v, n.Source)
		walkList(v, n.InCols)
	case *UpdateStatisticsStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Names)
		walkList(v, n.Options)
	case *UpdateStmt:
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
		if n.Top != nil {
			Walk(v, n.Top)
		}
		Walk(v, n.Relation)
		walkList(v, n.SetClause)
		if n.OutputClause != nil {
			Walk(v, n.OutputClause)
		}
		walkList(v, n.FromClause)
		Walk(v, n.WhereClause)
		walkList(v, n.OptionClause)
	case *UpdatetextStmt:
		if n.DestColumn != nil {
			Walk(v, n.DestColumn)
		}
		Walk(v, n.DestTextPtr)
		Walk(v, n.InsertOffset)
		Walk(v, n.DeleteLength)
		Walk(v, n.InsertedData)
	case *UseFederationStmt:
		Walk(v, n.Value)
	case *ValuesClause:
		walkList(v, n.Rows)
	case *VariableDecl:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		Walk(v, n.Default)
		walkList(v, n.TableDef)
	case *WaitForStmt:
		Walk(v, n.Value)
		Walk(v, n.InnerStmt)
		Walk(v, n.Timeout)
	case *WhileStmt:
		Walk(v, n.Condition)
		Walk(v, n.Body)
	case *WindowBound:
		Walk(v, n.Offset)
	case *WindowDef:
		walkList(v, n.PartitionBy)
		walkList(v, n.OrderBy)
		if n.Frame != nil {
			Walk(v, n.Frame)
		}
	case *WindowFrame:
		if n.Start != nil {
			Walk(v, n.Start)
		}
		if n.End != nil {
			Walk(v, n.End)
		}
	case *WithClause:
		walkList(v, n.XmlNamespaces)
		walkList(v, n.CTEs)
	case *WritetextStmt:
		if n.Column != nil {
			Walk(v, n.Column)
		}
		Walk(v, n.TextPtr)
		Walk(v, n.Data)
	}
}
