package parser

import "github.com/bytebase/omni/snowflake/ast"

// Special tokens.
const (
	tokEOF     = 0
	tokInvalid = 1 // synthetic error-recovery token; always accompanied by a LexError
)

// Multi-character operators and literal token kinds. Single-character tokens
// (+, -, *, /, %, ~, (, ), [, ], {, }, ,, ;, ., @, :, <, >, =) use the ASCII
// byte value directly as their Type — no constant needed.
const (
	tokInt         = 600 + iota // numeric literal: integer (legacy DECIMAL)
	tokFloat                    // numeric literal: 1.5, 1., .5  (legacy FLOAT)
	tokReal                     // numeric literal: 1.5e10, 1e-10 (legacy REAL)
	tokString                   // 'string' or $$string$$  (legacy STRING / DBL_DOLLAR)
	tokIdent                    // unquoted identifier (preserves source case)
	tokQuotedIdent              // "quoted identifier" (preserves source bytes verbatim)
	tokVariable                 // $name Snowflake script variable (legacy ID2)

	tokDoubleColon // ::  (legacy COLON_COLON)
	tokConcat      // ||  (legacy PIPE_PIPE)
	tokArrow       // ->  (legacy ARROW)
	tokFlow        // ->> (legacy FLOW)
	tokAssoc       // =>  (legacy ASSOC)
	tokNotEq       // != or <> (legacy NE / LTGT — folded into one token)
	tokLessEq      // <=  (legacy LE)
	tokGreaterEq   // >=  (legacy GE)
)

// Token represents a single lexical token.
type Token struct {
	Type    int     // tok* / kw* / ASCII byte value
	Str     string  // identifier text, string content, raw operator text
	Ival    int64   // integer value for tokInt
	Loc     ast.Loc // {Start, End} byte offsets in source text
	XPrefix bool    // true if string was X'...' (binary literal); only set on tokString
}

// Keyword token constants. Values start at 700 and grow with iota.
// Generated from /Users/h3n4l/OpenSource/parser/snowflake/SnowflakeLexer.g4
// via the extraction pipeline in docs/superpowers/plans/2026-04-07-snowflake-lexer.md.
// Numeric values are NOT stable across edits — do not persist them.
const (
	// KEYWORD_CONSTANTS_BEGIN — populated from SnowflakeLexer.g4
	kwABORT = 700 + iota
	kwABORT_DETACHED_QUERY
	kwABORT_STATEMENT
	kwACCESS
	kwACCOUNT
	kwACCOUNTADMIN
	kwACCOUNTS
	kwACTION
	kwADD
	kwADMIN_NAME
	kwADMIN_PASSWORD
	kwAES
	kwAFTER
	kwALERT
	kwALERTS
	kwALL
	kwALLOW_CLIENT_MFA_CACHING
	kwALLOW_DUPLICATE
	kwALLOW_ID_TOKEN
	kwALLOW_OVERLAPPING_EXECUTION
	kwALLOWED_ACCOUNTS
	kwALLOWED_DATABASES
	kwALLOWED_INTEGRATION_TYPES
	kwALLOWED_IP_LIST
	kwALLOWED_SHARES
	kwALLOWED_VALUES
	kwALTER
	kwAND
	kwANY
	kwANY_VALUE
	kwAPI
	kwAPI_ALLOWED_PREFIXES
	kwAPI_AUTHENTICATION
	kwAPI_AWS_ROLE_ARN
	kwAPI_BLOCKED_PREFIXES
	kwAPI_INTEGRATION
	kwAPI_KEY
	kwAPI_PROVIDER
	kwAPPEND
	kwAPPEND_ONLY
	kwAPPLICATION
	kwAPPLY
	kwARRAY
	kwARRAY_AGG
	kwAS
	kwASC
	kwASOF
	kwAT
	kwATTACH
	kwAUTHORIZATION
	kwAUTHORIZATIONS
	kwAUTO
	kwAUTO_COMPRESS
	kwAUTO_DETECT
	kwAUTO_INGEST
	kwAUTO_REFRESH
	kwAUTO_RESUME
	kwAUTO_SUSPEND
	kwAUTOCOMMIT
	kwAUTOCOMMIT_API_SUPPORTED
	kwAUTOINCREMENT
	kwAVG
	kwAVRO
	kwAWS_KEY_ID
	kwAWS_ROLE
	kwAWS_SECRET_KEY
	kwAWS_SNS
	kwAWS_SNS_ROLE_ARN
	kwAWS_SNS_TOPIC
	kwAWS_SNS_TOPIC_ARN
	kwAWS_TOKEN
	kwAZURE
	kwAZURE_AD_APPLICATION_ID
	kwAZURE_EVENT_GRID
	kwAZURE_EVENT_GRID_TOPIC_ENDPOINT
	kwAZURE_SAS_TOKEN
	kwAZURE_STORAGE_QUEUE_PRIMARY_URI
	kwAZURE_TENANT_ID
	kwBASE64
	kwBEFORE
	kwBEGIN
	kwBERNOULLI
	kwBETWEEN
	kwBIGINT
	kwBINARY
	kwBINARY_AS_TEXT
	kwBINARY_FORMAT
	kwBINARY_INPUT_FORMAT
	kwBINARY_OUTPUT_FORMAT
	kwBLOCK
	kwBLOCKED_IP_LIST
	kwBLOCKED_ROLES_LIST
	kwBODY
	kwBOOLEAN
	kwBRANCHES
	kwBROTLI
	kwBUSINESS_CRITICAL
	kwBY
	kwBYTEINT
	kwBZ2
	kwCA
	kwCALL
	kwCALLED
	kwCALLER
	kwCASCADE
	kwCASE
	kwCASE_INSENSITIVE
	kwCASE_SENSITIVE
	kwCAST
	kwCEIL
	kwCHANGE_TRACKING
	kwCHANGES
	kwCHANNELS
	kwCHAR
	kwCHARACTER
	kwCHARINDEX
	kwCHECK
	kwCHECKSUM
	kwCLIENT_ENABLE_LOG_INFO_STATEMENT_PARAMETERS
	kwCLIENT_ENCRYPTION_KEY_SIZE
	kwCLIENT_MEMORY_LIMIT
	kwCLIENT_METADATA_REQUEST_USE_CONNECTION_CTX
	kwCLIENT_METADATA_USE_SESSION_DATABASE
	kwCLIENT_PREFETCH_THREADS
	kwCLIENT_RESULT_CHUNK_SIZE
	kwCLIENT_RESULT_COLUMN_CASE_INSENSITIVE
	kwCLIENT_SESSION_KEEP_ALIVE
	kwCLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY
	kwCLIENT_TIMESTAMP_TYPE_MAPPING
	kwCLONE
	kwCLOUD_PROVIDER_TOKEN
	kwCLUSTER
	kwCLUSTERING
	kwCOALESCE
	kwCOLLATE
	kwCOLLECTION
	kwCOLUMN
	kwCOLUMNS
	kwCOMMENT
	kwCOMMIT
	kwCOMPRESSION
	kwCONCAT
	kwCONCAT_WS
	kwCONDITION
	kwCONFIGURATION
	kwCONNECT
	kwCONNECTION
	kwCONNECTIONS
	kwCONSTRAINT
	kwCONTAINS
	kwCONTEXT_HEADERS
	kwCONTINUE
	kwCOPY
	kwCOPY_OPTIONS
	kwCORTEX
	kwCOUNT
	kwCREATE
	kwCREDENTIALS
	kwCREDIT_QUOTA
	kwCROSS
	kwCSV
	kwCUBE
	kwCURRENT
	kwCURRENT_DATE
	kwCURRENT_TIME
	kwCURRENT_TIMESTAMP
	kwCUSTOM
	kwDAILY
	kwDATA
	kwDATA_RETENTION_TIME_IN_DAYS
	kwDATABASE
	kwDATABASES
	kwDATASET
	kwDATASETS
	kwDATE
	kwDATE_FORMAT
	kwDATE_INPUT_FORMAT
	kwDATE_OUTPUT_FORMAT
	kwDATE_PART
	kwDATEADD
	kwDATEDIFF
	kwDATETIME
	kwDAYS
	kwDAYS_TO_EXPIRY
	kwDECIMAL
	kwDECLARE
	kwDEFAULT
	kwDEFAULT_DDL_COLLATION
	kwDEFAULT_NAMESPACE
	kwDEFAULT_ROLE
	kwDEFAULT_WAREHOUSE
	kwDEFERRABLE
	kwDEFERRED
	kwDEFINE
	kwDEFINITION
	kwDEFLATE
	kwDELEGATED
	kwDELETE
	kwDELTA
	kwDENSE_RANK
	kwDESC
	kwDESCRIBE
	kwDIMENSIONS
	kwDIRECTED
	kwDIRECTION
	kwDIRECTORY
	kwDISABLE
	kwDISABLE_AUTO_CONVERT
	kwDISABLE_SNOWFLAKE_DATA
	kwDISABLED
	kwDISPLAY_NAME
	kwDISTINCT
	kwDO
	kwDOUBLE
	kwDOWNSTREAM
	kwDROP
	kwDUMMY
	kwDYNAMIC
	kwECONOMY
	kwEDITION
	kwELSE
	kwEMAIL
	kwEMPTY
	kwEMPTY_FIELD_AS_NULL
	kwENABLE
	kwENABLE_FOR_PRIVILEGE
	kwENABLE_INTERNAL_STAGES_PRIVATELINK
	kwENABLE_OCTAL
	kwENABLE_QUERY_ACCELERATION
	kwENABLE_UNLOAD_PHYSICAL_TYPE_OPTIMIZATION
	kwENABLED
	kwENCODING
	kwENCRYPTION
	kwEND
	kwEND_TIMESTAMP
	kwENFORCE_LENGTH
	kwENFORCE_SESSION_POLICY
	kwENFORCED
	kwENTERPRISE
	kwEQUAL_NULL
	kwEQUALITY
	kwERROR_INTEGRATION
	kwERROR_ON_COLUMN_COUNT_MISMATCH
	kwERROR_ON_NONDETERMINISTIC_MERGE
	kwERROR_ON_NONDETERMINISTIC_UPDATE
	kwESCAPE
	kwESCAPE_UNENCLOSED_FIELD
	kwEVENT
	kwEXCEPT
	kwEXCHANGE
	kwEXCLUDE
	kwEXECUTION
	kwEXISTS
	kwEXPIRY_DATE
	kwEXPLAIN
	kwEXPR
	kwEXTENSION
	kwEXTERNAL
	kwEXTERNAL_OAUTH
	kwEXTERNAL_OAUTH_ADD_PRIVILEGED_ROLES_TO_BLOCKED_LIST
	kwEXTERNAL_OAUTH_ALLOWED_ROLES_LIST
	kwEXTERNAL_OAUTH_ANY_ROLE_MODE
	kwEXTERNAL_OAUTH_AUDIENCE_LIST
	kwEXTERNAL_OAUTH_BLOCKED_ROLES_LIST
	kwEXTERNAL_OAUTH_ISSUER
	kwEXTERNAL_OAUTH_JWS_KEYS_URL
	kwEXTERNAL_OAUTH_RSA_PUBLIC_KEY
	kwEXTERNAL_OAUTH_RSA_PUBLIC_KEY_2
	kwEXTERNAL_OAUTH_SCOPE_DELIMITER
	kwEXTERNAL_OAUTH_SNOWFLAKE_USER_MAPPING_ATTRIBUTE
	kwEXTERNAL_OAUTH_TOKEN_USER_MAPPING_CLAIM
	kwEXTERNAL_OAUTH_TYPE
	kwEXTERNAL_STAGE
	kwFACTS
	kwFAILOVER
	kwFALSE
	kwFETCH
	kwFIELD_DELIMITER
	kwFIELD_OPTIONALLY_ENCLOSED_BY
	kwFILE
	kwFILE_EXTENSION
	kwFILE_FORMAT
	kwFILES
	kwFIRST
	kwFIRST_NAME
	kwFIRST_VALUE
	kwFLATTEN
	kwFLOAT
	kwFLOAT4
	kwFLOAT8
	kwFLOOR
	kwFOR
	kwFORCE
	kwFOREIGN
	kwFORMAT
	kwFORMAT_NAME
	kwFORMATS
	kwFREQUENCY
	kwFROM
	kwFULL
	kwFUNCTION
	kwFUNCTIONS
	kwFUTURE
	kwGCP_PUBSUB
	kwGCP_PUBSUB_SUBSCRIPTION_NAME
	kwGCP_PUBSUB_TOPIC_NAME
	kwGCS
	kwGENERIC
	kwGENERIC_STRING
	kwGEO
	kwGEOGRAPHY
	kwGEOGRAPHY_OUTPUT_FORMAT
	kwGEOMETRY
	kwGEOMETRY_OUTPUT_FORMAT
	kwGET
	kwGETDATE
	kwGIT
	kwGIT_CREDENTIALS
	kwGLOBAL
	kwGOOGLE_AUDIENCE
	kwGRANT
	kwGRANTS
	kwGROUP
	kwGROUPING
	kwGROUPS
	kwGZIP
	kwHANDLER
	kwHASH
	kwHAVING
	kwHEADER
	kwHEADERS
	kwHEX
	kwHIGH
	kwHISTORY
	kwHOURS
	kwIDENTIFIER
	kwIDENTITY
	kwIF
	kwIFF
	kwIFNULL
	kwIGNORE
	kwIGNORE_UTF8_ERRORS
	kwILIKE
	kwIMMEDIATE
	kwIMMEDIATELY
	kwIMMUTABLE
	kwIMPLICIT
	kwIMPORT
	kwIMPORTED
	kwIMPORTS
	kwIN
	kwINCLUDE
	kwINCREMENT
	kwINCREMENTAL
	kwINDEX
	kwINFORMATION
	kwINITIAL_REPLICATION_SIZE_LIMIT_IN_TB
	kwINITIALIZE
	kwINITIALLY
	kwINITIALLY_SUSPENDED
	kwINNER
	kwINPUT
	kwINSERT
	kwINSERT_ONLY
	kwINT
	kwINTEGER
	kwINTEGRATION
	kwINTEGRATIONS
	kwINTERSECT
	kwINTERVAL
	kwINTO
	kwIS
	kwJAVA
	kwJAVASCRIPT
	kwJDBC_TREAT_DECIMAL_AS_INT
	kwJDBC_TREAT_TIMESTAMP_NTZ_AS_UTC
	kwJDBC_USE_SESSION_TIMEZONE
	kwJOIN
	kwJS_TREAT_INTEGER_AS_BIGINT
	kwJSON
	kwJSON_INDENT
	kwKEY
	kwKEYS
	kwKMS_KEY_ID
	kwLAG
	kwLANGUAGE
	kwLARGE
	kwLAST
	kwLAST_NAME
	kwLAST_QUERY_ID
	kwLAST_VALUE
	kwLATERAL
	kwLEAD
	kwLEFT
	kwLEN
	kwLENGTH
	kwLIKE
	kwLIMIT
	kwLINEAR
	kwLIST
	kwLISTAGG
	kwLISTING
	kwLOCAL
	kwLOCATION
	kwLOCK_TIMEOUT
	kwLOCKS
	kwLOGIN_NAME
	kwLOOKER
	kwLOW
	kwLOWER
	kwLTRIM
	kwLZO
	kwMANAGE
	kwMANAGED
	kwMASKING
	kwMASTER_KEY
	kwMATCH
	kwMATCH_BY_COLUMN_NAME
	kwMATCH_CONDITION
	kwMATCH_RECOGNIZE
	kwMATCHED
	kwMATCHES
	kwMATERIALIZED
	kwMAX_BATCH_ROWS
	kwMAX_CLUSTER_COUNT
	kwMAX_CONCURRENCY_LEVEL
	kwMAX_DATA_EXTENSION_TIME_IN_DAYS
	kwMAX_SIZE
	kwMEASURES
	kwMEDIUM
	kwMEMOIZABLE
	kwMERGE
	kwMETADATA
	kwMETRIC
	kwMETRICS
	kwMIDDLE_NAME
	kwMIN
	kwMIN_CLUSTER_COUNT
	kwMIN_DATA_RETENTION_TIME_IN_DAYS
	kwMINS_TO_BYPASS_MFA
	kwMINS_TO_UNLOCK
	kwMINUS
	kwMODE
	kwMODIFIED_AFTER
	kwMODIFY
	kwMONITOR
	kwMONITORS
	kwMONTHLY
	kwMOVE
	kwMULTI_STATEMENT_COUNT
	kwMUST_CHANGE_PASSWORD
	kwNAME
	kwNATURAL
	kwNCHAR
	kwNETWORK
	kwNETWORK_POLICY
	kwNEVER
	kwNEXT
	kwNEXTVAL
	kwNO
	kwNONE
	kwNOORDER
	kwNORELY
	kwNOT
	kwNOTIFICATION
	kwNOTIFICATION_INTEGRATION
	kwNOTIFICATION_PROVIDER
	kwNOTIFY
	kwNOTIFY_USERS
	kwNOVALIDATE
	kwNTILE
	kwNULL
	kwNULL_IF
	kwNULLIF
	kwNULLS
	kwNUMBER
	kwNUMERIC
	kwNVARCHAR
	kwNVARCHAR2
	kwNVL
	kwNVL2
	kwOAUTH
	kwOAUTH_ALLOW_NON_TLS_REDIRECT_URI
	kwOAUTH_CLIENT
	kwOAUTH_CLIENT_RSA_PUBLIC_KEY
	kwOAUTH_CLIENT_RSA_PUBLIC_KEY_2
	kwOAUTH_ENFORCE_PKCE
	kwOAUTH_ISSUE_REFRESH_TOKENS
	kwOAUTH_REDIRECT_URI
	kwOAUTH_REFRESH_TOKEN
	kwOAUTH_REFRESH_TOKEN_EXPIRY_TIME
	kwOAUTH_REFRESH_TOKEN_VALIDITY
	kwOAUTH_SCOPES
	kwOAUTH_USE_SECONDARY_ROLES
	kwOAUTH2
	kwOBJECT
	kwOBJECT_TYPES
	kwOBJECTS
	kwOF
	kwOFFSET
	kwOKTA
	kwOLD
	kwOMIT
	kwON
	kwON_CREATE
	kwON_ERROR
	kwON_SCHEDULE
	kwONE
	kwONLY
	kwOPERATE
	kwOPTIMIZATION
	kwOPTION
	kwOR
	kwORC
	kwORDER
	kwORGADMIN
	kwORGANIZATION
	kwORIGIN
	kwOUTBOUND
	kwOUTER
	kwOVER
	kwOVERRIDE
	kwOVERWRITE
	kwOWNER
	kwOWNERSHIP
	kwPACKAGE
	kwPACKAGES
	kwPARALLEL
	kwPARAMETERS
	kwPARQUET
	kwPARTIAL
	kwPARTITION
	kwPARTITION_TYPE
	kwPASSWORD
	kwPASSWORD_HISTORY
	kwPASSWORD_LOCKOUT_TIME_MINS
	kwPASSWORD_MAX_AGE_DAYS
	kwPASSWORD_MAX_LENGTH
	kwPASSWORD_MAX_RETRIES
	kwPASSWORD_MIN_AGE_DAYS
	kwPASSWORD_MIN_LENGTH
	kwPASSWORD_MIN_LOWER_CASE_CHARS
	kwPASSWORD_MIN_NUMERIC_CHARS
	kwPASSWORD_MIN_SPECIAL_CHARS
	kwPASSWORD_MIN_UPPER_CASE_CHARS
	kwPAST
	kwPATH
	kwPATTERN
	kwPER
	kwPERCENT
	kwPERIODIC_DATA_REKEYING
	kwPING_FEDERATE
	kwPIPE
	kwPIPE_EXECUTION_PAUSED
	kwPIPES
	kwPIVOT
	kwPOLICIES
	kwPOLICY
	kwPORT
	kwPRE_AUTHORIZED_ROLES_LIST
	kwPREFIX
	kwPRESERVE_SPACE
	kwPREVENT_UNLOAD_TO_INLINE_URL
	kwPREVENT_UNLOAD_TO_INTERNAL_STAGES
	kwPRIMARY
	kwPRIOR
	kwPRIORITY
	kwPRIVATE
	kwPRIVILEGES
	kwPROCEDURE
	kwPROCEDURE_NAME
	kwPROCEDURES
	kwPROPERTY
	kwPROVIDER
	kwPUBLIC
	kwPURGE
	kwPUT
	kwPYTHON
	kwQUALIFY
	kwQUARTER
	kwQUERIES
	kwQUERY
	kwQUERY_ACCELERATION_MAX_SCALE_FACTOR
	kwQUERY_TAG
	kwQUEUE
	kwQUOTED_IDENTIFIERS_IGNORE_CASE
	kwRANK
	kwRAW_DEFLATE
	kwREAD
	kwREADER
	kwREAL
	kwRECLUSTER
	kwRECORD_DELIMITER
	kwRECURSIVE
	kwREFERENCE_USAGE
	kwREFERENCES
	kwREFRESH
	kwREFRESH_MODE
	kwREFRESH_ON_CREATE
	kwREGION
	kwREGION_GROUP
	kwREGIONS
	kwRELATIONSHIPS
	kwRELY
	kwREMOVE
	kwRENAME
	kwREPEATABLE
	kwREPLACE
	kwREPLACE_INVALID_CHARACTERS
	kwREPLICA
	kwREPLICATION
	kwREPLICATION_SCHEDULE
	kwREPOSITORIES
	kwREPOSITORY
	kwREQUEST_TRANSLATOR
	kwREQUIRE_STORAGE_INTEGRATION_FOR_STAGE_CREATION
	kwREQUIRE_STORAGE_INTEGRATION_FOR_STAGE_OPERATION
	kwRESET
	kwRESOURCE
	kwRESOURCE_MONITOR
	kwRESOURCES
	kwRESPECT
	kwRESPONSE_TRANSLATOR
	kwRESTRICT
	kwRESTRICTIONS
	kwRESULT
	kwRESUME
	kwRETRY
	kwRETURN
	kwRETURN_ALL_ERRORS
	kwRETURN_ERRORS
	kwRETURN_FAILED_ONLY
	kwRETURN_ROWS
	kwRETURNS
	kwREVOKE
	kwRIGHT
	kwRLIKE
	kwROLE
	kwROLES
	kwROLLBACK
	kwROLLUP
	kwROUND
	kwROUNDING_MODE
	kwROW
	kwROW_NUMBER
	kwROWS
	kwROWS_PER_RESULTSET
	kwRSA_PUBLIC_KEY
	kwRSA_PUBLIC_KEY_2
	kwRTRIM
	kwRUN_AS_ROLE
	kwRUNTIME_VERSION
	kwSAML_IDENTITY_PROVIDER
	kwSAML2
	kwSAML2_ENABLE_SP_INITIATED
	kwSAML2_FORCE_AUTHN
	kwSAML2_ISSUER
	kwSAML2_POST_LOGOUT_REDIRECT_URL
	kwSAML2_PROVIDER
	kwSAML2_REQUESTED_NAMEID_FORMAT
	kwSAML2_SIGN_REQUEST
	kwSAML2_SNOWFLAKE_ACS_URL
	kwSAML2_SNOWFLAKE_ISSUER_URL
	kwSAML2_SNOWFLAKE_X509_CERT
	kwSAML2_SP_INITIATED_LOGIN_PAGE_LABEL
	kwSAML2_SSO_URL
	kwSAML2_X509_CERT
	kwSAMPLE
	kwSAVE_OLD_URL
	kwSCALE
	kwSCALING_POLICY
	kwSCHEDULE
	kwSCHEMA
	kwSCHEMAS
	kwSCIM
	kwSCIM_CLIENT
	kwSEARCH
	kwSECONDARY
	kwSECRET
	kwSECRET_STRING
	kwSECRETS
	kwSECURE
	kwSECURITY
	kwSECURITYADMIN
	kwSEED
	kwSELECT
	kwSEMANTIC
	kwSEQUENCE
	kwSEQUENCES
	kwSERVICE
	kwSESSION
	kwSESSION_IDLE_TIMEOUT_MINS
	kwSESSION_POLICY
	kwSESSION_UI_IDLE_TIMEOUT_MINS
	kwSET
	kwSETS
	kwSHARE
	kwSHARE_RESTRICTIONS
	kwSHARES
	kwSHOW
	kwSHOW_INITIAL_ROWS
	kwSIMPLE
	kwSIMULATED_DATA_SHARING_CONSUMER
	kwSIZE_LIMIT
	kwSKIP
	kwSKIP_BLANK_LINES
	kwSKIP_BYTE_ORDER_MARK
	kwSKIP_FILE
	kwSKIP_HEADER
	kwSMALL
	kwSMALLINT
	kwSNAPPY
	kwSNAPPY_COMPRESSION
	kwSNOWFLAKE_FULL
	kwSNOWFLAKE_SSE
	kwSOME
	kwSOURCE
	kwSOURCE_COMPRESSION
	kwSPLIT
	kwSPLIT_PART
	kwSPLIT_TO_TABLE
	kwSQL
	kwSSO_LOGIN_PAGE
	kwSTAGE
	kwSTAGE_COPY_OPTIONS
	kwSTAGE_FILE_FORMAT
	kwSTAGES
	kwSTANDARD
	kwSTART
	kwSTART_DATE
	kwSTART_TIMESTAMP
	kwSTARTS
	kwSTATE
	kwSTATEMENT
	kwSTATEMENT_QUEUED_TIMEOUT_IN_SECONDS
	kwSTATEMENT_TIMEOUT_IN_SECONDS
	kwSTATS
	kwSTATUS
	kwSTORAGE
	kwSTORAGE_ALLOWED_LOCATIONS
	kwSTORAGE_AWS_OBJECT_ACL
	kwSTORAGE_AWS_ROLE_ARN
	kwSTORAGE_BLOCKED_LOCATIONS
	kwSTORAGE_INTEGRATION
	kwSTORAGE_PROVIDER
	kwSTREAM
	kwSTREAMS
	kwSTRICT
	kwSTRICT_JSON_OUTPUT
	kwSTRING
	kwSTRIP_NULL_VALUES
	kwSTRIP_OUTER_ARRAY
	kwSTRIP_OUTER_ELEMENT
	kwSUBSTR
	kwSUBSTRING
	kwSUM
	kwSUSPEND
	kwSUSPEND_IMMEDIATE
	kwSUSPEND_TASK_AFTER_NUM_FAILURES
	kwSUSPENDED
	kwSWAP
	kwSYMMETRIC_KEY
	kwSYNC_PASSWORD
	kwSYNONYMS
	kwSYSADMIN
	kwSYSTEM
	kwTABLE
	kwTABLE_FORMAT
	kwTABLEAU_DESKTOP
	kwTABLEAU_SERVER
	kwTABLES
	kwTABLESAMPLE
	kwTABULAR
	kwTAG
	kwTAGS
	kwTARGET_LAG
	kwTASK
	kwTASKS
	kwTEMP
	kwTEMPORARY
	kwTERSE
	kwTEXT
	kwTHEN
	kwTIME
	kwTIME_FORMAT
	kwTIME_INPUT_FORMAT
	kwTIME_OUTPUT_FORMAT
	kwTIMEADD
	kwTIMEDIFF
	kwTIMESTAMP
	kwTIMESTAMP_LTZ
	kwTIMESTAMP_NTZ
	kwTIMESTAMP_TZ
	kwTIMESTAMP_DAY_IS_ALWAYS_24H
	kwTIMESTAMP_FORMAT
	kwTIMESTAMP_INPUT_FORMAT
	kwTIMESTAMP_LTZ_OUTPUT_FORMAT
	kwTIMESTAMP_NTZ_OUTPUT_FORMAT
	kwTIMESTAMP_OUTPUT_FORMAT
	kwTIMESTAMP_TYPE_MAPPING
	kwTIMESTAMP_TZ_OUTPUT_FORMAT
	kwTIMESTAMPADD
	kwTIMESTAMPDIFF
	kwTIMEZONE
	kwTINYINT
	kwTO
	kwTO_BOOLEAN
	kwTO_DATE
	kwTO_TIMESTAMP
	kwTOP
	kwTRANSACTION
	kwTRANSACTION_ABORT_ON_ERROR
	kwTRANSACTION_DEFAULT_ISOLATION_LEVEL
	kwTRANSACTIONS
	kwTRANSIENT
	kwTRIGGERS
	kwTRIM
	kwTRIM_SPACE
	kwTRUE
	kwTRUNC
	kwTRUNCATE
	kwTRUNCATECOLUMNS
	kwTRY_CAST
	kwTWO_DIGIT_CENTURY_START
	kwTYPE
	kwUNDROP
	kwUNION
	kwUNIQUE
	kwUNMATCHED
	kwUNPIVOT
	kwUNSET
	kwUNSUPPORTED_DDL_ACTION
	kwUPDATE
	kwUPPER
	kwURL
	kwUSAGE
	kwUSE
	kwUSE_ANY_ROLE
	kwUSE_CACHED_RESULT
	kwUSER
	kwUSER_SPECIFIED
	kwUSER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE
	kwUSER_TASK_TIMEOUT_MS
	kwUSERADMIN
	kwUSERNAME
	kwUSERS
	kwUSING
	kwUTF8
	kwVALIDATE
	kwVALIDATION_MODE
	kwVALUE
	kwVALUES
	kwVARBINARY
	kwVARCHAR
	kwVARIABLES
	kwVARIANT
	kwVECTOR
	kwVERSION
	kwVERSIONS
	kwVIEW
	kwVIEWS
	kwVISIBILITY
	kwVOLATILE
	kwWAREHOUSE
	kwWAREHOUSE_SIZE
	kwWAREHOUSE_TYPE
	kwWAREHOUSES
	kwWEEK_OF_YEAR_POLICY
	kwWEEK_START
	kwWEEKLY
	kwWHEN
	kwWHERE
	kwWITH
	kwWITHIN
	kwWORK
	kwWRITE
	kwX4LARGE
	kwX5LARGE
	kwX6LARGE
	kwXLARGE
	kwXML
	kwXSMALL
	kwXXLARGE
	kwXXXLARGE
	kwYEAR
	kwYEARLY
	kwZSTD
	// KEYWORD_CONSTANTS_END
)

// TokenName returns a human-readable name for a token type. Used by tests
// and debug output.
//
// Returns:
//   - "EOF" for tokEOF
//   - "INVALID" for tokInvalid
//   - the upper-case keyword name (e.g. "SELECT") for kw* constants
//   - the constant name minus the "tok" prefix (e.g. "INT", "STRING") for tok* constants
//   - the literal character in quotes (e.g. "'+'") for ASCII single-char tokens
func TokenName(t int) string {
	switch t {
	case tokEOF:
		return "EOF"
	case tokInvalid:
		return "INVALID"
	case tokInt:
		return "INT"
	case tokFloat:
		return "FLOAT"
	case tokReal:
		return "REAL"
	case tokString:
		return "STRING"
	case tokIdent:
		return "IDENT"
	case tokQuotedIdent:
		return "QUOTED_IDENT"
	case tokVariable:
		return "VARIABLE"
	case tokDoubleColon:
		return "::"
	case tokConcat:
		return "||"
	case tokArrow:
		return "->"
	case tokFlow:
		return "->>"
	case tokAssoc:
		return "=>"
	case tokNotEq:
		return "!="
	case tokLessEq:
		return "<="
	case tokGreaterEq:
		return ">="
	}
	if t >= 700 {
		// Keyword token — look up by reverse-mapping the keywordMap. The
		// inverse map is built lazily by keywords.go's keywordName helper.
		if name, ok := keywordName(t); ok {
			return name
		}
		return "UNKNOWN_KEYWORD"
	}
	if t > 0 && t < 128 {
		// ASCII single-char token
		return "'" + string(rune(t)) + "'"
	}
	return "UNKNOWN"
}
