// Code generated by genwalker; DO NOT EDIT.

package ast

// walkChildren walks the child nodes of node, calling Walk(v, child)
// for each child. This function is generated from parsenodes.go and node.go.
func walkChildren(v Visitor, node Node) {
	switch n := node.(type) {
	case *AccessExpr:
		Walk(v, n.Expr)
		Walk(v, n.Index)
	case *AlterAccountStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.PolicyName != nil {
			Walk(v, n.PolicyName)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterAlertStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.Condition)
		Walk(v, n.ActionBody)
	case *AlterDatabaseStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterDynamicTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
		walkNodes(v, n.ClusterBy)
	case *AlterExternalTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterFileFormatStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterIntegrationStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterMaterializedViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
		walkNodes(v, n.ClusterBy)
	case *AlterPipeStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterPolicyStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
		Walk(v, n.Body)
	case *AlterReplicationGroupStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
		if n.MoveTo != nil {
			Walk(v, n.MoveTo)
		}
	case *AlterRoleStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterRoutineStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterSchemaStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterSemanticViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterSequenceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterShareStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterStageStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterStreamStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterTagStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterTaskStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.When)
		Walk(v, n.Body)
	case *AlterUserStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
		if n.PolicyName != nil {
			Walk(v, n.PolicyName)
		}
		if n.MaskingPolicy != nil {
			Walk(v, n.MaskingPolicy)
		}
	case *ArrayLiteralExpr:
		walkNodes(v, n.Elements)
	case *BetweenExpr:
		Walk(v, n.Expr)
		Walk(v, n.Low)
		Walk(v, n.High)
	case *BinaryExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *CallArg:
		Walk(v, n.Value)
	case *CallStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkNodes(v, n.Args)
	case *CaseExpr:
		Walk(v, n.Operand)
		Walk(v, n.Else)
	case *CastExpr:
		Walk(v, n.Expr)
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
	case *ChangesClause:
		if n.Start != nil {
			Walk(v, n.Start)
		}
		if n.End != nil {
			Walk(v, n.End)
		}
	case *CollateExpr:
		Walk(v, n.Expr)
	case *ColumnDef:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		Walk(v, n.Default)
		if n.MaskingPolicy != nil {
			Walk(v, n.MaskingPolicy)
		}
		Walk(v, n.VirtualExpr)
	case *CommentStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Column != nil {
			Walk(v, n.Column)
		}
	case *ConnectionReplica:
		if n.Source != nil {
			Walk(v, n.Source)
		}
	case *CopyIntoLocationStmt:
		if n.Into != nil {
			Walk(v, n.Into)
		}
		if n.FromTable != nil {
			Walk(v, n.FromTable)
		}
		Walk(v, n.FromQuery)
		Walk(v, n.Partition)
	case *CopyIntoTableStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		if n.From != nil {
			Walk(v, n.From)
		}
		if n.Transform != nil {
			Walk(v, n.Transform)
		}
	case *CopyOption:
		if n.Lit != nil {
			Walk(v, n.Lit)
		}
	case *CreateAccountStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateAlertStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.Condition)
		Walk(v, n.Action)
	case *CreateDatabaseStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateDatasetStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateDynamicTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkNodes(v, n.ClusterBy)
		Walk(v, n.ImmutableWhere)
		Walk(v, n.AsQuery)
		Walk(v, n.RefreshUsing)
	case *CreateEventTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkNodes(v, n.ClusterBy)
	case *CreateExternalTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.UsingTemplate)
		walkNodes(v, n.PartitionBy)
		if n.Location != nil {
			Walk(v, n.Location)
		}
	case *CreateFileFormatStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateIntegrationStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Replica != nil {
			Walk(v, n.Replica)
		}
	case *CreateMaterializedViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkNodes(v, n.ClusterBy)
		Walk(v, n.Query)
	case *CreatePipeStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.Copy)
	case *CreatePolicyStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Returns != nil {
			Walk(v, n.Returns)
		}
		Walk(v, n.Body)
	case *CreateReplicationGroupStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Replica != nil {
			Walk(v, n.Replica)
		}
	case *CreateRoleStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateRoutineStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.ReturnType != nil {
			Walk(v, n.ReturnType)
		}
	case *CreateSchemaStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateSemanticViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateSequenceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateShareStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateStageStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateStreamStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Source != nil {
			Walk(v, n.Source)
		}
		if n.Clone != nil {
			Walk(v, n.Clone)
		}
	case *CreateTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkNodes(v, n.ClusterBy)
		Walk(v, n.AsSelect)
		if n.Like != nil {
			Walk(v, n.Like)
		}
	case *CreateTagStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateTaskStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.When)
		Walk(v, n.Body)
		if n.Clone != nil {
			Walk(v, n.Clone)
		}
	case *CreateUserStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.Query)
	case *DeleteStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		walkNodes(v, n.Using)
		Walk(v, n.Where)
	case *DescribeStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NameLiteral != nil {
			Walk(v, n.NameLiteral)
		}
	case *DollarRef:
		if n.Qualifier != nil {
			Walk(v, n.Qualifier)
		}
	case *DropDatabaseStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropSchemaStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *ExecuteTaskStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *ExistsExpr:
		Walk(v, n.Query)
	case *ExplainStmt:
		Walk(v, n.Stmt)
	case *ExternalColumnDef:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		Walk(v, n.Expr)
	case *File:
		walkNodes(v, n.Stmts)
	case *FuncCallExpr:
		walkNodes(v, n.Args)
	case *GetStmt:
		if n.Stage != nil {
			Walk(v, n.Stage)
		}
		if n.Target != nil {
			Walk(v, n.Target)
		}
	case *GrantStmt:
		if n.Role != nil {
			Walk(v, n.Role)
		}
		if n.On != nil {
			Walk(v, n.On)
		}
		if n.Grantee != nil {
			Walk(v, n.Grantee)
		}
	case *GrantTarget:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.ContainerName != nil {
			Walk(v, n.ContainerName)
		}
	case *Grantee:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *GroupOption:
		if n.Lit != nil {
			Walk(v, n.Lit)
		}
	case *IffExpr:
		Walk(v, n.Cond)
		Walk(v, n.Then)
		Walk(v, n.Else)
	case *InExpr:
		Walk(v, n.Expr)
		walkNodes(v, n.Values)
	case *InsertMultiStmt:
		Walk(v, n.Select)
	case *InsertStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		Walk(v, n.Select)
	case *IsExpr:
		Walk(v, n.Expr)
		Walk(v, n.DistinctFrom)
	case *JoinExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
		Walk(v, n.On)
		Walk(v, n.MatchCondition)
	case *LambdaExpr:
		Walk(v, n.Body)
	case *LikeExpr:
		Walk(v, n.Expr)
		Walk(v, n.Pattern)
		Walk(v, n.Escape)
		walkNodes(v, n.AnyValues)
	case *ListStmt:
		if n.Stage != nil {
			Walk(v, n.Stage)
		}
		if n.Pattern != nil {
			Walk(v, n.Pattern)
		}
	case *MatchDefine:
		Walk(v, n.Cond)
	case *MatchMeasure:
		Walk(v, n.Expr)
	case *MatchRecognizeClause:
		walkNodes(v, n.PartitionBy)
		if n.RowsPerMatch != nil {
			Walk(v, n.RowsPerMatch)
		}
		if n.AfterMatch != nil {
			Walk(v, n.AfterMatch)
		}
		if n.Pattern != nil {
			Walk(v, n.Pattern)
		}
	case *MergeStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		Walk(v, n.Source)
		Walk(v, n.On)
	case *ParenExpr:
		Walk(v, n.Expr)
	case *PivotClause:
		if n.Agg != nil {
			Walk(v, n.Agg)
		}
		if n.ForColumn != nil {
			Walk(v, n.ForColumn)
		}
		if n.In != nil {
			Walk(v, n.In)
		}
		Walk(v, n.DefaultVal)
	case *PivotInClause:
		Walk(v, n.Subquery)
	case *PivotValue:
		Walk(v, n.Value)
	case *PolicyArg:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
	case *PutStmt:
		if n.File != nil {
			Walk(v, n.File)
		}
		if n.Stage != nil {
			Walk(v, n.Stage)
		}
	case *RemoveStmt:
		if n.Stage != nil {
			Walk(v, n.Stage)
		}
		if n.Pattern != nil {
			Walk(v, n.Pattern)
		}
	case *RevokeStmt:
		if n.On != nil {
			Walk(v, n.On)
		}
		if n.Role != nil {
			Walk(v, n.Role)
		}
		if n.Grantee != nil {
			Walk(v, n.Grantee)
		}
	case *SampleClause:
		Walk(v, n.Quantity)
		Walk(v, n.Seed)
	case *ScriptAssignStmt:
		Walk(v, n.Value)
	case *ScriptBlockStmt:
		walkNodes(v, n.Decls)
		walkNodes(v, n.Body)
		walkNodes(v, n.Handlers)
	case *ScriptCaseStmt:
		Walk(v, n.Operand)
		walkNodes(v, n.Whens)
		walkNodes(v, n.Else)
	case *ScriptCaseWhen:
		Walk(v, n.Match)
		walkNodes(v, n.Body)
	case *ScriptDeclaration:
		if n.Type != nil {
			Walk(v, n.Type)
		}
		Walk(v, n.Default)
		Walk(v, n.Query)
		walkNodes(v, n.ExcArgs)
	case *ScriptExceptionHandler:
		walkNodes(v, n.Body)
	case *ScriptForStmt:
		Walk(v, n.Start)
		Walk(v, n.End)
		walkNodes(v, n.Body)
	case *ScriptIfBranch:
		Walk(v, n.Cond)
		walkNodes(v, n.Body)
	case *ScriptIfStmt:
		walkNodes(v, n.Branches)
		walkNodes(v, n.Else)
	case *ScriptLetStmt:
		if n.Type != nil {
			Walk(v, n.Type)
		}
		Walk(v, n.Default)
		Walk(v, n.Query)
	case *ScriptLoopStmt:
		walkNodes(v, n.Body)
	case *ScriptOpenStmt:
		walkNodes(v, n.Using)
	case *ScriptRepeatStmt:
		walkNodes(v, n.Body)
		Walk(v, n.Cond)
	case *ScriptReturnStmt:
		Walk(v, n.Value)
	case *ScriptWhileStmt:
		Walk(v, n.Cond)
		walkNodes(v, n.Body)
	case *SelectStmt:
		Walk(v, n.Top)
		walkNodes(v, n.From)
		Walk(v, n.Where)
		Walk(v, n.Having)
		Walk(v, n.Qualify)
		Walk(v, n.StartWith)
		walkNodes(v, n.ConnectBy)
		Walk(v, n.Limit)
		Walk(v, n.Offset)
	case *SetOperationStmt:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *ShowStmt:
		if n.ScopeName != nil {
			Walk(v, n.ScopeName)
		}
		if n.GrantsOn != nil {
			Walk(v, n.GrantsOn)
		}
		if n.GrantsTo != nil {
			Walk(v, n.GrantsTo)
		}
		Walk(v, n.Pipe)
	case *StarExpr:
		if n.Qualifier != nil {
			Walk(v, n.Qualifier)
		}
	case *SubqueryExpr:
		Walk(v, n.Query)
	case *TableRef:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.Subquery)
		if n.FuncCall != nil {
			Walk(v, n.FuncCall)
		}
		if n.TimeTravel != nil {
			Walk(v, n.TimeTravel)
		}
		if n.Changes != nil {
			Walk(v, n.Changes)
		}
		if n.MatchRecognize != nil {
			Walk(v, n.MatchRecognize)
		}
		if n.Pivot != nil {
			Walk(v, n.Pivot)
		}
		if n.Unpivot != nil {
			Walk(v, n.Unpivot)
		}
		if n.Sample != nil {
			Walk(v, n.Sample)
		}
	case *TimeTravelClause:
		Walk(v, n.Expr)
	case *TruncateStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *TypeName:
		if n.ElementType != nil {
			Walk(v, n.ElementType)
		}
	case *UnaryExpr:
		Walk(v, n.Expr)
	case *UndropDatabaseStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *UndropSchemaStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *UndropStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *UpdateStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		walkNodes(v, n.From)
		Walk(v, n.Where)
	case *UseStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	}
}
