// Code generated by genwalker; DO NOT EDIT.

package ast

// walkChildren walks the child nodes of node, calling Walk(v, child)
// for each child. This function is generated from parsenodes.go and node.go.
func walkChildren(v Visitor, node Node) {
	switch n := node.(type) {
	case *AccessExpr:
		Walk(v, n.Expr)
		Walk(v, n.Index)
	case *AlterDatabaseStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterMaterializedViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
		walkNodes(v, n.ClusterBy)
	case *AlterSchemaStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
		if n.PolicyName != nil {
			Walk(v, n.PolicyName)
		}
		if n.MaskingPolicy != nil {
			Walk(v, n.MaskingPolicy)
		}
	case *ArrayLiteralExpr:
		walkNodes(v, n.Elements)
	case *BetweenExpr:
		Walk(v, n.Expr)
		Walk(v, n.Low)
		Walk(v, n.High)
	case *BinaryExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *CaseExpr:
		Walk(v, n.Operand)
		Walk(v, n.Else)
	case *CastExpr:
		Walk(v, n.Expr)
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
	case *CollateExpr:
		Walk(v, n.Expr)
	case *ColumnDef:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		Walk(v, n.Default)
		if n.MaskingPolicy != nil {
			Walk(v, n.MaskingPolicy)
		}
		Walk(v, n.VirtualExpr)
	case *CreateDatabaseStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateMaterializedViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkNodes(v, n.ClusterBy)
		Walk(v, n.Query)
	case *CreateSchemaStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkNodes(v, n.ClusterBy)
		Walk(v, n.AsSelect)
		if n.Like != nil {
			Walk(v, n.Like)
		}
	case *CreateViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.Query)
	case *DeleteStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		walkNodes(v, n.Using)
		Walk(v, n.Where)
	case *DropDatabaseStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropSchemaStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *ExistsExpr:
		Walk(v, n.Query)
	case *File:
		walkNodes(v, n.Stmts)
	case *FuncCallExpr:
		walkNodes(v, n.Args)
	case *IffExpr:
		Walk(v, n.Cond)
		Walk(v, n.Then)
		Walk(v, n.Else)
	case *InExpr:
		Walk(v, n.Expr)
		walkNodes(v, n.Values)
	case *InsertMultiStmt:
		Walk(v, n.Select)
	case *InsertStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		Walk(v, n.Select)
	case *IsExpr:
		Walk(v, n.Expr)
		Walk(v, n.DistinctFrom)
	case *JoinExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
		Walk(v, n.On)
		Walk(v, n.MatchCondition)
	case *LambdaExpr:
		Walk(v, n.Body)
	case *LikeExpr:
		Walk(v, n.Expr)
		Walk(v, n.Pattern)
		Walk(v, n.Escape)
		walkNodes(v, n.AnyValues)
	case *MergeStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		Walk(v, n.Source)
		Walk(v, n.On)
	case *ParenExpr:
		Walk(v, n.Expr)
	case *SelectStmt:
		Walk(v, n.Top)
		walkNodes(v, n.From)
		Walk(v, n.Where)
		Walk(v, n.Having)
		Walk(v, n.Qualify)
		Walk(v, n.Limit)
		Walk(v, n.Offset)
	case *SetOperationStmt:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *StarExpr:
		if n.Qualifier != nil {
			Walk(v, n.Qualifier)
		}
	case *SubqueryExpr:
		Walk(v, n.Query)
	case *TableRef:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.Subquery)
		if n.FuncCall != nil {
			Walk(v, n.FuncCall)
		}
	case *TypeName:
		if n.ElementType != nil {
			Walk(v, n.ElementType)
		}
	case *UnaryExpr:
		Walk(v, n.Expr)
	case *UndropDatabaseStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *UndropSchemaStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *UndropStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *UpdateStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		walkNodes(v, n.From)
		Walk(v, n.Where)
	}
}
