package ast

// NodeLoc extracts the Loc from any AST node that carries one.
// Returns NoLoc() if the node is nil or its type has no Loc field.
func NodeLoc(n Node) Loc {
	if n == nil {
		return NoLoc()
	}
	switch v := n.(type) {
	case *RawStmt:
		return v.Loc
	case *SelectStmt:
		return v.Loc
	case *InsertStmt:
		return v.Loc
	case *UpdateStmt:
		return v.Loc
	case *DeleteStmt:
		return v.Loc
	case *MergeStmt:
		return v.Loc
	case *CommitStmt:
		return v.Loc
	case *RollbackStmt:
		return v.Loc
	case *SavepointStmt:
		return v.Loc
	case *SetTransactionStmt:
		return v.Loc
	case *SetRoleStmt:
		return v.Loc
	case *SetConstraintsStmt:
		return v.Loc
	case *CallStmt:
		return v.Loc
	case *CommentStmt:
		return v.Loc
	case *TruncateStmt:
		return v.Loc
	case *AnalyzeStmt:
		return v.Loc
	case *ExplainPlanStmt:
		return v.Loc
	case *PurgeStmt:
		return v.Loc
	case *LockTableStmt:
		return v.Loc
	case *RenameStmt:
		return v.Loc
	case *GrantStmt:
		return v.Loc
	case *RevokeStmt:
		return v.Loc
	case *DropStmt:
		return v.Loc
	case *AuditStmt:
		return v.Loc
	case *NoauditStmt:
		return v.Loc
	case *AssociateStatisticsStmt:
		return v.Loc
	case *DisassociateStatisticsStmt:
		return v.Loc
	case *FlashbackTableStmt:
		return v.Loc
	case *FlashbackDatabaseStmt:
		return v.Loc
	case *AdminDDLStmt:
		return v.Loc
	case *AlterTableStmt:
		return v.Loc
	case *AlterTableCmd:
		return v.Loc
	case *AlterIndexStmt:
		return v.Loc
	case *AlterViewStmt:
		return v.Loc
	case *AlterSequenceStmt:
		return v.Loc
	case *AlterSessionStmt:
		return v.Loc
	case *AlterSystemStmt:
		return v.Loc
	case *AlterRoleStmt:
		return v.Loc
	case *AlterUserStmt:
		return v.Loc
	case *AlterProfileStmt:
		return v.Loc
	case *AlterResourceCostStmt:
		return v.Loc
	case *AlterDatabaseLinkStmt:
		return v.Loc
	case *AlterSynonymStmt:
		return v.Loc
	case *AlterTriggerStmt:
		return v.Loc
	case *AlterFunctionStmt:
		return v.Loc
	case *AlterProcedureStmt:
		return v.Loc
	case *AlterPackageStmt:
		return v.Loc
	case *AlterTypeStmt:
		return v.Loc
	case *AlterDomainStmt:
		return v.Loc
	case *AlterOperatorStmt:
		return v.Loc
	case *AlterIndextypeStmt:
		return v.Loc
	case *AlterOutlineStmt:
		return v.Loc
	case *AlterDimensionStmt:
		return v.Loc
	case *AlterClusterStmt:
		return v.Loc
	case *AlterMviewLogStmt:
		return v.Loc
	case *AlterMaterializedViewStmt:
		return v.Loc
	case *AlterMaterializedZonemapStmt:
		return v.Loc
	case *AlterTablespaceStmt:
		return v.Loc
	case *AlterAuditPolicyStmt:
		return v.Loc
	case *AlterLockdownProfileStmt:
		return v.Loc
	case *AlterInmemoryJoinGroupStmt:
		return v.Loc
	case *AlterJsonDualityViewStmt:
		return v.Loc
	case *AlterAnalyticViewStmt:
		return v.Loc
	case *AlterAttributeDimensionStmt:
		return v.Loc
	case *AlterHierarchyStmt:
		return v.Loc
	case *CreateTableStmt:
		return v.Loc
	case *CreateIndexStmt:
		return v.Loc
	case *CreateViewStmt:
		return v.Loc
	case *CreateSequenceStmt:
		return v.Loc
	case *CreateSynonymStmt:
		return v.Loc
	case *CreateDatabaseLinkStmt:
		return v.Loc
	case *CreateRoleStmt:
		return v.Loc
	case *CreateUserStmt:
		return v.Loc
	case *CreateProfileStmt:
		return v.Loc
	case *CreateSchemaStmt:
		return v.Loc
	case *CreateTriggerStmt:
		return v.Loc
	case *CreateFunctionStmt:
		return v.Loc
	case *CreateProcedureStmt:
		return v.Loc
	case *CreatePackageStmt:
		return v.Loc
	case *CreateTypeStmt:
		return v.Loc
	case *CreateDomainStmt:
		return v.Loc
	case *CreateOperatorStmt:
		return v.Loc
	case *CreateIndextypeStmt:
		return v.Loc
	case *CreateOutlineStmt:
		return v.Loc
	case *CreateDimensionStmt:
		return v.Loc
	case *CreateClusterStmt:
		return v.Loc
	case *CreateMviewLogStmt:
		return v.Loc
	case *CreateAuditPolicyStmt:
		return v.Loc
	case *CreateLockdownProfileStmt:
		return v.Loc
	case *CreateInmemoryJoinGroupStmt:
		return v.Loc
	case *CreateJsonDualityViewStmt:
		return v.Loc
	case *CreatePropertyGraphStmt:
		return v.Loc
	case *CreateAnalyticViewStmt:
		return v.Loc
	case *CreateAttributeDimensionStmt:
		return v.Loc
	case *CreateHierarchyStmt:
		return v.Loc
	case *CreateVectorIndexStmt:
		return v.Loc
	case *CreateMaterializedZonemapStmt:
		return v.Loc
	case *CreateTablespaceStmt:
		return v.Loc
	case *CreateTablespaceSetStmt:
		return v.Loc
	case *DropTablespaceStmt:
		return v.Loc
	case *DropAuditPolicyStmt:
		return v.Loc

	// Expression nodes
	case *BinaryExpr:
		return v.Loc
	case *UnaryExpr:
		return v.Loc
	case *BoolExpr:
		return v.Loc
	case *ColumnRef:
		return v.Loc
	case *FuncCallExpr:
		return v.Loc
	case *CaseExpr:
		return v.Loc
	case *CaseWhen:
		return v.Loc
	case *CastExpr:
		return v.Loc
	case *InExpr:
		return v.Loc
	case *BetweenExpr:
		return v.Loc
	case *LikeExpr:
		return v.Loc
	case *IsExpr:
		return v.Loc
	case *ExistsExpr:
		return v.Loc
	case *SubqueryExpr:
		return v.Loc
	case *IntervalExpr:
		return v.Loc
	case *ParenExpr:
		return v.Loc
	case *DecodeExpr:
		return v.Loc
	case *DecodePair:
		return v.Loc
	case *TreatExpr:
		return v.Loc
	case *MultisetExpr:
		return v.Loc
	case *CursorExpr:
		return v.Loc
	case *ContainersExpr:
		return v.Loc
	case *NumberLiteral:
		return v.Loc
	case *StringLiteral:
		return v.Loc
	case *NullLiteral:
		return v.Loc
	case *Star:
		return v.Loc
	case *BindVariable:
		return v.Loc
	case *PseudoColumn:
		return v.Loc

	// Clause/definition nodes
	case *ObjectName:
		return v.Loc
	case *Alias:
		return v.Loc
	case *TypeName:
		return v.Loc
	case *ColumnDef:
		return v.Loc
	case *ColumnConstraint:
		return v.Loc
	case *TableConstraint:
		return v.Loc
	case *ResTarget:
		return v.Loc
	case *SortBy:
		return v.Loc
	case *Hint:
		return v.Loc
	case *TableRef:
		return v.Loc
	case *SubqueryRef:
		return v.Loc
	case *LateralRef:
		return v.Loc
	case *JoinClause:
		return v.Loc
	case *WithClause:
		return v.Loc
	case *CTE:
		return v.Loc
	case *CTESearchClause:
		return v.Loc
	case *CTECycleClause:
		return v.Loc
	case *WindowSpec:
		return v.Loc
	case *WindowDef:
		return v.Loc
	case *WindowFrame:
		return v.Loc
	case *WindowBound:
		return v.Loc
	case *ForUpdateClause:
		return v.Loc
	case *FetchFirstClause:
		return v.Loc
	case *HierarchicalClause:
		return v.Loc
	case *SampleClause:
		return v.Loc
	case *PivotClause:
		return v.Loc
	case *UnpivotClause:
		return v.Loc
	case *MatchRecognizeClause:
		return v.Loc
	case *ModelClause:
		return v.Loc
	case *ModelMainModel:
		return v.Loc
	case *ModelRefModel:
		return v.Loc
	case *ModelRulesClause:
		return v.Loc
	case *ModelRule:
		return v.Loc
	case *ModelColumnClauses:
		return v.Loc
	case *ModelForLoop:
		return v.Loc
	case *ModelCellRefOptions:
		return v.Loc
	case *GroupingSetsClause:
		return v.Loc
	case *RollupClause:
		return v.Loc
	case *CubeClause:
		return v.Loc
	case *InsertIntoClause:
		return v.Loc
	case *SetClause:
		return v.Loc
	case *MergeClause:
		return v.Loc
	case *ErrorLogClause:
		return v.Loc
	case *FlashbackClause:
		return v.Loc
	case *PartitionClause:
		return v.Loc
	case *PartitionDef:
		return v.Loc
	case *PartitionExtClause:
		return v.Loc
	case *StorageClause:
		return v.Loc
	case *IndexColumn:
		return v.Loc
	case *LockTableItem:
		return v.Loc
	case *InlineExternalTable:
		return v.Loc
	case *TableCollectionExpr:
		return v.Loc
	case *JsonTableRef:
		return v.Loc
	case *JsonTableColumn:
		return v.Loc
	case *XmlTableRef:
		return v.Loc
	case *XmlTableColumn:
		return v.Loc
	case *Parameter:
		return v.Loc
	case *IdentityClause:
		return v.Loc
	case *IdentifiedClause:
		return v.Loc
	case *DefaultRoleClause:
		return v.Loc
	case *UserQuotaClause:
		return v.Loc
	case *ProfileLimit:
		return v.Loc
	case *ResourceCostEntry:
		return v.Loc
	case *DDLOption:
		return v.Loc
	case *DatafileClause:
		return v.Loc
	case *AutoextendClause:
		return v.Loc
	case *SetParam:
		return v.Loc
	case *KeepClause:
		return v.Loc
	case *ClusterColumn:
		return v.Loc
	case *GraphTableDef:
		return v.Loc
	case *GraphEdgeDef:
		return v.Loc
	case *GraphOptions:
		return v.Loc
	case *DomainColumn:
		return v.Loc
	case *DomainConstraint:
		return v.Loc
	case *DomainEnumItem:
		return v.Loc
	case *OperatorBinding:
		return v.Loc
	case *IndextypeOp:
		return v.Loc
	case *IndextypeModOp:
		return v.Loc
	case *DimensionLevel:
		return v.Loc
	case *DimensionHierarchy:
		return v.Loc
	case *DimensionAttribute:
		return v.Loc
	case *DimensionJoinKey:
		return v.Loc
	case *AuditActionEntry:
		return v.Loc
	case *AuditComponentAction:
		return v.Loc
	case *JoinGroupMember:
		return v.Loc
	case *TypeAttribute:
		return v.Loc
	case *TypeBodyMember:
		return v.Loc
	case *AttrDimSourceClause:
		return v.Loc
	case *AttrDimAttribute:
		return v.Loc
	case *AttrDimLevel:
		return v.Loc
	case *AttrDimOrderByItem:
		return v.Loc
	case *AttrDimAllClause:
		return v.Loc
	case *AttrDimJoinCondElem:
		return v.Loc
	case *HierAttr:
		return v.Loc
	case *HierLevelClause:
		return v.Loc

	// PL/SQL nodes
	case *PLSQLBlock:
		return v.Loc
	case *PLSQLVarDecl:
		return v.Loc
	case *PLSQLCursorDecl:
		return v.Loc
	case *PLSQLTypeDecl:
		return v.Loc
	case *PLSQLAssign:
		return v.Loc
	case *PLSQLIf:
		return v.Loc
	case *PLSQLElsIf:
		return v.Loc
	case *PLSQLCase:
		return v.Loc
	case *PLSQLWhen:
		return v.Loc
	case *PLSQLLoop:
		return v.Loc
	case *PLSQLForall:
		return v.Loc
	case *PLSQLReturn:
		return v.Loc
	case *PLSQLCall:
		return v.Loc
	case *PLSQLRaise:
		return v.Loc
	case *PLSQLExit:
		return v.Loc
	case *PLSQLContinue:
		return v.Loc
	case *PLSQLGoto:
		return v.Loc
	case *PLSQLNull:
		return v.Loc
	case *PLSQLOpen:
		return v.Loc
	case *PLSQLFetch:
		return v.Loc
	case *PLSQLClose:
		return v.Loc
	case *PLSQLExecImmediate:
		return v.Loc
	case *PLSQLPipeRow:
		return v.Loc
	case *PLSQLPragma:
		return v.Loc
	case *ExceptionHandler:
		return v.Loc

	default:
		return NoLoc()
	}
}

// ListSpan returns the byte range spanning all items in a List.
// It uses NodeLoc on the first and last items to compute the range.
// Returns NoLoc() if the list is nil, empty, or items have no Loc.
func ListSpan(list *List) Loc {
	if list == nil || len(list.Items) == 0 {
		return NoLoc()
	}
	first := NodeLoc(list.Items[0])
	last := NodeLoc(list.Items[len(list.Items)-1])
	if first.IsUnknown() || last.IsUnknown() || first.Start == -1 || last.End == -1 {
		return NoLoc()
	}
	return Loc{Start: first.Start, End: last.End}
}
