// Code generated by genwalker; DO NOT EDIT.

package ast

// walkChildren walks the child nodes of node, calling Walk(v, child)
// for each child. This function is generated from parsenodes.go.
func walkChildren(v Visitor, node Node) {
	switch n := node.(type) {
	case *AdminDDLStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Options)
	case *Alias:
		walkList(v, n.Cols)
	case *AlterAnalyticViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
		walkList(v, n.Options)
	case *AlterAttributeDimensionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterAuditPolicyStmt:
		for _, item := range n.Actions {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.ComponentActions {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterClusterStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterDatabaseLinkStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterDimensionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.AddLevels {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.AddHierarchies {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.AddAttributes {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterDomainStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.Display)
		Walk(v, n.Order)
		walkList(v, n.Annotations)
	case *AlterFunctionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.CompilerParams {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterHierarchyStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *AlterIndexStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.SplitValues)
	case *AlterIndextypeStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Modifications {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.UsingType != nil {
			Walk(v, n.UsingType)
		}
	case *AlterInmemoryJoinGroupStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Member != nil {
			Walk(v, n.Member)
		}
	case *AlterJsonDualityViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterMaterializedViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.StartWith)
		Walk(v, n.Next)
		if n.ScopeTable != nil {
			Walk(v, n.ScopeTable)
		}
		walkList(v, n.Options)
	case *AlterMaterializedZonemapStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterMviewLogStmt:
		if n.OnTable != nil {
			Walk(v, n.OnTable)
		}
		walkList(v, n.Columns)
		walkList(v, n.Options)
	case *AlterOperatorStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Binding != nil {
			Walk(v, n.Binding)
		}
	case *AlterPackageStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.CompilerParams {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterProcedureStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.CompilerParams {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterProfileStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Limits {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterResourceCostStmt:
		for _, item := range n.Costs {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterRoleStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterSequenceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.IncrementBy)
		Walk(v, n.MaxValue)
		Walk(v, n.MinValue)
		Walk(v, n.Cache)
		Walk(v, n.RestartWith)
	case *AlterSessionStmt:
		walkList(v, n.SetParams)
	case *AlterSynonymStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *AlterSystemStmt:
		walkList(v, n.SetParams)
	case *AlterTableCmd:
		if n.ColumnDef != nil {
			Walk(v, n.ColumnDef)
		}
		walkList(v, n.ColumnDefs)
		if n.Constraint != nil {
			Walk(v, n.Constraint)
		}
		walkList(v, n.Options)
	case *AlterTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Actions)
	case *AlterTablespaceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Datafiles {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Autoextend != nil {
			Walk(v, n.Autoextend)
		}
	case *AlterTriggerStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.CompilerParams {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterTypeStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.CompilerParams {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.Attributes {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.MethodParams {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.MethodReturn != nil {
			Walk(v, n.MethodReturn)
		}
		Walk(v, n.LimitValue)
		if n.ElementType != nil {
			Walk(v, n.ElementType)
		}
	case *AlterUserStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Identified != nil {
			Walk(v, n.Identified)
		}
		for _, item := range n.Quotas {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.DefaultRole != nil {
			Walk(v, n.DefaultRole)
		}
	case *AlterViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Constraint != nil {
			Walk(v, n.Constraint)
		}
		walkList(v, n.Annotations)
	case *AnalyzeStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		if n.IntoTable != nil {
			Walk(v, n.IntoTable)
		}
	case *AssociateStatisticsStmt:
		for _, item := range n.Objects {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Using != nil {
			Walk(v, n.Using)
		}
	case *AttrDimAllClause:
		Walk(v, n.MemberName)
		Walk(v, n.MemberCaption)
		Walk(v, n.MemberDesc)
	case *AttrDimAttribute:
		walkList(v, n.Classifications)
	case *AttrDimLevel:
		walkList(v, n.Classifications)
		walkList(v, n.KeyAttrs)
		walkList(v, n.AltKeyAttrs)
		Walk(v, n.MemberName)
		Walk(v, n.MemberCaption)
		Walk(v, n.MemberDesc)
		walkList(v, n.OrderByAttrs)
		walkList(v, n.Determines)
	case *AttrDimSourceClause:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.JoinCondition)
	case *AuditActionEntry:
		if n.Object != nil {
			Walk(v, n.Object)
		}
	case *AuditStmt:
		if n.Object != nil {
			Walk(v, n.Object)
		}
	case *BetweenExpr:
		Walk(v, n.Expr)
		Walk(v, n.Low)
		Walk(v, n.High)
	case *BinaryExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *BoolExpr:
		walkList(v, n.Args)
	case *CTE:
		walkList(v, n.Columns)
		Walk(v, n.Query)
		if n.Search != nil {
			Walk(v, n.Search)
		}
		if n.Cycle != nil {
			Walk(v, n.Cycle)
		}
	case *CTECycleClause:
		walkList(v, n.Columns)
		Walk(v, n.CycleValue)
		Walk(v, n.NoCycleValue)
	case *CTESearchClause:
		walkList(v, n.Columns)
	case *CallStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Args)
		Walk(v, n.Into)
	case *CaseExpr:
		Walk(v, n.Arg)
		walkList(v, n.Whens)
		Walk(v, n.Default)
	case *CaseWhen:
		Walk(v, n.Condition)
		Walk(v, n.Result)
	case *CastExpr:
		Walk(v, n.Arg)
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
	case *ClusterColumn:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
	case *ColumnConstraint:
		Walk(v, n.Expr)
		if n.RefTable != nil {
			Walk(v, n.RefTable)
		}
		walkList(v, n.RefColumns)
	case *ColumnDef:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		if n.Domain != nil {
			Walk(v, n.Domain)
		}
		Walk(v, n.Default)
		if n.Identity != nil {
			Walk(v, n.Identity)
		}
		Walk(v, n.Virtual)
		walkList(v, n.Constraints)
	case *CommentStmt:
		if n.Object != nil {
			Walk(v, n.Object)
		}
	case *ContainersExpr:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *CreateAnalyticViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.UsingTable != nil {
			Walk(v, n.UsingTable)
		}
		walkList(v, n.DimBy)
		walkList(v, n.Measures)
		walkList(v, n.Options)
	case *CreateAttributeDimensionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Classifications)
		walkList(v, n.Sources)
		walkList(v, n.Attributes)
		walkList(v, n.Levels)
		if n.AllClause != nil {
			Walk(v, n.AllClause)
		}
	case *CreateAuditPolicyStmt:
		for _, item := range n.Actions {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.ComponentActions {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CreateClusterStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Columns {
			if item != nil {
				Walk(v, item)
			}
		}
		Walk(v, n.HashExpr)
	case *CreateDimensionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Levels {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.Hierarchies {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.Attributes {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CreateDomainStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		Walk(v, n.Default)
		walkList(v, n.Constraints)
		Walk(v, n.Display)
		Walk(v, n.Order)
		walkList(v, n.Annotations)
		walkList(v, n.EnumItems)
		walkList(v, n.Columns)
		if n.FlexDomainName != nil {
			Walk(v, n.FlexDomainName)
		}
		walkList(v, n.FlexColumns)
		walkList(v, n.ChooseUsing)
		Walk(v, n.ChooseExpr)
	case *CreateFunctionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Parameters)
		if n.ReturnType != nil {
			Walk(v, n.ReturnType)
		}
		Walk(v, n.Body)
	case *CreateHierarchyStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Classifications)
		if n.UsingAttrDim != nil {
			Walk(v, n.UsingAttrDim)
		}
		if n.LevelHier != nil {
			Walk(v, n.LevelHier)
		}
		walkList(v, n.HierAttrs)
	case *CreateIndexStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Table != nil {
			Walk(v, n.Table)
		}
		if n.Cluster != nil {
			Walk(v, n.Cluster)
		}
		walkList(v, n.Columns)
		if n.IndexType != nil {
			Walk(v, n.IndexType)
		}
		walkList(v, n.FromTables)
		Walk(v, n.Where)
		walkList(v, n.Options)
	case *CreateIndextypeStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Operators {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.UsingType != nil {
			Walk(v, n.UsingType)
		}
	case *CreateInmemoryJoinGroupStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Members {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CreateJsonDualityViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.Query)
		walkList(v, n.Options)
	case *CreateMaterializedZonemapStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.OnTable != nil {
			Walk(v, n.OnTable)
		}
		if n.AsQuery != nil {
			Walk(v, n.AsQuery)
		}
	case *CreateMviewLogStmt:
		if n.OnTable != nil {
			Walk(v, n.OnTable)
		}
		walkList(v, n.Columns)
		Walk(v, n.PurgeStart)
		Walk(v, n.PurgeNext)
		walkList(v, n.Options)
	case *CreateOperatorStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Bindings {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CreatePackageStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Body)
	case *CreateProcedureStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Parameters)
		Walk(v, n.Body)
	case *CreateProfileStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Limits {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CreatePropertyGraphStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.VertexTables {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.EdgeTables {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Options != nil {
			Walk(v, n.Options)
		}
	case *CreateRoleStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateSchemaStmt:
		walkList(v, n.Stmts)
	case *CreateSequenceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.IncrementBy)
		Walk(v, n.StartWith)
		Walk(v, n.MaxValue)
		Walk(v, n.MinValue)
		Walk(v, n.Cache)
	case *CreateSynonymStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Target != nil {
			Walk(v, n.Target)
		}
	case *CreateTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Columns)
		walkList(v, n.Constraints)
		Walk(v, n.AsQuery)
		if n.Storage != nil {
			Walk(v, n.Storage)
		}
		if n.Partition != nil {
			Walk(v, n.Partition)
		}
		walkList(v, n.Hints)
		if n.Parent != nil {
			Walk(v, n.Parent)
		}
		walkList(v, n.Options)
	case *CreateTablespaceSetStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Datafiles {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CreateTablespaceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Datafiles {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Autoextend != nil {
			Walk(v, n.Autoextend)
		}
	case *CreateTriggerStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Events)
		if n.Table != nil {
			Walk(v, n.Table)
		}
		if n.Referencing != nil {
			Walk(v, n.Referencing)
		}
		Walk(v, n.When)
		Walk(v, n.Body)
	case *CreateTypeStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Attributes)
		if n.AsTable != nil {
			Walk(v, n.AsTable)
		}
		if n.AsVarray != nil {
			Walk(v, n.AsVarray)
		}
		Walk(v, n.VarraySize)
		walkList(v, n.Body)
	case *CreateUserStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Identified != nil {
			Walk(v, n.Identified)
		}
		for _, item := range n.Quotas {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CreateVectorIndexStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.TableName != nil {
			Walk(v, n.TableName)
		}
	case *CreateViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.Columns)
		Walk(v, n.Query)
		Walk(v, n.StartWith)
		Walk(v, n.Next)
		walkList(v, n.Options)
	case *CubeClause:
		walkList(v, n.Args)
	case *CursorAttributeExpr:
		Walk(v, n.Cursor)
	case *CursorExpr:
		Walk(v, n.Subquery)
	case *DDLOption:
		walkList(v, n.Items)
	case *DatafileClause:
		if n.Autoextend != nil {
			Walk(v, n.Autoextend)
		}
	case *DecodeExpr:
		Walk(v, n.Arg)
		walkList(v, n.Pairs)
		Walk(v, n.Default)
	case *DecodePair:
		Walk(v, n.Search)
		Walk(v, n.Result)
	case *DefaultRoleClause:
		for _, item := range n.Roles {
			if item != nil {
				Walk(v, item)
			}
		}
	case *DeleteStmt:
		Walk(v, n.Target)
		if n.Table != nil {
			Walk(v, n.Table)
		}
		if n.PartitionExt != nil {
			Walk(v, n.PartitionExt)
		}
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
		Walk(v, n.WhereClause)
		walkList(v, n.Returning)
		if n.ErrorLog != nil {
			Walk(v, n.ErrorLog)
		}
		walkList(v, n.Hints)
	case *DimensionAttribute:
		for _, item := range n.Columns {
			if item != nil {
				Walk(v, item)
			}
		}
	case *DimensionHierarchy:
		for _, item := range n.JoinKeys {
			if item != nil {
				Walk(v, item)
			}
		}
	case *DimensionJoinKey:
		for _, item := range n.ChildKeys {
			if item != nil {
				Walk(v, item)
			}
		}
	case *DimensionLevel:
		for _, item := range n.Columns {
			if item != nil {
				Walk(v, item)
			}
		}
	case *DisassociateStatisticsStmt:
		for _, item := range n.Objects {
			if item != nil {
				Walk(v, item)
			}
		}
	case *DomainColumn:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
		walkList(v, n.Annotations)
	case *DomainConstraint:
		Walk(v, n.CheckExpr)
		walkList(v, n.State)
	case *DomainEnumItem:
		Walk(v, n.Value)
	case *DropStmt:
		walkList(v, n.Names)
	case *DropTablespaceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *ErrorLogClause:
		if n.Into != nil {
			Walk(v, n.Into)
		}
		Walk(v, n.Tag)
		Walk(v, n.Reject)
	case *ExceptionHandler:
		walkList(v, n.Exceptions)
		walkList(v, n.Statements)
	case *ExistsExpr:
		Walk(v, n.Subquery)
	case *ExplainPlanStmt:
		if n.Into != nil {
			Walk(v, n.Into)
		}
		Walk(v, n.Statement)
	case *ExtractExpr:
		Walk(v, n.Expr)
	case *FetchFirstClause:
		Walk(v, n.Offset)
		Walk(v, n.Count)
	case *FieldAccessExpr:
		Walk(v, n.Expr)
	case *FlashbackClause:
		Walk(v, n.Expr)
		Walk(v, n.VersionsLow)
		Walk(v, n.VersionsHigh)
	case *FlashbackDatabaseStmt:
		if n.DatabaseName != nil {
			Walk(v, n.DatabaseName)
		}
		Walk(v, n.ToSCN)
		Walk(v, n.ToTimestamp)
	case *FlashbackTableStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Table != nil {
			Walk(v, n.Table)
		}
		Walk(v, n.ToSCN)
		Walk(v, n.ToTimestamp)
	case *ForUpdateClause:
		walkList(v, n.Tables)
		Walk(v, n.Wait)
	case *FuncCallExpr:
		if n.FuncName != nil {
			Walk(v, n.FuncName)
		}
		walkList(v, n.Args)
		walkList(v, n.OrderBy)
		if n.KeepClause != nil {
			Walk(v, n.KeepClause)
		}
		if n.Over != nil {
			Walk(v, n.Over)
		}
	case *GrantStmt:
		walkList(v, n.Privileges)
		if n.OnObject != nil {
			Walk(v, n.OnObject)
		}
		walkList(v, n.Grantees)
	case *GraphEdgeDef:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *GraphTableDef:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *GroupingSetsClause:
		walkList(v, n.Sets)
	case *HierAttr:
		walkList(v, n.Classifications)
	case *HierLevelClause:
		walkList(v, n.Classifications)
		if n.ChildOf != nil {
			Walk(v, n.ChildOf)
		}
	case *HierarchicalClause:
		Walk(v, n.ConnectBy)
		Walk(v, n.StartWith)
	case *IdentityClause:
		walkList(v, n.Options)
	case *InExpr:
		Walk(v, n.Expr)
		walkList(v, n.List)
	case *IndexColumn:
		Walk(v, n.Expr)
	case *IndextypeModOp:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *IndextypeOp:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *InlineExternalTable:
		walkList(v, n.Columns)
		Walk(v, n.RejectLimit)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *InsertIntoClause:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Columns)
		walkList(v, n.Values)
		Walk(v, n.When)
	case *InsertStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		if n.PartitionExt != nil {
			Walk(v, n.PartitionExt)
		}
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
		walkList(v, n.Columns)
		walkList(v, n.Values)
		Walk(v, n.ValuesRecord)
		walkList(v, n.SetClauses)
		if n.Select != nil {
			Walk(v, n.Select)
		}
		walkList(v, n.MultiTable)
		Walk(v, n.Subquery)
		walkList(v, n.Returning)
		if n.ErrorLog != nil {
			Walk(v, n.ErrorLog)
		}
		walkList(v, n.Hints)
	case *IntervalExpr:
		Walk(v, n.Value)
	case *IsExpr:
		Walk(v, n.Expr)
		walkList(v, n.TypeList)
	case *JoinClause:
		Walk(v, n.Left)
		Walk(v, n.Right)
		Walk(v, n.On)
		walkList(v, n.Using)
	case *JoinGroupMember:
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *JsonTableColumn:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		Walk(v, n.Path)
		if n.Nested != nil {
			Walk(v, n.Nested)
		}
	case *JsonTableRef:
		Walk(v, n.Expr)
		Walk(v, n.Path)
		walkList(v, n.Columns)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *KeepClause:
		walkList(v, n.OrderBy)
	case *LateralRef:
		Walk(v, n.Subquery)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *LikeExpr:
		Walk(v, n.Expr)
		Walk(v, n.Pattern)
		Walk(v, n.Escape)
	case *List:
		for _, item := range n.Items {
			Walk(v, item)
		}
	case *LockTableItem:
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *LockTableStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
		Walk(v, n.Wait)
	case *MatchRecognizeClause:
		Walk(v, n.Source)
		walkList(v, n.PartitionBy)
		walkList(v, n.OrderBy)
		walkList(v, n.Measures)
		walkList(v, n.Subsets)
		walkList(v, n.Definitions)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *MergeClause:
		Walk(v, n.Condition)
		walkList(v, n.UpdateSet)
		Walk(v, n.UpdateWhere)
		Walk(v, n.DeleteWhere)
		walkList(v, n.InsertCols)
		walkList(v, n.InsertVals)
		Walk(v, n.InsertWhere)
	case *MergeStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		if n.TargetAlias != nil {
			Walk(v, n.TargetAlias)
		}
		Walk(v, n.Source)
		if n.SourceAlias != nil {
			Walk(v, n.SourceAlias)
		}
		Walk(v, n.On)
		walkList(v, n.Clauses)
		if n.ErrorLog != nil {
			Walk(v, n.ErrorLog)
		}
		walkList(v, n.Hints)
	case *ModelCellReference:
		walkList(v, n.Dimensions)
	case *ModelClause:
		if n.CellRefOptions != nil {
			Walk(v, n.CellRefOptions)
		}
		for _, item := range n.RefModels {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.MainModel != nil {
			Walk(v, n.MainModel)
		}
	case *ModelColumnClauses:
		walkList(v, n.PartitionBy)
		walkList(v, n.DimensionBy)
		walkList(v, n.Measures)
	case *ModelForLoop:
		walkList(v, n.InList)
		if n.Subquery != nil {
			Walk(v, n.Subquery)
		}
		Walk(v, n.LikePattern)
		Walk(v, n.FromExpr)
		Walk(v, n.ToExpr)
		Walk(v, n.IncrExpr)
	case *ModelMainModel:
		if n.ColumnClauses != nil {
			Walk(v, n.ColumnClauses)
		}
		if n.CellRefOptions != nil {
			Walk(v, n.CellRefOptions)
		}
		if n.RulesClause != nil {
			Walk(v, n.RulesClause)
		}
	case *ModelRefModel:
		if n.Subquery != nil {
			Walk(v, n.Subquery)
		}
		if n.ColumnClauses != nil {
			Walk(v, n.ColumnClauses)
		}
		if n.CellRefOptions != nil {
			Walk(v, n.CellRefOptions)
		}
	case *ModelRule:
		Walk(v, n.CellRef)
		if n.Cell != nil {
			Walk(v, n.Cell)
		}
		Walk(v, n.Expr)
	case *ModelRulesClause:
		Walk(v, n.Iterate)
		Walk(v, n.Until)
		walkList(v, n.Rules)
	case *MultisetExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *NamedArgExpr:
		Walk(v, n.Expr)
	case *NoauditStmt:
		if n.Object != nil {
			Walk(v, n.Object)
		}
	case *OperatorBinding:
		if n.UsingFunc != nil {
			Walk(v, n.UsingFunc)
		}
		if n.AncillaryTo != nil {
			Walk(v, n.AncillaryTo)
		}
	case *PLSQLAssign:
		Walk(v, n.Target)
		Walk(v, n.Value)
	case *PLSQLBlock:
		walkList(v, n.Declarations)
		walkList(v, n.Statements)
		walkList(v, n.Exceptions)
	case *PLSQLCall:
		Walk(v, n.Name)
	case *PLSQLCase:
		Walk(v, n.Expr)
		for _, item := range n.Whens {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.Else {
			Walk(v, item)
		}
	case *PLSQLContinue:
		Walk(v, n.Condition)
	case *PLSQLCursorDecl:
		walkList(v, n.Parameters)
		Walk(v, n.Query)
	case *PLSQLElsIf:
		Walk(v, n.Condition)
		walkList(v, n.Then)
	case *PLSQLExecImmediate:
		Walk(v, n.SQL)
		walkList(v, n.Into)
		walkList(v, n.Using)
	case *PLSQLExit:
		Walk(v, n.Condition)
	case *PLSQLFetch:
		walkList(v, n.Into)
		Walk(v, n.Limit)
	case *PLSQLForall:
		Walk(v, n.Lower)
		Walk(v, n.Upper)
		Walk(v, n.Body)
	case *PLSQLIf:
		Walk(v, n.Condition)
		walkList(v, n.Then)
		walkList(v, n.ElsIfs)
		walkList(v, n.Else)
	case *PLSQLLabeledStatement:
		Walk(v, n.Statement)
	case *PLSQLLoop:
		Walk(v, n.Condition)
		Walk(v, n.LowerBound)
		Walk(v, n.UpperBound)
		walkList(v, n.CursorArgs)
		Walk(v, n.CursorQuery)
		walkList(v, n.Statements)
	case *PLSQLOpen:
		walkList(v, n.Args)
		Walk(v, n.ForQuery)
		Walk(v, n.ForExpr)
		walkList(v, n.UsingArgs)
	case *PLSQLPipeRow:
		Walk(v, n.Row)
	case *PLSQLPragma:
		walkList(v, n.Args)
	case *PLSQLReturn:
		Walk(v, n.Expr)
	case *PLSQLTypeDecl:
		if n.ElementType != nil {
			Walk(v, n.ElementType)
		}
		if n.IndexBy != nil {
			Walk(v, n.IndexBy)
		}
		Walk(v, n.Limit)
		walkList(v, n.Fields)
		if n.ReturnType != nil {
			Walk(v, n.ReturnType)
		}
	case *PLSQLVarDecl:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		Walk(v, n.Default)
	case *PLSQLWhen:
		Walk(v, n.Expr)
		for _, item := range n.Stmts {
			Walk(v, item)
		}
	case *Parameter:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		Walk(v, n.Default)
	case *ParenExpr:
		Walk(v, n.Expr)
	case *PartitionClause:
		walkList(v, n.Columns)
		Walk(v, n.Interval)
		walkList(v, n.Partitions)
		if n.Subpartition != nil {
			Walk(v, n.Subpartition)
		}
	case *PartitionDef:
		walkList(v, n.Values)
	case *PartitionExtClause:
		walkList(v, n.Keys)
	case *PivotAggregate:
		Walk(v, n.Expr)
	case *PivotClause:
		walkList(v, n.AggFuncs)
		Walk(v, n.ForCol)
		walkList(v, n.ForCols)
		walkList(v, n.InList)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
		Walk(v, n.Source)
		walkList(v, n.Aggregates)
		walkList(v, n.ForColumns)
		walkList(v, n.InItems)
	case *PivotInItem:
		walkList(v, n.Values)
	case *PurgeStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *RawStmt:
		Walk(v, n.Stmt)
	case *RenameStmt:
		if n.OldName != nil {
			Walk(v, n.OldName)
		}
		if n.NewName != nil {
			Walk(v, n.NewName)
		}
	case *ResTarget:
		Walk(v, n.Expr)
	case *RevokeStmt:
		walkList(v, n.Privileges)
		if n.OnObject != nil {
			Walk(v, n.OnObject)
		}
		walkList(v, n.Grantees)
	case *RollupClause:
		walkList(v, n.Args)
	case *SampleClause:
		Walk(v, n.Percent)
		Walk(v, n.Seed)
	case *SelectStmt:
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
		walkList(v, n.TargetList)
		if n.Into != nil {
			Walk(v, n.Into)
		}
		walkList(v, n.IntoVars)
		walkList(v, n.FromClause)
		Walk(v, n.WhereClause)
		if n.Hierarchical != nil {
			Walk(v, n.Hierarchical)
		}
		walkList(v, n.GroupClause)
		Walk(v, n.HavingClause)
		if n.ModelClause != nil {
			Walk(v, n.ModelClause)
		}
		for _, item := range n.WindowDefs {
			if item != nil {
				Walk(v, item)
			}
		}
		Walk(v, n.QualifyClause)
		walkList(v, n.OrderBy)
		if n.ForUpdate != nil {
			Walk(v, n.ForUpdate)
		}
		if n.FetchFirst != nil {
			Walk(v, n.FetchFirst)
		}
		walkList(v, n.Hints)
		if n.Larg != nil {
			Walk(v, n.Larg)
		}
		if n.Rarg != nil {
			Walk(v, n.Rarg)
		}
	case *SetClause:
		if n.Column != nil {
			Walk(v, n.Column)
		}
		walkList(v, n.Columns)
		Walk(v, n.Value)
	case *SetConstraintsStmt:
		for _, item := range n.Constraints {
			if item != nil {
				Walk(v, item)
			}
		}
	case *SetParam:
		Walk(v, n.Value)
	case *SetRoleStmt:
		for _, item := range n.Roles {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.Except {
			if item != nil {
				Walk(v, item)
			}
		}
	case *SortBy:
		Walk(v, n.Expr)
	case *SubqueryExpr:
		Walk(v, n.Subquery)
	case *SubqueryRef:
		Walk(v, n.Subquery)
		if n.Restriction != nil {
			Walk(v, n.Restriction)
		}
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *SubqueryRestrictionClause:
		if n.ConstraintName != nil {
			Walk(v, n.ConstraintName)
		}
	case *TableCollectionExpr:
		Walk(v, n.Expr)
		if n.FunctionCall != nil {
			Walk(v, n.FunctionCall)
		}
		Walk(v, n.CollectionExpr)
		walkList(v, n.ColumnAliases)
		if n.ReturnType != nil {
			Walk(v, n.ReturnType)
		}
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *TableConstraint:
		walkList(v, n.Columns)
		Walk(v, n.Expr)
		if n.RefTable != nil {
			Walk(v, n.RefTable)
		}
		walkList(v, n.RefColumns)
	case *TableRef:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
		if n.Sample != nil {
			Walk(v, n.Sample)
		}
		if n.Flashback != nil {
			Walk(v, n.Flashback)
		}
		if n.PartitionExt != nil {
			Walk(v, n.PartitionExt)
		}
	case *TreatExpr:
		Walk(v, n.Expr)
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
	case *TruncateStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *TypeAttribute:
		if n.DataType != nil {
			Walk(v, n.DataType)
		}
	case *TypeBodyMember:
		Walk(v, n.Subprog)
	case *TypeName:
		walkList(v, n.Names)
		walkList(v, n.TypeMods)
		walkList(v, n.ArrayBounds)
	case *UnaryExpr:
		Walk(v, n.Operand)
	case *UnpivotClause:
		Walk(v, n.ValueCol)
		Walk(v, n.PivotCol)
		walkList(v, n.InList)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
		Walk(v, n.Source)
		walkList(v, n.ValueColumns)
		Walk(v, n.PivotColumn)
		walkList(v, n.InputMappings)
	case *UnpivotInItem:
		walkList(v, n.InputColumns)
		Walk(v, n.Label)
	case *UpdateStmt:
		Walk(v, n.Target)
		if n.Table != nil {
			Walk(v, n.Table)
		}
		if n.PartitionExt != nil {
			Walk(v, n.PartitionExt)
		}
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
		walkList(v, n.SetClauses)
		walkList(v, n.FromClause)
		Walk(v, n.WhereClause)
		walkList(v, n.Returning)
		if n.ErrorLog != nil {
			Walk(v, n.ErrorLog)
		}
		walkList(v, n.Hints)
	case *UserQuotaClause:
		if n.Tablespace != nil {
			Walk(v, n.Tablespace)
		}
	case *WindowBound:
		Walk(v, n.Value)
	case *WindowDef:
		if n.Spec != nil {
			Walk(v, n.Spec)
		}
	case *WindowFrame:
		if n.Start != nil {
			Walk(v, n.Start)
		}
		if n.End != nil {
			Walk(v, n.End)
		}
	case *WindowSpec:
		walkList(v, n.PartitionBy)
		walkList(v, n.OrderBy)
		if n.Frame != nil {
			Walk(v, n.Frame)
		}
	case *WithClause:
		walkList(v, n.CTEs)
	case *XmlTableColumn:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		Walk(v, n.Path)
		Walk(v, n.Default)
	case *XmlTableRef:
		Walk(v, n.XPath)
		Walk(v, n.Passing)
		walkList(v, n.Columns)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	}
}
