// Code generated by genwalker; DO NOT EDIT.

package ast

// walkChildren walks the child nodes of node, calling Walk(v, child)
// for each child. This function is generated from parsenodes.go.
func walkChildren(v Visitor, node Node) {
	switch n := node.(type) {
	case *A_ArrayExpr:
		walkList(v, n.Elements)
	case *A_Const:
		Walk(v, n.Val)
	case *A_Expr:
		walkList(v, n.Name)
		Walk(v, n.Lexpr)
		Walk(v, n.Rexpr)
	case *A_Indices:
		Walk(v, n.Lidx)
		Walk(v, n.Uidx)
	case *A_Indirection:
		Walk(v, n.Arg)
		walkList(v, n.Indirection)
	case *AccessPriv:
		walkList(v, n.Cols)
	case *Alias:
		walkList(v, n.Colnames)
	case *AlterCollationStmt:
		walkList(v, n.Collname)
	case *AlterDatabaseSetStmt:
		if n.Setstmt != nil {
			Walk(v, n.Setstmt)
		}
	case *AlterDatabaseStmt:
		walkList(v, n.Options)
	case *AlterDefaultPrivilegesStmt:
		walkList(v, n.Options)
		if n.Action != nil {
			Walk(v, n.Action)
		}
	case *AlterDomainStmt:
		walkList(v, n.Typname)
		Walk(v, n.Def)
	case *AlterEnumStmt:
		walkList(v, n.Typname)
	case *AlterExtensionContentsStmt:
		Walk(v, n.Object)
	case *AlterExtensionStmt:
		walkList(v, n.Options)
	case *AlterFdwStmt:
		walkList(v, n.FuncOptions)
		walkList(v, n.Options)
	case *AlterForeignServerStmt:
		walkList(v, n.Options)
	case *AlterFunctionStmt:
		if n.Func != nil {
			Walk(v, n.Func)
		}
		walkList(v, n.Actions)
	case *AlterObjectDependsStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		Walk(v, n.Object)
		Walk(v, n.Extname)
	case *AlterObjectSchemaStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		Walk(v, n.Object)
	case *AlterOpFamilyStmt:
		walkList(v, n.Opfamilyname)
		walkList(v, n.Items)
	case *AlterOperatorStmt:
		if n.Opername != nil {
			Walk(v, n.Opername)
		}
		walkList(v, n.Options)
	case *AlterOwnerStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		Walk(v, n.Object)
		if n.Newowner != nil {
			Walk(v, n.Newowner)
		}
	case *AlterPolicyStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Roles)
		Walk(v, n.Qual)
		Walk(v, n.WithCheck)
	case *AlterPublicationStmt:
		walkList(v, n.Options)
		walkList(v, n.Pubobjects)
	case *AlterRoleSetStmt:
		if n.Role != nil {
			Walk(v, n.Role)
		}
		if n.Setstmt != nil {
			Walk(v, n.Setstmt)
		}
	case *AlterRoleStmt:
		if n.Role != nil {
			Walk(v, n.Role)
		}
		walkList(v, n.Options)
	case *AlterSeqStmt:
		if n.Sequence != nil {
			Walk(v, n.Sequence)
		}
		walkList(v, n.Options)
	case *AlterStatsStmt:
		walkList(v, n.Defnames)
	case *AlterSubscriptionStmt:
		walkList(v, n.Publication)
		walkList(v, n.Options)
	case *AlterSystemStmt:
		if n.Setstmt != nil {
			Walk(v, n.Setstmt)
		}
	case *AlterTSConfigurationStmt:
		walkList(v, n.Cfgname)
		walkList(v, n.Tokentype)
		walkList(v, n.Dicts)
	case *AlterTSDictionaryStmt:
		walkList(v, n.Dictname)
		walkList(v, n.Options)
	case *AlterTableCmd:
		if n.Newowner != nil {
			Walk(v, n.Newowner)
		}
		Walk(v, n.Def)
	case *AlterTableMoveAllStmt:
		walkList(v, n.Roles)
	case *AlterTableSpaceOptionsStmt:
		walkList(v, n.Options)
	case *AlterTableStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.Cmds)
	case *AlterTypeStmt:
		walkList(v, n.TypeName)
		walkList(v, n.Options)
	case *AlterUserMappingStmt:
		if n.User != nil {
			Walk(v, n.User)
		}
		walkList(v, n.Options)
	case *ArrayExpr:
		walkList(v, n.Elements)
	case *BoolExpr:
		walkList(v, n.Args)
	case *BooleanTest:
		Walk(v, n.Arg)
	case *CTECycleClause:
		walkList(v, n.CycleColList)
		Walk(v, n.CycleMarkValue)
		Walk(v, n.CycleMarkDefault)
	case *CTESearchClause:
		walkList(v, n.SearchColList)
	case *CallStmt:
		if n.Funccall != nil {
			Walk(v, n.Funccall)
		}
	case *CaseExpr:
		Walk(v, n.Arg)
		walkList(v, n.Args)
		Walk(v, n.Defresult)
	case *CaseWhen:
		Walk(v, n.Expr)
		Walk(v, n.Result)
	case *ClusterStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.Params)
	case *CoalesceExpr:
		walkList(v, n.Args)
	case *CollateClause:
		Walk(v, n.Arg)
		walkList(v, n.Collname)
	case *ColumnDef:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		Walk(v, n.RawDefault)
		Walk(v, n.CookedDefault)
		if n.IdentitySequence != nil {
			Walk(v, n.IdentitySequence)
		}
		if n.CollClause != nil {
			Walk(v, n.CollClause)
		}
		walkList(v, n.Constraints)
		walkList(v, n.Fdwoptions)
	case *ColumnRef:
		walkList(v, n.Fields)
	case *CommentStmt:
		Walk(v, n.Object)
	case *CommonTableExpr:
		walkList(v, n.Aliascolnames)
		Walk(v, n.Ctequery)
		Walk(v, n.SearchClause)
		Walk(v, n.CycleClause)
		walkList(v, n.Ctecolnames)
		walkList(v, n.Ctecoltypes)
		walkList(v, n.Ctecoltypmods)
		walkList(v, n.Ctecolcollations)
	case *CompositeTypeStmt:
		if n.Typevar != nil {
			Walk(v, n.Typevar)
		}
		walkList(v, n.Coldeflist)
	case *Constraint:
		Walk(v, n.RawExpr)
		walkList(v, n.Keys)
		walkList(v, n.Including)
		walkList(v, n.Exclusions)
		walkList(v, n.Options)
		Walk(v, n.WhereClause)
		if n.Pktable != nil {
			Walk(v, n.Pktable)
		}
		walkList(v, n.FkAttrs)
		walkList(v, n.PkAttrs)
		walkList(v, n.FkDelsetcols)
		walkList(v, n.OldConpfeqop)
	case *ConstraintsSetStmt:
		walkList(v, n.Constraints)
	case *CopyStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		Walk(v, n.Query)
		walkList(v, n.Attlist)
		walkList(v, n.Options)
		Walk(v, n.WhereClause)
	case *CreateAmStmt:
		walkList(v, n.HandlerName)
	case *CreateCastStmt:
		if n.Sourcetype != nil {
			Walk(v, n.Sourcetype)
		}
		if n.Targettype != nil {
			Walk(v, n.Targettype)
		}
		if n.Func != nil {
			Walk(v, n.Func)
		}
	case *CreateConversionStmt:
		walkList(v, n.ConversionName)
		walkList(v, n.FuncName)
	case *CreateDomainStmt:
		walkList(v, n.Domainname)
		if n.Typname != nil {
			Walk(v, n.Typname)
		}
		if n.CollClause != nil {
			Walk(v, n.CollClause)
		}
		walkList(v, n.Constraints)
	case *CreateEnumStmt:
		walkList(v, n.TypeName)
		walkList(v, n.Vals)
	case *CreateEventTrigStmt:
		walkList(v, n.Whenclause)
		walkList(v, n.Funcname)
	case *CreateExtensionStmt:
		walkList(v, n.Options)
	case *CreateFdwStmt:
		walkList(v, n.FuncOptions)
		walkList(v, n.Options)
	case *CreateForeignServerStmt:
		walkList(v, n.Options)
	case *CreateForeignTableStmt:
		walkList(v, n.Options)
	case *CreateFunctionStmt:
		walkList(v, n.Funcname)
		walkList(v, n.Parameters)
		if n.ReturnType != nil {
			Walk(v, n.ReturnType)
		}
		walkList(v, n.Options)
		Walk(v, n.SqlBody)
	case *CreateOpClassItem:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkList(v, n.OrderFamily)
		walkList(v, n.ClassArgs)
		if n.Storedtype != nil {
			Walk(v, n.Storedtype)
		}
	case *CreateOpClassStmt:
		walkList(v, n.Opclassname)
		walkList(v, n.Opfamilyname)
		if n.Datatype != nil {
			Walk(v, n.Datatype)
		}
		walkList(v, n.Items)
	case *CreateOpFamilyStmt:
		walkList(v, n.Opfamilyname)
	case *CreatePLangStmt:
		walkList(v, n.Plhandler)
		walkList(v, n.Plinline)
		walkList(v, n.Plvalidator)
	case *CreatePolicyStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		walkList(v, n.Roles)
		Walk(v, n.Qual)
		Walk(v, n.WithCheck)
	case *CreatePublicationStmt:
		walkList(v, n.Options)
		walkList(v, n.Pubobjects)
	case *CreateRangeStmt:
		walkList(v, n.TypeName)
		walkList(v, n.Params)
	case *CreateRoleStmt:
		walkList(v, n.Options)
	case *CreateSchemaStmt:
		if n.Authrole != nil {
			Walk(v, n.Authrole)
		}
		walkList(v, n.SchemaElts)
	case *CreateSeqStmt:
		if n.Sequence != nil {
			Walk(v, n.Sequence)
		}
		walkList(v, n.Options)
	case *CreateStatsStmt:
		walkList(v, n.Defnames)
		walkList(v, n.StatTypes)
		walkList(v, n.Exprs)
		walkList(v, n.Relations)
	case *CreateStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.TableElts)
		walkList(v, n.InhRelations)
		Walk(v, n.Partbound)
		if n.Partspec != nil {
			Walk(v, n.Partspec)
		}
		if n.OfTypename != nil {
			Walk(v, n.OfTypename)
		}
		walkList(v, n.Constraints)
		walkList(v, n.Options)
	case *CreateSubscriptionStmt:
		walkList(v, n.Publication)
		walkList(v, n.Options)
	case *CreateTableAsStmt:
		Walk(v, n.Query)
		if n.Into != nil {
			Walk(v, n.Into)
		}
	case *CreateTableSpaceStmt:
		if n.Owner != nil {
			Walk(v, n.Owner)
		}
		walkList(v, n.Options)
	case *CreateTransformStmt:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		if n.Fromsql != nil {
			Walk(v, n.Fromsql)
		}
		if n.Tosql != nil {
			Walk(v, n.Tosql)
		}
	case *CreateTrigStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.Funcname)
		walkList(v, n.Args)
		walkList(v, n.Columns)
		Walk(v, n.WhenClause)
		walkList(v, n.TransitionRels)
		if n.Constrrel != nil {
			Walk(v, n.Constrrel)
		}
	case *CreateUserMappingStmt:
		if n.User != nil {
			Walk(v, n.User)
		}
		walkList(v, n.Options)
	case *CreatedbStmt:
		walkList(v, n.Options)
	case *DeclareCursorStmt:
		Walk(v, n.Query)
	case *DefElem:
		Walk(v, n.Arg)
	case *DefineStmt:
		walkList(v, n.Defnames)
		walkList(v, n.Args)
		walkList(v, n.Definition)
	case *DeleteStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.UsingClause)
		Walk(v, n.WhereClause)
		walkList(v, n.ReturningList)
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
	case *DoStmt:
		walkList(v, n.Args)
	case *DropOwnedStmt:
		walkList(v, n.Roles)
	case *DropRoleStmt:
		walkList(v, n.Roles)
	case *DropStmt:
		walkList(v, n.Objects)
	case *DropUserMappingStmt:
		if n.User != nil {
			Walk(v, n.User)
		}
	case *DropdbStmt:
		walkList(v, n.Options)
	case *ExecuteStmt:
		walkList(v, n.Params)
	case *ExplainStmt:
		Walk(v, n.Query)
		walkList(v, n.Options)
	case *FromExpr:
		walkList(v, n.Fromlist)
		Walk(v, n.Quals)
	case *FuncCall:
		walkList(v, n.Funcname)
		walkList(v, n.Args)
		walkList(v, n.AggOrder)
		Walk(v, n.AggFilter)
		Walk(v, n.Over)
	case *FunctionParameter:
		if n.ArgType != nil {
			Walk(v, n.ArgType)
		}
		Walk(v, n.Defexpr)
	case *GrantRoleStmt:
		walkList(v, n.GrantedRoles)
		walkList(v, n.GranteeRoles)
		walkList(v, n.Opt)
		if n.Grantor != nil {
			Walk(v, n.Grantor)
		}
	case *GrantStmt:
		walkList(v, n.Objects)
		walkList(v, n.Privileges)
		walkList(v, n.Grantees)
		if n.Grantor != nil {
			Walk(v, n.Grantor)
		}
	case *GroupingFunc:
		walkList(v, n.Args)
		walkList(v, n.Refs)
	case *GroupingSet:
		walkList(v, n.Content)
	case *ImportForeignSchemaStmt:
		walkList(v, n.TableList)
		walkList(v, n.Options)
	case *IndexElem:
		Walk(v, n.Expr)
		walkList(v, n.Collation)
		walkList(v, n.Opclass)
		walkList(v, n.Opclassopts)
	case *IndexStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.IndexParams)
		walkList(v, n.IndexIncludingParams)
		walkList(v, n.Options)
		Walk(v, n.WhereClause)
		walkList(v, n.ExcludeOpNames)
	case *InferClause:
		walkList(v, n.IndexElems)
		Walk(v, n.WhereClause)
	case *InsertStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.Cols)
		Walk(v, n.SelectStmt)
		if n.OnConflictClause != nil {
			Walk(v, n.OnConflictClause)
		}
		walkList(v, n.ReturningList)
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
	case *IntoClause:
		if n.Rel != nil {
			Walk(v, n.Rel)
		}
		walkList(v, n.ColNames)
		walkList(v, n.Options)
		Walk(v, n.ViewQuery)
	case *JoinExpr:
		Walk(v, n.Larg)
		Walk(v, n.Rarg)
		walkList(v, n.UsingClause)
		if n.JoinUsing != nil {
			Walk(v, n.JoinUsing)
		}
		Walk(v, n.Quals)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *JsonAggConstructor:
		if n.Output != nil {
			Walk(v, n.Output)
		}
		Walk(v, n.Agg_filter)
		walkList(v, n.Agg_order)
		if n.Over != nil {
			Walk(v, n.Over)
		}
	case *JsonArgument:
		if n.Val != nil {
			Walk(v, n.Val)
		}
	case *JsonArrayAgg:
		if n.Constructor != nil {
			Walk(v, n.Constructor)
		}
		if n.Arg != nil {
			Walk(v, n.Arg)
		}
	case *JsonArrayConstructor:
		walkList(v, n.Exprs)
		if n.Output != nil {
			Walk(v, n.Output)
		}
	case *JsonArrayQueryConstructor:
		Walk(v, n.Query)
		if n.Output != nil {
			Walk(v, n.Output)
		}
		if n.Format != nil {
			Walk(v, n.Format)
		}
	case *JsonBehavior:
		Walk(v, n.Expr)
		Walk(v, n.Coerce)
	case *JsonFuncExpr:
		if n.ContextItem != nil {
			Walk(v, n.ContextItem)
		}
		Walk(v, n.Pathspec)
		walkList(v, n.Passing)
		if n.Output != nil {
			Walk(v, n.Output)
		}
		if n.OnEmpty != nil {
			Walk(v, n.OnEmpty)
		}
		if n.OnError != nil {
			Walk(v, n.OnError)
		}
	case *JsonIsPredicate:
		Walk(v, n.Expr)
		if n.Format != nil {
			Walk(v, n.Format)
		}
	case *JsonKeyValue:
		Walk(v, n.Key)
		if n.Value != nil {
			Walk(v, n.Value)
		}
	case *JsonObjectAgg:
		if n.Constructor != nil {
			Walk(v, n.Constructor)
		}
		if n.Arg != nil {
			Walk(v, n.Arg)
		}
	case *JsonObjectConstructor:
		walkList(v, n.Exprs)
		if n.Output != nil {
			Walk(v, n.Output)
		}
	case *JsonOutput:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		if n.Returning != nil {
			Walk(v, n.Returning)
		}
	case *JsonParseExpr:
		if n.Expr != nil {
			Walk(v, n.Expr)
		}
		if n.Output != nil {
			Walk(v, n.Output)
		}
	case *JsonReturning:
		if n.Format != nil {
			Walk(v, n.Format)
		}
	case *JsonScalarExpr:
		Walk(v, n.Expr)
		if n.Output != nil {
			Walk(v, n.Output)
		}
	case *JsonSerializeExpr:
		if n.Expr != nil {
			Walk(v, n.Expr)
		}
		if n.Output != nil {
			Walk(v, n.Output)
		}
	case *JsonTable:
		if n.ContextItem != nil {
			Walk(v, n.ContextItem)
		}
		if n.Pathspec != nil {
			Walk(v, n.Pathspec)
		}
		walkList(v, n.Passing)
		walkList(v, n.Columns)
		if n.OnError != nil {
			Walk(v, n.OnError)
		}
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *JsonTableColumn:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		if n.Pathspec != nil {
			Walk(v, n.Pathspec)
		}
		if n.Format != nil {
			Walk(v, n.Format)
		}
		walkList(v, n.Columns)
		if n.OnEmpty != nil {
			Walk(v, n.OnEmpty)
		}
		if n.OnError != nil {
			Walk(v, n.OnError)
		}
	case *JsonTablePathSpec:
		Walk(v, n.String)
	case *JsonValueExpr:
		Walk(v, n.RawExpr)
		Walk(v, n.FormattedExpr)
		if n.Format != nil {
			Walk(v, n.Format)
		}
	case *LockStmt:
		walkList(v, n.Relations)
	case *LockingClause:
		walkList(v, n.LockedRels)
	case *MergeStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		Walk(v, n.SourceRelation)
		Walk(v, n.JoinCondition)
		walkList(v, n.MergeWhenClauses)
		walkList(v, n.ReturningList)
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
	case *MergeWhenClause:
		Walk(v, n.Condition)
		walkList(v, n.TargetList)
		walkList(v, n.Values)
	case *MinMaxExpr:
		walkList(v, n.Args)
	case *MultiAssignRef:
		Walk(v, n.Source)
	case *NamedArgExpr:
		Walk(v, n.Arg)
	case *NullIfExpr:
		walkList(v, n.Args)
	case *NullTest:
		Walk(v, n.Arg)
	case *ObjectWithArgs:
		walkList(v, n.Objname)
		walkList(v, n.Objargs)
	case *OnConflictClause:
		if n.Infer != nil {
			Walk(v, n.Infer)
		}
		walkList(v, n.TargetList)
		Walk(v, n.WhereClause)
	case *PartitionBoundSpec:
		walkList(v, n.Listdatums)
		walkList(v, n.Lowerdatums)
		walkList(v, n.Upperdatums)
	case *PartitionCmd:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Bound != nil {
			Walk(v, n.Bound)
		}
	case *PartitionElem:
		Walk(v, n.Expr)
		walkList(v, n.Collation)
		walkList(v, n.Opclass)
	case *PartitionSpec:
		walkList(v, n.PartParams)
	case *PrepareStmt:
		walkList(v, n.Argtypes)
		Walk(v, n.Query)
	case *PublicationObjSpec:
		if n.Pubtable != nil {
			Walk(v, n.Pubtable)
		}
	case *PublicationTable:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		Walk(v, n.WhereClause)
		walkList(v, n.Columns)
	case *RangeFunction:
		walkList(v, n.Functions)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
		walkList(v, n.Coldeflist)
	case *RangeSubselect:
		Walk(v, n.Subquery)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *RangeTableFunc:
		Walk(v, n.Docexpr)
		Walk(v, n.Rowexpr)
		walkList(v, n.Namespaces)
		walkList(v, n.Columns)
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *RangeTableFuncCol:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		Walk(v, n.Colexpr)
		Walk(v, n.Coldefexpr)
	case *RangeTableSample:
		Walk(v, n.Relation)
		walkList(v, n.Method)
		walkList(v, n.Args)
		Walk(v, n.Repeatable)
	case *RangeVar:
		if n.Alias != nil {
			Walk(v, n.Alias)
		}
	case *RawStmt:
		Walk(v, n.Stmt)
	case *ReassignOwnedStmt:
		walkList(v, n.Roles)
		if n.Newrole != nil {
			Walk(v, n.Newrole)
		}
	case *RefreshMatViewStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
	case *ReindexStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.Params)
	case *RenameStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		Walk(v, n.Object)
	case *ResTarget:
		walkList(v, n.Indirection)
		Walk(v, n.Val)
	case *ReturnStmt:
		Walk(v, n.Returnval)
	case *RowExpr:
		walkList(v, n.Args)
		walkList(v, n.Colnames)
	case *RuleStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		Walk(v, n.WhereClause)
		walkList(v, n.Actions)
	case *SecLabelStmt:
		Walk(v, n.Object)
	case *SelectStmt:
		walkList(v, n.DistinctClause)
		if n.IntoClause != nil {
			Walk(v, n.IntoClause)
		}
		walkList(v, n.TargetList)
		walkList(v, n.FromClause)
		Walk(v, n.WhereClause)
		walkList(v, n.GroupClause)
		Walk(v, n.HavingClause)
		walkList(v, n.WindowClause)
		walkList(v, n.ValuesLists)
		walkList(v, n.SortClause)
		Walk(v, n.LimitOffset)
		Walk(v, n.LimitCount)
		walkList(v, n.LockingClause)
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
		if n.Larg != nil {
			Walk(v, n.Larg)
		}
		if n.Rarg != nil {
			Walk(v, n.Rarg)
		}
	case *SetOperationStmt:
		Walk(v, n.Larg)
		Walk(v, n.Rarg)
		walkList(v, n.ColTypes)
		walkList(v, n.ColTypmods)
		walkList(v, n.ColCollations)
		walkList(v, n.GroupClauses)
	case *SortBy:
		Walk(v, n.Node)
		walkList(v, n.UseOp)
	case *StatsElem:
		Walk(v, n.Expr)
	case *SubLink:
		Walk(v, n.Testexpr)
		walkList(v, n.OperName)
		Walk(v, n.Subselect)
	case *TableLikeClause:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.Columns)
		walkList(v, n.AncillaryData)
	case *TransactionStmt:
		walkList(v, n.Options)
	case *TruncateStmt:
		walkList(v, n.Relations)
	case *TypeCast:
		Walk(v, n.Arg)
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
	case *TypeName:
		walkList(v, n.Names)
		walkList(v, n.Typmods)
		walkList(v, n.ArrayBounds)
	case *UpdateStmt:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.TargetList)
		Walk(v, n.WhereClause)
		walkList(v, n.FromClause)
		walkList(v, n.ReturningList)
		if n.WithClause != nil {
			Walk(v, n.WithClause)
		}
	case *VacuumRelation:
		if n.Relation != nil {
			Walk(v, n.Relation)
		}
		walkList(v, n.VaCols)
	case *VacuumStmt:
		walkList(v, n.Options)
		walkList(v, n.Rels)
	case *VariableSetStmt:
		walkList(v, n.Args)
	case *ViewStmt:
		if n.View != nil {
			Walk(v, n.View)
		}
		walkList(v, n.Aliases)
		Walk(v, n.Query)
		walkList(v, n.Options)
	case *WindowClause:
		walkList(v, n.PartitionClause)
		walkList(v, n.OrderClause)
		Walk(v, n.StartOffset)
		Walk(v, n.EndOffset)
		walkList(v, n.RunCondition)
	case *WindowDef:
		walkList(v, n.PartitionClause)
		walkList(v, n.OrderClause)
		Walk(v, n.StartOffset)
		Walk(v, n.EndOffset)
	case *WithClause:
		walkList(v, n.Ctes)
	case *XmlExpr:
		walkList(v, n.NamedArgs)
		walkList(v, n.ArgNames)
		walkList(v, n.Args)
	case *XmlSerialize:
		Walk(v, n.Expr)
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
	}
}
