// Code generated by genwalker; DO NOT EDIT.

package ast

// walkChildren walks the child nodes of node, calling Walk(v, child)
// for each child. This function is generated from parsenodes.go and node.go.
func walkChildren(v Visitor, node Node) {
	switch n := node.(type) {
	case *AlterAction:
		if n.Column != nil {
			Walk(v, n.Column)
		}
		Walk(v, n.FillUsing)
		if n.Constraint != nil {
			Walk(v, n.Constraint)
		}
		if n.NewType != nil {
			Walk(v, n.NewType)
		}
		Walk(v, n.Generated)
		Walk(v, n.Default)
		Walk(v, n.RowDeletion)
		if n.RenameTo != nil {
			Walk(v, n.RenameTo)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *AlterChangeStreamStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.ForTables {
			Walk(v, c)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *AlterLocalityGroupStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.SetOptions {
			Walk(v, c)
		}
	case *AlterSequenceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.SetOptions {
			Walk(v, c)
		}
	case *AlterStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Actions {
			Walk(v, c)
		}
	case *AnalyzeStmt:
		for _, c := range n.Options {
			Walk(v, c)
		}
		for _, c := range n.Targets {
			Walk(v, c)
		}
	case *ArrayExpr:
		walkNodes(v, n.Elements)
		if n.ElemType != nil {
			Walk(v, n.ElemType)
		}
	case *ArraySubqueryExpr:
		Walk(v, n.Query)
	case *AssertStmt:
		Walk(v, n.Expr)
		Walk(v, n.Description)
	case *BQAlterStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.OnTable != nil {
			Walk(v, n.OnTable)
		}
		for _, c := range n.SetOptions {
			Walk(v, c)
		}
	case *BQDropStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.OnTable != nil {
			Walk(v, n.OnTable)
		}
	case *BetweenExpr:
		Walk(v, n.Expr)
		Walk(v, n.Low)
		Walk(v, n.High)
	case *BinaryExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *BracedConstructor:
		if n.Type != nil {
			Walk(v, n.Type)
		}
		walkNodes(v, n.Fields)
	case *CTE:
		Walk(v, n.Query)
		if n.Depth != nil {
			Walk(v, n.Depth)
		}
	case *CallArg:
		if n.Path != nil {
			Walk(v, n.Path)
		}
	case *CallStmt:
		if n.Proc != nil {
			Walk(v, n.Proc)
		}
		walkNodes(v, n.Args)
	case *CaseExpr:
		Walk(v, n.Operand)
		for _, c := range n.Whens {
			Walk(v, c)
		}
		Walk(v, n.Else)
	case *CastExpr:
		Walk(v, n.Expr)
		if n.Type != nil {
			Walk(v, n.Type)
		}
		Walk(v, n.Format)
		Walk(v, n.TimeZone)
	case *ChangeStreamTrackedTable:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *ClampedModifier:
		Walk(v, n.Low)
		Walk(v, n.High)
	case *CloneDataSource:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		Walk(v, n.ForSystemTime)
		Walk(v, n.Where)
	case *CloneDataStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Sources {
			Walk(v, c)
		}
	case *ColumnDef:
		if n.Type != nil {
			Walk(v, n.Type)
		}
		if n.ForeignKey != nil {
			Walk(v, n.ForeignKey)
		}
		Walk(v, n.Default)
		Walk(v, n.Generated)
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *CompareExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *CreateChangeStreamStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.ForTables {
			Walk(v, c)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *CreateDatabaseStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *CreateEntityStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *CreateFunctionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Params {
			Walk(v, c)
		}
		if n.Returns != nil {
			Walk(v, n.Returns)
		}
		for _, c := range n.ReturnColumns {
			Walk(v, c)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
		Walk(v, n.Body)
		Walk(v, n.AsQuery)
	case *CreateIndexStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Table != nil {
			Walk(v, n.Table)
		}
		for _, c := range n.Keys {
			Walk(v, c)
		}
		walkNodes(v, n.Storing)
		walkNodes(v, n.PartitionBy)
		if n.Interleave != nil {
			Walk(v, n.Interleave)
		}
		Walk(v, n.Where)
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *CreateLocalityGroupStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *CreateMaterializedViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Columns {
			Walk(v, c)
		}
		walkNodes(v, n.PartitionBy)
		walkNodes(v, n.ClusterBy)
		for _, c := range n.Options {
			Walk(v, c)
		}
		Walk(v, n.AsQuery)
		if n.ReplicaOf != nil {
			Walk(v, n.ReplicaOf)
		}
	case *CreateProcedureStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Params {
			Walk(v, c)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *CreateRoleStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *CreateRowAccessPolicyStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		for _, c := range n.Grantees {
			Walk(v, c)
		}
		Walk(v, n.Filter)
	case *CreateSchemaStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *CreateSequenceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *CreateSnapshotStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.CloneSource != nil {
			Walk(v, n.CloneSource)
		}
		Walk(v, n.ForSystemTime)
		Walk(v, n.Where)
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *CreateTableStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Columns {
			Walk(v, c)
		}
		for _, c := range n.Constraints {
			Walk(v, c)
		}
		for _, c := range n.PrimaryKey {
			Walk(v, c)
		}
		if n.Interleave != nil {
			Walk(v, n.Interleave)
		}
		Walk(v, n.RowDeletion)
		if n.Like != nil {
			Walk(v, n.Like)
		}
		if n.Clone != nil {
			Walk(v, n.Clone)
		}
		if n.Copy != nil {
			Walk(v, n.Copy)
		}
		walkNodes(v, n.PartitionBy)
		walkNodes(v, n.ClusterBy)
		for _, c := range n.Options {
			Walk(v, c)
		}
		Walk(v, n.AsQuery)
	case *CreateViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Columns {
			Walk(v, c)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
		Walk(v, n.AsQuery)
	case *DeleteStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		Walk(v, n.Where)
		Walk(v, n.AssertRows)
		if n.Returning != nil {
			Walk(v, n.Returning)
		}
	case *DescribeStmt:
		if n.Path != nil {
			Walk(v, n.Path)
		}
		if n.FromPath != nil {
			Walk(v, n.FromPath)
		}
	case *DropAllRowAccessPoliciesStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *DropChangeStreamStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropLocalityGroupStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropRoleStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropSequenceStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.OnTable != nil {
			Walk(v, n.OnTable)
		}
	case *ExistsExpr:
		Walk(v, n.Query)
	case *ExportDataStmt:
		for _, c := range n.Options {
			Walk(v, c)
		}
		Walk(v, n.Query)
	case *ExportModelStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *ExtensionAccess:
		Walk(v, n.Expr)
		if n.Path != nil {
			Walk(v, n.Path)
		}
	case *ExtractExpr:
		Walk(v, n.Part)
		Walk(v, n.From)
		Walk(v, n.TimeZone)
	case *FieldAccess:
		Walk(v, n.Expr)
	case *File:
		walkNodes(v, n.Stmts)
	case *ForeignKeyRef:
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *FuncCall:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		walkNodes(v, n.Args)
		if n.Having != nil {
			Walk(v, n.Having)
		}
		if n.Clamped != nil {
			Walk(v, n.Clamped)
		}
		for _, c := range n.OrderBy {
			Walk(v, c)
		}
		Walk(v, n.Limit)
		Walk(v, n.LimitOffset)
		if n.Over != nil {
			Walk(v, n.Over)
		}
	case *FunctionParam:
		if n.Type != nil {
			Walk(v, n.Type)
		}
		Walk(v, n.Default)
	case *GrantStmt:
		for _, c := range n.Privileges {
			Walk(v, c)
		}
		for _, c := range n.Grantees {
			Walk(v, c)
		}
	case *GroupByClause:
		for _, c := range n.Items {
			Walk(v, c)
		}
	case *GroupingItem:
		Walk(v, n.Expr)
		walkNodes(v, n.Items)
	case *HavingModifier:
		Walk(v, n.Expr)
	case *InExpr:
		Walk(v, n.Expr)
		walkNodes(v, n.Values)
		Walk(v, n.Unnest)
		Walk(v, n.Subquery)
	case *IndexAccess:
		Walk(v, n.Expr)
		Walk(v, n.Index)
	case *InsertRow:
		walkNodes(v, n.Values)
	case *InsertStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		for _, c := range n.Rows {
			Walk(v, c)
		}
		Walk(v, n.Query)
		if n.TableClause != nil {
			Walk(v, n.TableClause)
		}
		if n.OnConflict != nil {
			Walk(v, n.OnConflict)
		}
		Walk(v, n.AssertRows)
		if n.Returning != nil {
			Walk(v, n.Returning)
		}
	case *InsertTable:
		if n.Path != nil {
			Walk(v, n.Path)
		}
		if n.Func != nil {
			Walk(v, n.Func)
		}
		Walk(v, n.Where)
	case *InterleaveClause:
		if n.Parent != nil {
			Walk(v, n.Parent)
		}
	case *IntervalExpr:
		Walk(v, n.Value)
	case *IsExpr:
		Walk(v, n.Expr)
		Walk(v, n.DistinctFrom)
	case *JoinExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
		Walk(v, n.On)
	case *KeyPart:
		Walk(v, n.Expr)
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *LambdaExpr:
		Walk(v, n.Body)
	case *LikeExpr:
		Walk(v, n.Expr)
		Walk(v, n.Pattern)
		walkNodes(v, n.QuantValues)
		Walk(v, n.QuantUnnest)
		Walk(v, n.QuantSubquery)
	case *LoadDataStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, c := range n.Columns {
			Walk(v, c)
		}
		for _, c := range n.Constraints {
			Walk(v, c)
		}
		Walk(v, n.Partitions)
		walkNodes(v, n.PartitionBy)
		walkNodes(v, n.ClusterBy)
		for _, c := range n.Options {
			Walk(v, c)
		}
		for _, c := range n.FromFiles {
			Walk(v, c)
		}
		for _, c := range n.PartitionColumns {
			Walk(v, c)
		}
	case *MergeAction:
		if n.InsertRow != nil {
			Walk(v, n.InsertRow)
		}
		for _, c := range n.SetItems {
			Walk(v, c)
		}
	case *MergeStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		Walk(v, n.Source)
		Walk(v, n.On)
		for _, c := range n.Whens {
			Walk(v, c)
		}
	case *MergeWhen:
		Walk(v, n.And)
		if n.Action != nil {
			Walk(v, n.Action)
		}
	case *NamedArg:
		Walk(v, n.Value)
	case *NewConstructor:
		if n.Type != nil {
			Walk(v, n.Type)
		}
		for _, c := range n.Args {
			Walk(v, c)
		}
		if n.Braced != nil {
			Walk(v, n.Braced)
		}
	case *OnConflict:
		for _, c := range n.SetItems {
			Walk(v, c)
		}
		Walk(v, n.Where)
	case *OptionsEntry:
		Walk(v, n.Value)
	case *OrderItem:
		Walk(v, n.Expr)
		Walk(v, n.Collate)
	case *ParenExpr:
		Walk(v, n.Expr)
	case *QueryStmt:
		if n.With != nil {
			Walk(v, n.With)
		}
		Walk(v, n.Body)
		for _, c := range n.OrderBy {
			Walk(v, c)
		}
		Walk(v, n.Limit)
		Walk(v, n.Offset)
	case *RecursionDepth:
		Walk(v, n.Lower)
		Walk(v, n.Upper)
		Walk(v, n.Max)
	case *RenameStmt:
		if n.From != nil {
			Walk(v, n.From)
		}
		if n.To != nil {
			Walk(v, n.To)
		}
	case *ReplaceFieldsExpr:
		Walk(v, n.Expr)
		for _, c := range n.Items {
			Walk(v, c)
		}
	case *Returning:
		for _, c := range n.Items {
			Walk(v, c)
		}
	case *RevokeStmt:
		for _, c := range n.Privileges {
			Walk(v, c)
		}
		for _, c := range n.Grantees {
			Walk(v, c)
		}
	case *SearchVectorIndexStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Table != nil {
			Walk(v, n.Table)
		}
		for _, c := range n.Keys {
			Walk(v, c)
		}
		walkNodes(v, n.Storing)
		walkNodes(v, n.PartitionBy)
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *SelectItem:
		Walk(v, n.Expr)
		if n.Modifiers != nil {
			Walk(v, n.Modifiers)
		}
	case *SelectStmt:
		if n.AsTypeName != nil {
			Walk(v, n.AsTypeName)
		}
		for _, c := range n.Items {
			Walk(v, c)
		}
		walkNodes(v, n.From)
		Walk(v, n.Where)
		if n.GroupBy != nil {
			Walk(v, n.GroupBy)
		}
		Walk(v, n.Having)
		Walk(v, n.Qualify)
		for _, c := range n.Window {
			Walk(v, c)
		}
	case *SequenceArg:
		if n.Path != nil {
			Walk(v, n.Path)
		}
	case *SetOperation:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *StarExpr:
		if n.Modifiers != nil {
			Walk(v, n.Modifiers)
		}
	case *StarModifiers:
		for _, c := range n.Replace {
			Walk(v, c)
		}
	case *StructExpr:
		if n.Type != nil {
			Walk(v, n.Type)
		}
		for _, c := range n.Fields {
			Walk(v, c)
		}
	case *StructFieldExpr:
		Walk(v, n.Value)
	case *SubqueryExpr:
		Walk(v, n.Query)
	case *TableAndColumnInfo:
		if n.Path != nil {
			Walk(v, n.Path)
		}
	case *TableConstraint:
		for _, c := range n.KeyParts {
			Walk(v, c)
		}
		if n.ForeignKey != nil {
			Walk(v, n.ForeignKey)
		}
		Walk(v, n.Check)
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *TableExpr:
		if n.Path != nil {
			Walk(v, n.Path)
		}
		Walk(v, n.Subquery)
		if n.Func != nil {
			Walk(v, n.Func)
		}
		Walk(v, n.SystemTime)
	case *TransactionStmt:
		for _, c := range n.Modes {
			Walk(v, c)
		}
	case *TruncateStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		Walk(v, n.Where)
	case *UnaryExpr:
		Walk(v, n.Expr)
	case *UnnestExpr:
		Walk(v, n.Array)
	case *UpdateItem:
		Walk(v, n.Value)
		Walk(v, n.Nested)
	case *UpdateStmt:
		if n.Target != nil {
			Walk(v, n.Target)
		}
		for _, c := range n.Items {
			Walk(v, c)
		}
		walkNodes(v, n.From)
		Walk(v, n.Where)
		Walk(v, n.AssertRows)
		if n.Returning != nil {
			Walk(v, n.Returning)
		}
	case *ViewColumn:
		for _, c := range n.Options {
			Walk(v, c)
		}
	case *WhenClause:
		Walk(v, n.Cond)
		Walk(v, n.Result)
	case *WindowDef:
		if n.Spec != nil {
			Walk(v, n.Spec)
		}
	case *WindowFrame:
		Walk(v, n.Start.Offset)
		Walk(v, n.End.Offset)
	case *WindowSpec:
		walkNodes(v, n.PartitionBy)
		for _, c := range n.OrderBy {
			Walk(v, c)
		}
		if n.Frame != nil {
			Walk(v, n.Frame)
		}
	case *WithClause:
		for _, c := range n.CTEs {
			Walk(v, c)
		}
	case *WithExpr:
		for _, c := range n.Vars {
			Walk(v, c)
		}
		Walk(v, n.Body)
	}
}
