package parser

// keywords maps lowercase keyword strings to their token types.
// CQL keywords are case-insensitive.
var keywords = map[string]int{
	"access":               tokACCESS,
	"add":                  tokADD,
	"aggregate":            tokAGGREGATE,
	"all":                  tokALL,
	"allow":                tokALLOW,
	"alter":                tokALTER,
	"and":                  tokAND,
	"ann":                  tokANN,
	"apply":                tokAPPLY,
	"as":                   tokAS,
	"asc":                  tokASC,
	"ascii":                tokASCII,
	"authorize":            tokAUTHORIZE,
	"batch":                tokBATCH,
	"begin":                tokBEGIN,
	"bigint":               tokBIGINT,
	"blob":                 tokBLOB,
	"boolean":              tokBOOLEAN,
	"by":                   tokBY,
	"called":               tokCALLED,
	"cast":                 tokCAST,
	"clustering":           tokCLUSTERING,
	"compact":              tokCOMPACT,
	"contains":             tokCONTAINS,
	"counter":              tokCOUNTER,
	"create":               tokCREATE,
	"currentdate":          tokCURRENTDATE,
	"currenttime":          tokCURRENTTIME,
	"currenttimestamp":     tokCURRENTTIMESTAMP,
	"currenttimeuuid":      tokCURRENTTIMEUUID,
	"custom":               tokCUSTOM,
	"datacenters":          tokDATACENTERS,
	"date":                 tokDATE,
	"datetimenow":          tokDATETIMENOW,
	"decimal":              tokDECIMAL,
	"default":              tokDEFAULT,
	"delete":               tokDELETE,
	"desc":                 tokDESC,
	"describe":             tokDESCRIBE,
	"distinct":             tokDISTINCT,
	"double":               tokDOUBLE,
	"drop":                 tokDROP,
	"durable_writes":       tokDURABLE_WRITES,
	"duration":             tokDURATION,
	"entries":              tokENTRIES,
	"execute":              tokEXECUTE,
	"exists":               tokEXISTS,
	"false":                tokFALSE,
	"filtering":            tokFILTERING,
	"finalfunc":            tokFINALFUNC,
	"float":                tokFLOATKW,
	"from":                 tokFROM,
	"fromjson":             tokFROMJSON,
	"frozen":               tokFROZEN,
	"full":                 tokFULL,
	"function":             tokFUNCTION,
	"functions":            tokFUNCTIONS,
	"grant":                tokGRANT,
	"group":                tokGROUP,
	"hashed":               tokHASHED,
	"if":                   tokIF,
	"in":                   tokIN,
	"index":                tokINDEX,
	"inet":                 tokINET,
	"infinity":             tokINFINITY,
	"initcond":             tokINITCOND,
	"input":                tokINPUT,
	"insert":               tokINSERT,
	"int":                  tokINT,
	"into":                 tokINTO,
	"is":                   tokIS,
	"json":                 tokJSON,
	"key":                  tokKEY,
	"keys":                 tokKEYS,
	"keyspace":             tokKEYSPACE,
	"keyspaces":            tokKEYSPACES,
	"language":             tokLANGUAGE,
	"limit":                tokLIMIT,
	"list":                 tokLIST,
	"logged":               tokLOGGED,
	"login":                tokLOGIN,
	"map":                  tokMAP,
	"materialized":         tokMATERIALIZED,
	"mbean":                tokMBEAN,
	"mbeans":               tokMBEANS,
	"maxtimeuuid":          tokMAXTIMEUUID,
	"mintimeuuid":          tokMINTIMEUUID,
	"modify":               tokMODIFY,
	"nan":                  tokNAN,
	"norecursive":          tokNORECURSIVE,
	"nosuperuser":          tokNOSUPERUSER,
	"not":                  tokNOT,
	"now":                  tokNOW,
	"null":                 tokNULL,
	"of":                   tokOF,
	"on":                   tokON,
	"options":              tokOPTIONS,
	"or":                   tokOR,
	"order":                tokORDER,
	"partition":            tokPARTITION,
	"password":             tokPASSWORD,
	"per":                  tokPER,
	"permission":           tokPERMISSION,
	"permissions":          tokPERMISSIONS,
	"primary":              tokPRIMARY,
	"rename":               tokRENAME,
	"replace":              tokREPLACE,
	"replication":          tokREPLICATION,
	"returns":              tokRETURNS,
	"revoke":               tokREVOKE,
	"role":                 tokROLE,
	"roles":                tokROLES,
	"sai":                  tokSAI,
	"select":               tokSELECT,
	"set":                  tokSET,
	"sfunc":                tokSFUNC,
	"smallint":             tokSMALLINT,
	"static":               tokSTATIC,
	"storage":              tokSTORAGE,
	"storageattachedindex": tokSTORAGEATTACHEDINDEX,
	"stype":                tokSTYPE,
	"superuser":            tokSUPERUSER,
	"table":                tokTABLE,
	"text":                 tokTEXT,
	"time":                 tokTIME,
	"timestamp":            tokTIMESTAMP,
	"timeuuid":             tokTIMEUUID,
	"tinyint":              tokTINYINT,
	"to":                   tokTO,
	"tojson":               tokTOJSON,
	"trigger":              tokTRIGGER,
	"true":                 tokTRUE,
	"truncate":             tokTRUNCATE,
	"ttl":                  tokTTL,
	"tuple":                tokTUPLE,
	"type":                 tokTYPE,
	"unlogged":             tokUNLOGGED,
	"unset":                tokUNSET,
	"update":               tokUPDATE,
	"use":                  tokUSE,
	"user":                 tokUSER,
	"using":                tokUSING,
	"uuid":                 tokUUID_KW,
	"values":               tokVALUES,
	"varchar":              tokVARCHAR,
	"varint":               tokVARINT,
	"vector":               tokVECTOR,
	"view":                 tokVIEW,
	"where":                tokWHERE,
	"with":                 tokWITH,
}

// isKeyword returns true if the token type is a keyword.
func isKeyword(tok int) bool {
	return tok >= 3000
}

// isIdentLike returns true if the token is an identifier or a keyword that
// can be used as an identifier in certain contexts (like column/table names).
func isIdentLike(tok int) bool {
	return tok == tokIDENT || tok == tokQUOTED || isKeyword(tok)
}
