package parser

import (
	"strings"
	"testing"
)

// mysql8KeywordCategory matches the 6-category keyword system in MySQL 8.0's sql_yacc.yy.
type mysql8KeywordCategory string

const (
	catReserved    mysql8KeywordCategory = "reserved"
	catUnambiguous mysql8KeywordCategory = "unambiguous"
	catAmbiguous1  mysql8KeywordCategory = "ambiguous_1"
	catAmbiguous2  mysql8KeywordCategory = "ambiguous_2"
	catAmbiguous3  mysql8KeywordCategory = "ambiguous_3"
	catAmbiguous4  mysql8KeywordCategory = "ambiguous_4"
	catOperator    mysql8KeywordCategory = "operator"
	catHint        mysql8KeywordCategory = "hint"
)

type mysql8Keyword struct {
	SQL      string
	Category mysql8KeywordCategory
}

// mysql8Keywords is the golden list of ALL MySQL 8.0 keywords extracted from
// mysql-server/sql/lex.h (SYM/SYM_FN/SYM_HK/SYM_H entries) and classified
// per mysql-server/sql/sql_yacc.yy token declarations and ident_keywords_* rules.
//
// This list is the ground truth. Tests verify omni's keyword map and classification
// match this list exactly.
//
// 848 entries total. Sorted alphabetically by SQL string.
var mysql8Keywords = []mysql8Keyword{
	{"!=", catOperator},
	{"&&", catOperator},
	{"<", catOperator},
	{"<<", catOperator},
	{"<=", catOperator},
	{"<=>", catOperator},
	{"<>", catOperator},
	{"=", catOperator},
	{">", catOperator},
	{">=", catOperator},
	{">>", catOperator},
	{"absent", catUnambiguous},
	{"accessible", catReserved},
	{"account", catUnambiguous},
	{"action", catUnambiguous},
	{"active", catUnambiguous},
	{"add", catReserved},
	{"adddate", catUnambiguous},
	{"admin", catUnambiguous},
	{"after", catUnambiguous},
	{"against", catUnambiguous},
	{"aggregate", catUnambiguous},
	{"algorithm", catUnambiguous},
	{"all", catReserved},
	{"allow_missing_files", catUnambiguous},
	{"alter", catReserved},
	{"always", catUnambiguous},
	{"analyze", catReserved},
	{"and", catReserved},
	{"any", catUnambiguous},
	{"array", catUnambiguous},
	{"as", catReserved},
	{"asc", catReserved},
	{"ascii", catAmbiguous2},
	{"asensitive", catReserved},
	{"assign_gtids_to_anonymous_transactions", catUnambiguous},
	{"at", catUnambiguous},
	{"attribute", catUnambiguous},
	{"authentication", catUnambiguous},
	{"auto", catUnambiguous},
	{"auto_increment", catUnambiguous},
	{"auto_refresh", catUnambiguous},
	{"auto_refresh_source", catUnambiguous},
	{"autoextend_size", catUnambiguous},
	{"avg", catUnambiguous},
	{"avg_row_length", catUnambiguous},
	{"backup", catUnambiguous},
	{"before", catReserved},
	{"begin", catAmbiguous2},
	{"bernoulli", catUnambiguous},
	{"between", catReserved},
	{"bigint", catReserved},
	{"binary", catReserved},
	{"binlog", catAmbiguous2},
	{"bit", catUnambiguous},
	{"bit_and", catReserved},
	{"bit_or", catReserved},
	{"bit_xor", catReserved},
	{"bka", catHint},
	{"blob", catReserved},
	{"block", catUnambiguous},
	{"bnl", catHint},
	{"bool", catUnambiguous},
	{"boolean", catUnambiguous},
	{"both", catReserved},
	{"btree", catUnambiguous},
	{"buckets", catUnambiguous},
	{"bulk", catUnambiguous},
	{"by", catReserved},
	{"byte", catAmbiguous2},
	{"cache", catAmbiguous2},
	{"call", catReserved},
	{"cascade", catReserved},
	{"cascaded", catUnambiguous},
	{"case", catReserved},
	{"cast", catReserved},
	{"catalog_name", catUnambiguous},
	{"chain", catUnambiguous},
	{"challenge_response", catUnambiguous},
	{"change", catReserved},
	{"changed", catUnambiguous},
	{"channel", catUnambiguous},
	{"char", catReserved},
	{"character", catReserved},
	{"charset", catAmbiguous2},
	{"check", catReserved},
	{"checksum", catAmbiguous2},
	{"cipher", catUnambiguous},
	{"class_origin", catUnambiguous},
	{"client", catUnambiguous},
	{"clone", catAmbiguous2},
	{"close", catUnambiguous},
	{"coalesce", catUnambiguous},
	{"code", catUnambiguous},
	{"collate", catReserved},
	{"collation", catUnambiguous},
	{"column", catReserved},
	{"column_format", catUnambiguous},
	{"column_name", catUnambiguous},
	{"columns", catUnambiguous},
	{"comment", catAmbiguous2},
	{"commit", catAmbiguous2},
	{"committed", catUnambiguous},
	{"compact", catUnambiguous},
	{"completion", catUnambiguous},
	{"component", catUnambiguous},
	{"compressed", catUnambiguous},
	{"compression", catUnambiguous},
	{"concurrent", catUnambiguous},
	{"condition", catReserved},
	{"connection", catUnambiguous},
	{"consistent", catUnambiguous},
	{"constraint", catReserved},
	{"constraint_catalog", catUnambiguous},
	{"constraint_name", catUnambiguous},
	{"constraint_schema", catUnambiguous},
	{"contains", catAmbiguous2},
	{"context", catUnambiguous},
	{"continue", catReserved},
	{"convert", catReserved},
	{"count", catReserved},
	{"cpu", catUnambiguous},
	{"create", catReserved},
	{"cross", catReserved},
	{"cube", catReserved},
	{"cume_dist", catReserved},
	{"curdate", catReserved},
	{"current", catUnambiguous},
	{"current_date", catReserved},
	{"current_time", catReserved},
	{"current_timestamp", catReserved},
	{"current_user", catReserved},
	{"cursor", catReserved},
	{"cursor_name", catUnambiguous},
	{"curtime", catReserved},
	{"data", catUnambiguous},
	{"database", catReserved},
	{"databases", catReserved},
	{"datafile", catUnambiguous},
	{"date", catUnambiguous},
	{"date_add", catReserved},
	{"date_sub", catReserved},
	{"datetime", catUnambiguous},
	{"day", catUnambiguous},
	{"day_hour", catReserved},
	{"day_microsecond", catReserved},
	{"day_minute", catReserved},
	{"day_second", catReserved},
	{"deallocate", catAmbiguous2},
	{"dec", catReserved},
	{"decimal", catReserved},
	{"declare", catReserved},
	{"default", catReserved},
	{"default_auth", catUnambiguous},
	{"definer", catUnambiguous},
	{"definition", catUnambiguous},
	{"delay_key_write", catUnambiguous},
	{"delayed", catReserved},
	{"delete", catReserved},
	{"dense_rank", catReserved},
	{"derived_condition_pushdown", catHint},
	{"desc", catReserved},
	{"describe", catReserved},
	{"description", catUnambiguous},
	{"deterministic", catReserved},
	{"diagnostics", catUnambiguous},
	{"directory", catUnambiguous},
	{"disable", catUnambiguous},
	{"discard", catUnambiguous},
	{"disk", catUnambiguous},
	{"distinct", catReserved},
	{"distinctrow", catReserved},
	{"div", catReserved},
	{"do", catAmbiguous2},
	{"double", catReserved},
	{"drop", catReserved},
	{"dual", catReserved},
	{"duality", catUnambiguous},
	{"dumpfile", catUnambiguous},
	{"duplicate", catUnambiguous},
	{"dupsweedout", catHint},
	{"dynamic", catUnambiguous},
	{"each", catReserved},
	{"else", catReserved},
	{"elseif", catReserved},
	{"empty", catReserved},
	{"enable", catUnambiguous},
	{"enclosed", catReserved},
	{"encryption", catUnambiguous},
	{"end", catAmbiguous2},
	{"ends", catUnambiguous},
	{"enforced", catUnambiguous},
	{"engine", catUnambiguous},
	{"engine_attribute", catUnambiguous},
	{"engines", catUnambiguous},
	{"enum", catUnambiguous},
	{"error", catUnambiguous},
	{"errors", catUnambiguous},
	{"escape", catUnambiguous},
	{"escaped", catReserved},
	{"event", catAmbiguous3},
	{"events", catUnambiguous},
	{"every", catUnambiguous},
	{"except", catReserved},
	{"exchange", catUnambiguous},
	{"exclude", catUnambiguous},
	{"execute", catAmbiguous1},
	{"exists", catReserved},
	{"exit", catReserved},
	{"expansion", catUnambiguous},
	{"expire", catUnambiguous},
	{"explain", catReserved},
	{"export", catUnambiguous},
	{"extended", catUnambiguous},
	{"extent_size", catUnambiguous},
	{"external", catReserved},
	{"external_format", catUnambiguous},
	{"extract", catReserved},
	{"factor", catUnambiguous},
	{"failed_login_attempts", catUnambiguous},
	{"false", catReserved},
	{"fast", catUnambiguous},
	{"faults", catUnambiguous},
	{"fetch", catReserved},
	{"fields", catUnambiguous},
	{"file", catAmbiguous3},
	{"file_block_size", catUnambiguous},
	{"file_format", catUnambiguous},
	{"file_name", catUnambiguous},
	{"file_pattern", catUnambiguous},
	{"file_prefix", catUnambiguous},
	{"files", catUnambiguous},
	{"filter", catUnambiguous},
	{"finish", catUnambiguous},
	{"first", catUnambiguous},
	{"first_value", catReserved},
	{"firstmatch", catHint},
	{"fixed", catUnambiguous},
	{"float", catReserved},
	{"float4", catReserved},
	{"float8", catReserved},
	{"flush", catAmbiguous2},
	{"following", catUnambiguous},
	{"follows", catAmbiguous2},
	{"for", catReserved},
	{"force", catReserved},
	{"foreign", catReserved},
	{"format", catUnambiguous},
	{"found", catUnambiguous},
	{"from", catReserved},
	{"full", catUnambiguous},
	{"fulltext", catReserved},
	{"function", catReserved},
	{"general", catUnambiguous},
	{"generate", catUnambiguous},
	{"generated", catReserved},
	{"geomcollection", catUnambiguous},
	{"geometry", catUnambiguous},
	{"geometrycollection", catUnambiguous},
	{"get", catReserved},
	{"get_format", catUnambiguous},
	{"get_source_public_key", catUnambiguous},
	{"global", catAmbiguous4},
	{"grant", catReserved},
	{"grants", catUnambiguous},
	{"group", catReserved},
	{"group_concat", catReserved},
	{"group_index", catHint},
	{"group_replication", catUnambiguous},
	{"grouping", catReserved},
	{"groups", catReserved},
	{"gtid_only", catUnambiguous},
	{"gtids", catUnambiguous},
	{"guided", catUnambiguous},
	{"handler", catAmbiguous2},
	{"hash", catUnambiguous},
	{"hash_join", catHint},
	{"having", catReserved},
	{"header", catUnambiguous},
	{"help", catAmbiguous2},
	{"high_priority", catReserved},
	{"histogram", catUnambiguous},
	{"history", catUnambiguous},
	{"host", catUnambiguous},
	{"hosts", catUnambiguous},
	{"hour", catUnambiguous},
	{"hour_microsecond", catReserved},
	{"hour_minute", catReserved},
	{"hour_second", catReserved},
	{"identified", catUnambiguous},
	{"if", catReserved},
	{"ignore", catReserved},
	{"ignore_server_ids", catUnambiguous},
	{"import", catAmbiguous2},
	{"in", catReserved},
	{"inactive", catUnambiguous},
	{"index", catReserved},
	{"index_merge", catHint},
	{"indexes", catUnambiguous},
	{"infile", catReserved},
	{"initial", catUnambiguous},
	{"initial_size", catUnambiguous},
	{"initiate", catUnambiguous},
	{"inner", catReserved},
	{"inout", catReserved},
	{"insensitive", catReserved},
	{"insert", catReserved},
	{"insert_method", catUnambiguous},
	{"install", catAmbiguous2},
	{"instance", catUnambiguous},
	{"int", catReserved},
	{"int1", catReserved},
	{"int2", catReserved},
	{"int3", catReserved},
	{"int4", catReserved},
	{"int8", catReserved},
	{"integer", catReserved},
	{"intersect", catReserved},
	{"interval", catReserved},
	{"into", catReserved},
	{"intoexists", catHint},
	{"invisible", catUnambiguous},
	{"invoker", catUnambiguous},
	{"io", catUnambiguous},
	{"io_after_gtids", catReserved},
	{"io_before_gtids", catReserved},
	{"io_thread", catUnambiguous},
	{"ipc", catUnambiguous},
	{"is", catReserved},
	{"isolation", catUnambiguous},
	{"issuer", catUnambiguous},
	{"iterate", catReserved},
	{"join", catReserved},
	{"join_fixed_order", catHint},
	{"join_index", catHint},
	{"join_order", catHint},
	{"join_prefix", catHint},
	{"join_suffix", catHint},
	{"json", catUnambiguous},
	{"json_arrayagg", catReserved},
	{"json_duality_object", catReserved},
	{"json_objectagg", catReserved},
	{"json_table", catReserved},
	{"json_value", catUnambiguous},
	{"key", catReserved},
	{"key_block_size", catUnambiguous},
	{"keyring", catUnambiguous},
	{"keys", catReserved},
	{"kill", catReserved},
	{"lag", catReserved},
	{"language", catAmbiguous2},
	{"last", catUnambiguous},
	{"last_value", catReserved},
	{"lateral", catReserved},
	{"lead", catReserved},
	{"leading", catReserved},
	{"leave", catReserved},
	{"leaves", catUnambiguous},
	{"left", catReserved},
	{"less", catUnambiguous},
	{"level", catUnambiguous},
	{"library", catReserved},
	{"like", catReserved},
	{"limit", catReserved},
	{"linear", catReserved},
	{"lines", catReserved},
	{"linestring", catUnambiguous},
	{"list", catUnambiguous},
	{"load", catReserved},
	{"local", catAmbiguous4},
	{"localtime", catReserved},
	{"localtimestamp", catReserved},
	{"lock", catReserved},
	{"locked", catUnambiguous},
	{"locks", catUnambiguous},
	{"log", catUnambiguous},
	{"logfile", catUnambiguous},
	{"logs", catUnambiguous},
	{"long", catReserved},
	{"longblob", catReserved},
	{"longtext", catReserved},
	{"loop", catReserved},
	{"loosescan", catHint},
	{"low_priority", catReserved},
	{"manual", catReserved},
	{"master", catUnambiguous},
	{"match", catReserved},
	{"materialization", catHint},
	{"materialized", catUnambiguous},
	{"max", catReserved},
	{"max_connections_per_hour", catUnambiguous},
	{"max_execution_time", catHint},
	{"max_queries_per_hour", catUnambiguous},
	{"max_rows", catUnambiguous},
	{"max_size", catUnambiguous},
	{"max_updates_per_hour", catUnambiguous},
	{"max_user_connections", catUnambiguous},
	{"maxvalue", catReserved},
	{"medium", catUnambiguous},
	{"mediumblob", catReserved},
	{"mediumint", catReserved},
	{"mediumtext", catReserved},
	{"member", catUnambiguous},
	{"memory", catUnambiguous},
	{"merge", catUnambiguous},
	{"message_text", catUnambiguous},
	{"microsecond", catUnambiguous},
	{"mid", catReserved},
	{"middleint", catReserved},
	{"migrate", catUnambiguous},
	{"min", catReserved},
	{"min_rows", catUnambiguous},
	{"minute", catUnambiguous},
	{"minute_microsecond", catReserved},
	{"minute_second", catReserved},
	{"mod", catReserved},
	{"mode", catUnambiguous},
	{"modifies", catReserved},
	{"modify", catUnambiguous},
	{"month", catUnambiguous},
	{"mrr", catHint},
	{"multilinestring", catUnambiguous},
	{"multipoint", catUnambiguous},
	{"multipolygon", catUnambiguous},
	{"mutex", catUnambiguous},
	{"mysql_errno", catUnambiguous},
	{"name", catUnambiguous},
	{"names", catUnambiguous},
	{"national", catUnambiguous},
	{"natural", catReserved},
	{"nchar", catUnambiguous},
	{"ndb", catUnambiguous},
	{"ndbcluster", catUnambiguous},
	{"nested", catUnambiguous},
	{"network_namespace", catUnambiguous},
	{"never", catUnambiguous},
	{"new", catUnambiguous},
	{"next", catUnambiguous},
	{"no", catAmbiguous2},
	{"no_bka", catHint},
	{"no_bnl", catHint},
	{"no_derived_condition_pushdown", catHint},
	{"no_group_index", catHint},
	{"no_hash_join", catHint},
	{"no_icp", catHint},
	{"no_index", catHint},
	{"no_index_merge", catHint},
	{"no_join_index", catHint},
	{"no_merge", catHint},
	{"no_mrr", catHint},
	{"no_order_index", catHint},
	{"no_range_optimization", catHint},
	{"no_semijoin", catHint},
	{"no_skip_scan", catHint},
	{"no_wait", catUnambiguous},
	{"no_write_to_binlog", catReserved},
	{"nodegroup", catUnambiguous},
	{"none", catAmbiguous3},
	{"not", catReserved},
	{"now", catReserved},
	{"nowait", catUnambiguous},
	{"nth_value", catReserved},
	{"ntile", catReserved},
	{"null", catReserved},
	{"nulls", catUnambiguous},
	{"number", catUnambiguous},
	{"numeric", catReserved},
	{"nvarchar", catUnambiguous},
	{"of", catReserved},
	{"off", catUnambiguous},
	{"offset", catUnambiguous},
	{"oj", catUnambiguous},
	{"old", catUnambiguous},
	{"on", catReserved},
	{"one", catUnambiguous},
	{"only", catUnambiguous},
	{"open", catUnambiguous},
	{"optimize", catReserved},
	{"optimizer_costs", catReserved},
	{"option", catReserved},
	{"optional", catUnambiguous},
	{"optionally", catReserved},
	{"options", catUnambiguous},
	{"or", catReserved},
	{"order", catReserved},
	{"order_index", catHint},
	{"ordinality", catUnambiguous},
	{"organization", catUnambiguous},
	{"others", catUnambiguous},
	{"out", catReserved},
	{"outer", catReserved},
	{"outfile", catReserved},
	{"over", catReserved},
	{"owner", catUnambiguous},
	{"pack_keys", catUnambiguous},
	{"page", catUnambiguous},
	{"parallel", catReserved},
	{"parameters", catUnambiguous},
	{"parse_tree", catUnambiguous},
	{"parser", catUnambiguous},
	{"partial", catUnambiguous},
	{"partition", catReserved},
	{"partitioning", catUnambiguous},
	{"partitions", catUnambiguous},
	{"password", catUnambiguous},
	{"password_lock_time", catUnambiguous},
	{"path", catUnambiguous},
	{"percent_rank", catReserved},
	{"persist", catAmbiguous4},
	{"persist_only", catAmbiguous4},
	{"phase", catUnambiguous},
	{"plugin", catUnambiguous},
	{"plugin_dir", catUnambiguous},
	{"plugins", catUnambiguous},
	{"point", catUnambiguous},
	{"polygon", catUnambiguous},
	{"port", catUnambiguous},
	{"position", catReserved},
	{"precedes", catAmbiguous2},
	{"preceding", catUnambiguous},
	{"precision", catReserved},
	{"prepare", catAmbiguous2},
	{"preserve", catUnambiguous},
	{"prev", catUnambiguous},
	{"primary", catReserved},
	{"privilege_checks_user", catUnambiguous},
	{"privileges", catUnambiguous},
	{"procedure", catReserved},
	{"process", catAmbiguous3},
	{"processlist", catUnambiguous},
	{"profile", catUnambiguous},
	{"profiles", catUnambiguous},
	{"proxy", catAmbiguous3},
	{"purge", catReserved},
	{"qb_name", catHint},
	{"qualify", catReserved},
	{"quarter", catUnambiguous},
	{"query", catUnambiguous},
	{"quick", catUnambiguous},
	{"random", catUnambiguous},
	{"range", catReserved},
	{"rank", catReserved},
	{"read", catReserved},
	{"read_only", catUnambiguous},
	{"read_write", catReserved},
	{"reads", catReserved},
	{"real", catReserved},
	{"rebuild", catUnambiguous},
	{"recover", catUnambiguous},
	{"recursive", catReserved},
	{"redo_buffer_size", catUnambiguous},
	{"redundant", catUnambiguous},
	{"reference", catUnambiguous},
	{"references", catReserved},
	{"regexp", catReserved},
	{"registration", catUnambiguous},
	{"relational", catUnambiguous},
	{"relay", catUnambiguous},
	{"relay_log_file", catUnambiguous},
	{"relay_log_pos", catUnambiguous},
	{"relay_thread", catUnambiguous},
	{"relaylog", catUnambiguous},
	{"release", catReserved},
	{"reload", catAmbiguous3},
	{"remove", catUnambiguous},
	{"rename", catReserved},
	{"reorganize", catUnambiguous},
	{"repair", catAmbiguous2},
	{"repeat", catReserved},
	{"repeatable", catUnambiguous},
	{"replace", catReserved},
	{"replica", catUnambiguous},
	{"replicas", catUnambiguous},
	{"replicate_do_db", catUnambiguous},
	{"replicate_do_table", catUnambiguous},
	{"replicate_ignore_db", catUnambiguous},
	{"replicate_ignore_table", catUnambiguous},
	{"replicate_rewrite_db", catUnambiguous},
	{"replicate_wild_do_table", catUnambiguous},
	{"replicate_wild_ignore_table", catUnambiguous},
	{"replication", catAmbiguous3},
	{"require", catReserved},
	{"require_row_format", catUnambiguous},
	{"require_table_primary_key_check", catUnambiguous},
	{"reset", catAmbiguous2},
	{"resignal", catReserved},
	{"resource", catAmbiguous3},
	{"resource_group", catHint},
	{"respect", catUnambiguous},
	{"restart", catAmbiguous1},
	{"restore", catUnambiguous},
	{"restrict", catReserved},
	{"resume", catUnambiguous},
	{"retain", catUnambiguous},
	{"return", catReserved},
	{"returned_sqlstate", catUnambiguous},
	{"returning", catUnambiguous},
	{"returns", catUnambiguous},
	{"reuse", catUnambiguous},
	{"reverse", catUnambiguous},
	{"revoke", catReserved},
	{"right", catReserved},
	{"rlike", catReserved},
	{"role", catUnambiguous},
	{"rollback", catAmbiguous2},
	{"rollup", catUnambiguous},
	{"rotate", catUnambiguous},
	{"routine", catUnambiguous},
	{"row", catReserved},
	{"row_count", catUnambiguous},
	{"row_format", catUnambiguous},
	{"row_number", catReserved},
	{"rows", catReserved},
	{"rtree", catUnambiguous},
	{"s3", catUnambiguous},
	{"savepoint", catAmbiguous2},
	{"schedule", catUnambiguous},
	{"schema", catReserved},
	{"schema_name", catUnambiguous},
	{"schemas", catReserved},
	{"second", catUnambiguous},
	{"second_microsecond", catReserved},
	{"secondary", catUnambiguous},
	{"secondary_engine", catUnambiguous},
	{"secondary_engine_attribute", catUnambiguous},
	{"secondary_load", catUnambiguous},
	{"secondary_unload", catUnambiguous},
	{"security", catUnambiguous},
	{"select", catReserved},
	{"semijoin", catHint},
	{"sensitive", catReserved},
	{"separator", catReserved},
	{"serial", catUnambiguous},
	{"serializable", catUnambiguous},
	{"server", catUnambiguous},
	{"session", catAmbiguous4},
	{"session_user", catUnambiguous},
	{"set", catReserved},
	{"set_var", catHint},
	{"sets", catReserved},
	{"share", catUnambiguous},
	{"show", catReserved},
	{"shutdown", catAmbiguous1},
	{"signal", catReserved},
	{"signed", catAmbiguous2},
	{"simple", catUnambiguous},
	{"skip", catUnambiguous},
	{"skip_scan", catHint},
	{"slave", catAmbiguous2},
	{"slow", catUnambiguous},
	{"smallint", catReserved},
	{"snapshot", catUnambiguous},
	{"socket", catUnambiguous},
	{"some", catUnambiguous},
	{"soname", catUnambiguous},
	{"sounds", catUnambiguous},
	{"source", catUnambiguous},
	{"source_auto_position", catUnambiguous},
	{"source_bind", catUnambiguous},
	{"source_compression_algorithms", catUnambiguous},
	{"source_connect_retry", catUnambiguous},
	{"source_connection_auto_failover", catUnambiguous},
	{"source_delay", catUnambiguous},
	{"source_heartbeat_period", catUnambiguous},
	{"source_host", catUnambiguous},
	{"source_log_file", catUnambiguous},
	{"source_log_pos", catUnambiguous},
	{"source_password", catUnambiguous},
	{"source_port", catUnambiguous},
	{"source_public_key_path", catUnambiguous},
	{"source_retry_count", catUnambiguous},
	{"source_ssl", catUnambiguous},
	{"source_ssl_ca", catUnambiguous},
	{"source_ssl_capath", catUnambiguous},
	{"source_ssl_cert", catUnambiguous},
	{"source_ssl_cipher", catUnambiguous},
	{"source_ssl_crl", catUnambiguous},
	{"source_ssl_crlpath", catUnambiguous},
	{"source_ssl_key", catUnambiguous},
	{"source_ssl_verify_server_cert", catUnambiguous},
	{"source_tls_ciphersuites", catUnambiguous},
	{"source_tls_version", catUnambiguous},
	{"source_user", catUnambiguous},
	{"source_zstd_compression_level", catUnambiguous},
	{"spatial", catReserved},
	{"specific", catReserved},
	{"sql", catReserved},
	{"sql_after_gtids", catUnambiguous},
	{"sql_after_mts_gaps", catUnambiguous},
	{"sql_before_gtids", catUnambiguous},
	{"sql_big_result", catReserved},
	{"sql_buffer_result", catUnambiguous},
	{"sql_calc_found_rows", catReserved},
	{"sql_no_cache", catUnambiguous},
	{"sql_small_result", catReserved},
	{"sql_thread", catUnambiguous},
	{"sql_tsi_day", catUnambiguous},
	{"sql_tsi_hour", catUnambiguous},
	{"sql_tsi_minute", catUnambiguous},
	{"sql_tsi_month", catUnambiguous},
	{"sql_tsi_quarter", catUnambiguous},
	{"sql_tsi_second", catUnambiguous},
	{"sql_tsi_week", catUnambiguous},
	{"sql_tsi_year", catUnambiguous},
	{"sqlexception", catReserved},
	{"sqlstate", catReserved},
	{"sqlwarning", catReserved},
	{"srid", catUnambiguous},
	{"ssl", catReserved},
	{"st_collect", catUnambiguous},
	{"stacked", catUnambiguous},
	{"start", catAmbiguous2},
	{"starting", catReserved},
	{"starts", catUnambiguous},
	{"stats_auto_recalc", catUnambiguous},
	{"stats_persistent", catUnambiguous},
	{"stats_sample_pages", catUnambiguous},
	{"status", catUnambiguous},
	{"std", catReserved},
	{"stddev", catReserved},
	{"stddev_pop", catReserved},
	{"stddev_samp", catReserved},
	{"stop", catAmbiguous2},
	{"storage", catUnambiguous},
	{"stored", catReserved},
	{"straight_join", catReserved},
	{"stream", catUnambiguous},
	{"strict_load", catUnambiguous},
	{"string", catUnambiguous},
	{"subclass_origin", catUnambiguous},
	{"subdate", catUnambiguous},
	{"subject", catUnambiguous},
	{"subpartition", catUnambiguous},
	{"subpartitions", catUnambiguous},
	{"subquery", catHint},
	{"substr", catReserved},
	{"substring", catReserved},
	{"sum", catReserved},
	{"super", catAmbiguous3},
	{"suspend", catUnambiguous},
	{"swaps", catUnambiguous},
	{"switches", catUnambiguous},
	{"sysdate", catReserved},
	{"system", catReserved},
	{"system_user", catUnambiguous},
	{"table", catReserved},
	{"table_checksum", catUnambiguous},
	{"table_name", catUnambiguous},
	{"tables", catUnambiguous},
	{"tablesample", catReserved},
	{"tablespace", catUnambiguous},
	{"temporary", catUnambiguous},
	{"temptable", catUnambiguous},
	{"terminated", catReserved},
	{"text", catUnambiguous},
	{"than", catUnambiguous},
	{"then", catReserved},
	{"thread_priority", catUnambiguous},
	{"ties", catUnambiguous},
	{"time", catUnambiguous},
	{"timestamp", catUnambiguous},
	{"timestampadd", catUnambiguous},
	{"timestampdiff", catUnambiguous},
	{"tinyblob", catReserved},
	{"tinyint", catReserved},
	{"tinytext", catReserved},
	{"tls", catUnambiguous},
	{"to", catReserved},
	{"trailing", catReserved},
	{"transaction", catUnambiguous},
	{"trigger", catReserved},
	{"triggers", catUnambiguous},
	{"trim", catReserved},
	{"true", catReserved},
	{"truncate", catAmbiguous2},
	{"type", catUnambiguous},
	{"types", catUnambiguous},
	{"unbounded", catUnambiguous},
	{"uncommitted", catUnambiguous},
	{"undefined", catUnambiguous},
	{"undo", catReserved},
	{"undo_buffer_size", catUnambiguous},
	{"undofile", catUnambiguous},
	{"unicode", catAmbiguous2},
	{"uninstall", catAmbiguous2},
	{"union", catReserved},
	{"unique", catReserved},
	{"unknown", catUnambiguous},
	{"unlock", catReserved},
	{"unregister", catUnambiguous},
	{"unsigned", catReserved},
	{"until", catUnambiguous},
	{"update", catReserved},
	{"upgrade", catUnambiguous},
	{"uri", catUnambiguous},
	{"url", catUnambiguous},
	{"usage", catReserved},
	{"use", catReserved},
	{"use_frm", catUnambiguous},
	{"user", catUnambiguous},
	{"user_resources", catUnambiguous},
	{"using", catReserved},
	{"utc_date", catReserved},
	{"utc_time", catReserved},
	{"utc_timestamp", catReserved},
	{"validate", catUnambiguous},
	{"validation", catUnambiguous},
	{"value", catUnambiguous},
	{"values", catReserved},
	{"var_pop", catReserved},
	{"var_samp", catReserved},
	{"varbinary", catReserved},
	{"varchar", catReserved},
	{"varcharacter", catReserved},
	{"variables", catUnambiguous},
	{"variance", catReserved},
	{"varying", catReserved},
	{"vcpu", catUnambiguous},
	{"vector", catUnambiguous},
	{"verify_key_constraints", catUnambiguous},
	{"view", catUnambiguous},
	{"virtual", catReserved},
	{"visible", catUnambiguous},
	{"wait", catUnambiguous},
	{"warnings", catUnambiguous},
	{"week", catUnambiguous},
	{"weight_string", catUnambiguous},
	{"when", catReserved},
	{"where", catReserved},
	{"while", catReserved},
	{"window", catReserved},
	{"with", catReserved},
	{"without", catUnambiguous},
	{"work", catUnambiguous},
	{"wrapper", catUnambiguous},
	{"write", catReserved},
	{"x509", catUnambiguous},
	{"xa", catAmbiguous2},
	{"xid", catUnambiguous},
	{"xml", catUnambiguous},
	{"xor", catReserved},
	{"year", catUnambiguous},
	{"year_month", catReserved},
	{"zerofill", catReserved},
	{"zone", catUnambiguous},
	{"||", catOperator},
}

// TestKeywordCompleteness verifies that every MySQL 8.0 keyword (excluding operators
// and optimizer hints) is registered in omni's keyword map.
func TestKeywordCompleteness(t *testing.T) {
	missing := 0
	for _, kw := range mysql8Keywords {
		if kw.Category == catOperator || kw.Category == catHint {
			continue // operators are handled by the scanner; hints use a separate system
		}
		// Check if this keyword is in the omni keyword map
		_, ok := keywords[kw.SQL]
		if !ok {
			t.Errorf("MySQL 8.0 keyword %q (category: %s) is NOT registered in omni's keyword map", kw.SQL, kw.Category)
			missing++
		}
	}
	if missing > 0 {
		t.Errorf("%d MySQL 8.0 keywords missing from omni's keyword map", missing)
	}
}

// TestKeywordClassification verifies that every registered MySQL 8.0 keyword
// has the correct category in omni's keywordCategories map.
func TestKeywordClassification(t *testing.T) {
	// Map mysql8KeywordCategory to omni's keywordCategory
	catMap := map[mysql8KeywordCategory]keywordCategory{
		catReserved:    kwCatReserved,
		catUnambiguous: kwCatUnambiguous,
		catAmbiguous1:  kwCatAmbiguous1,
		catAmbiguous2:  kwCatAmbiguous2,
		catAmbiguous3:  kwCatAmbiguous3,
		catAmbiguous4:  kwCatAmbiguous4,
	}

	misclassified := 0
	for _, kw := range mysql8Keywords {
		if kw.Category == catOperator || kw.Category == catHint {
			continue
		}
		expectedCat, ok := catMap[kw.Category]
		if !ok {
			continue // skip unknown categories
		}
		// Look up the keyword token
		tokType, registered := keywords[kw.SQL]
		if !registered {
			continue // completeness is checked by TestKeywordCompleteness
		}
		// Check classification
		actualCat, classified := keywordCategories[tokType]
		if !classified {
			// Not in keywordCategories — defaults to "unambiguous" behavior
			// (accepted by parseIdentifier since it's >= 700 and not reserved)
			if expectedCat != kwCatUnambiguous {
				t.Errorf("keyword %q (token %d): expected category %s but has no classification (defaults to unambiguous)",
					kw.SQL, tokType, kw.Category)
				misclassified++
			}
			continue
		}
		if actualCat != expectedCat {
			t.Errorf("keyword %q (token %d): expected category %s (%d) but got %d",
				kw.SQL, tokType, kw.Category, expectedCat, actualCat)
			misclassified++
		}
	}
	if misclassified > 0 {
		t.Errorf("%d keywords have incorrect classification", misclassified)
	}
}

// TestNoEqFoldForRegisteredKeywords verifies that no eqFold call in the parser
// matches a string that is also a registered keyword. This catches the anti-pattern
// where a keyword is registered but still checked via string comparison.
//
// Implementation: check all known eqFold target strings against the keyword map.
// This is a static list maintained alongside this test — when eqFold patterns
// are removed, remove them from this list too.
func TestNoEqFoldForRegisteredKeywords(t *testing.T) {
	// All strings currently matched via eqFold in the parser (excluding test files).
	// This list should shrink to zero as eqFold patterns are migrated.
	// Each entry is the lowercase string matched by eqFold.
	eqFoldStrings := []string{
		// replication.go — legacy alias (not a registered keyword)
		"master_log_file",
	}

	violations := 0
	for _, s := range eqFoldStrings {
		lower := strings.ToLower(s)
		if _, ok := keywords[lower]; ok {
			// No exceptions — all eqFold patterns for registered keywords must be migrated.
			// MySQL's parser uses keyword tokens for all 5 cases:
			// - @@global.var: lexer emits @ @ GLOBAL_SYM . ident (5 tokens)
			// - PROXY: PROXY_SYM keyword token in grammar
			// - CURRENT_USER: reserved keyword token in user rule
			// - PERSIST_ONLY: PERSIST_ONLY_SYM keyword token
			// - GROUP_REPLICATION: single keyword token
			t.Errorf("eqFold matches registered keyword %q — should use keyword token check instead", lower)
			violations++
		}
	}
	if violations > 0 {
		t.Errorf("%d eqFold patterns match registered keywords", violations)
	}
}
